// Generated by undra-bindgen from the Undra schema of `golden-stores` (schema hash 0xb38be47d1ea134a1). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
export const UndraIds = {
  schemaHash: 0xb38be47d1ea134a1n,
  namespace: "golden_stores",
  Objects: {
    Clock: {
      typeId: 0xbb5f80fd,
      new: 0x9dfc59b5,
    },
    Todos: {
      typeId: 0xf5e31faa,
      new: 0x35935dea,
      open: 0x0d940ccc,
      setFilter: 0x07781993,
      add: 0xd13d7ad7,
      remainingAfter: 0x63b9a759,
      changes: 0xe7ac349d,
    },
  },
  Functions: {
  },
  Ports: {
  },
  Queries: {
  },
} as const;
