// Generated by undra-bindgen from the Undra schema of `golden-stores` (schema hash 0xb38be47d1ea134a1). Do not edit.

import {
  CallTarget,
  ChangeOp,
  type Codec,
  type Duration,
  PatchError,
  Signal,
  type Timestamp,
  UndraCallError,
  UndraCore,
  UndraReader,
  UndraStore,
  UndraWriter,
  applyPatch,
  codecs,
  decodePatch,
  decodeValue,
} from "@undra/runtime";
import { type TodoError, TodoErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import {
  type Counter,
  CounterCodec,
  type Filter,
  FilterCodec,
  type Todo,
  TodoCodec,
} from "./types.js";

/** A store with a single signal and a constructor argument. */
export class Clock extends UndraStore {
  readonly now: Signal<Timestamp> = new Signal<Timestamp>(0);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle, { noCoalesce: [0] });
    this._signals = [this.now];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(zone: string, core: UndraCore = UndraCore.shared): Promise<Clock> {
    const w = new UndraWriter();
    w.writeStr(zone);
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Clock.typeId,
        UndraIds.Objects.Clock.new,
        w.finish(),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = new Clock(core, handle);
    await store._observeAll();
    return store;
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.now._set(decodeValue(codecs.timestamp, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `Clock.apply(signal: ${signalId})`);
    }
  }
}

/** The todo list. */
export class Todos extends UndraStore {
  readonly todos: Signal<Todo[]> = new Signal<Todo[]>([]);
  readonly filter: Signal<Filter> = new Signal<Filter>("all");
  /** Computed by the core; read-only. */
  readonly visible: Signal<Todo[]> = new Signal<Todo[]>([]);
  /** Computed by the core; read-only. */
  readonly remaining: Signal<number> = new Signal<number>(0);
  readonly selected: Signal<Todo | null> = new Signal<Todo | null>(null);
  readonly title: Signal<string> = new Signal<string>("");
  readonly counter: Signal<Counter> = new Signal<Counter>({ label: "", n: 0 });
  readonly tags: Signal<Map<string, number>> = new Signal<Map<string, number>>(new Map());
  readonly lastError: Signal<TodoError | null> = new Signal<TodoError | null>(null);
  readonly elapsed: Signal<Duration> = new Signal<Duration>(0);
  readonly created: Signal<Timestamp> = new Signal<Timestamp>(0);
  readonly blob: Signal<Uint8Array> = new Signal<Uint8Array>(new Uint8Array(0));
  readonly total: Signal<bigint> = new Signal<bigint>(0n);
  readonly default: Signal<boolean> = new Signal<boolean>(false);
  readonly uuid: Signal<string> = new Signal<string>("00000000-0000-0000-0000-000000000000");

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [
      this.todos,
      this.filter,
      this.visible,
      this.remaining,
      this.selected,
      this.title,
      this.counter,
      this.tags,
      this.lastError,
      this.elapsed,
      this.created,
      this.blob,
      this.total,
      this.default,
      this.uuid,
    ];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraCore.shared): Promise<Todos> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Todos.typeId,
        UndraIds.Objects.Todos.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = new Todos(core, handle);
    await store._observeAll();
    return store;
  }

  /**
   * @throws {TodoError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  static async open(path: string, core: UndraCore = UndraCore.shared): Promise<Todos> {
    const w = new UndraWriter();
    w.writeStr(path);
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Todos.typeId,
        UndraIds.Objects.Todos.open,
        w.finish(),
      );
    } catch (error) {
      throw UndraCallError.mapped(error, TodoErrorCodec);
    }
    const store = new Todos(core, handle);
    await store._observeAll();
    return store;
  }

  /**
   * Shows only the todos matching `f`.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async setFilter(f: Filter): Promise<void> {
    try {
      const w = new UndraWriter();
      FilterCodec.encode(w, f);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Todos.setFilter,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "Todos.setFilter");
    }
  }

  /**
   * Adds a todo.
   * @throws {TodoError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async add(title: string, signal?: AbortSignal): Promise<Todo> {
    const w = new UndraWriter();
    w.writeStr(title);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Todos.add,
        w.finish(),
        signal,
      );
      return decodeValue(TodoCodec, body);
    } catch (error) {
      throw UndraCallError.mapped(error, TodoErrorCodec);
    }
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  async remainingAfter(id: string): Promise<number> {
    const w = new UndraWriter();
    w.writeUuid(id);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Todos.remainingAfter,
        w.finish(),
      );
      return decodeValue(codecs.u32, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /** Iterating throws UndraCallError; leaving the loop early ends the stream quietly. */
  changes(): AsyncIterable<Todo> {
    const source = this.core.stream(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.Todos.changes,
      new Uint8Array(0),
    );
    return decodeStream(source, TodoCodec, (error) => UndraCallError.mappedStream(error));
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.todos._set(decodeValue(vecTodo, value));
          } else if (op === ChangeOp.KeyedPatch) {
            const r = new UndraReader(value);
            const ops = decodePatch(r, TodoCodec);
            r.finish();
            try {
              this.todos._set(applyPatch(this.todos.peek(), ops));
            } catch (error) {
              if (!(error instanceof PatchError)) throw error;
              this._resync(0);
            }
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.filter._set(decodeValue(FilterCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.visible._set(decodeValue(vecTodo, value));
          } else if (op === ChangeOp.KeyedPatch) {
            const r = new UndraReader(value);
            const ops = decodePatch(r, TodoCodec);
            r.finish();
            try {
              this.visible._set(applyPatch(this.visible.peek(), ops));
            } catch (error) {
              if (!(error instanceof PatchError)) throw error;
              this._resync(2);
            }
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.remaining._set(decodeValue(codecs.u32, value));
          }
          break;
        case 4:
          if (op === ChangeOp.FullValue) {
            this.selected._set(decodeValue(optionTodo, value));
          }
          break;
        case 5:
          if (op === ChangeOp.FullValue) {
            this.title._set(decodeValue(codecs.string, value));
          }
          break;
        case 6:
          if (op === ChangeOp.FullValue) {
            this.counter._set(decodeValue(CounterCodec, value));
          }
          break;
        case 7:
          if (op === ChangeOp.FullValue) {
            this.tags._set(decodeValue(mapStringU32, value));
          }
          break;
        case 8:
          if (op === ChangeOp.FullValue) {
            this.lastError._set(decodeValue(optionTodoError, value));
          }
          break;
        case 9:
          if (op === ChangeOp.FullValue) {
            this.elapsed._set(decodeValue(codecs.duration, value));
          }
          break;
        case 10:
          if (op === ChangeOp.FullValue) {
            this.created._set(decodeValue(codecs.timestamp, value));
          }
          break;
        case 11:
          if (op === ChangeOp.FullValue) {
            this.blob._set(decodeValue(codecs.bytes, value));
          }
          break;
        case 12:
          if (op === ChangeOp.FullValue) {
            this.total._set(decodeValue(codecs.u64, value));
          }
          break;
        case 13:
          if (op === ChangeOp.FullValue) {
            this.default._set(decodeValue(codecs.bool, value));
          }
          break;
        case 14:
          if (op === ChangeOp.FullValue) {
            this.uuid._set(decodeValue(codecs.uuid, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `Todos.apply(signal: ${signalId})`);
    }
  }

  /** Re-observes a signal whose mirror diverged from the core, to receive a full value. */
  private _resync(signalId: number): void {
    for (const on of [false, true]) {
      this.core.observe(this.handle, signalId, on).catch((error: unknown) => {
        this.core.report(error, `Todos.resync(signal: ${signalId})`);
      });
    }
  }
}

/** Decodes every item of a core stream; a failure of the stream or of an item goes through `mapError`. */
async function* decodeStream<T>(
  source: AsyncIterable<Uint8Array>,
  codec: Codec<T>,
  mapError: (error: unknown) => unknown,
): AsyncGenerator<T, void, undefined> {
  try {
    for await (const body of source) yield decodeValue(codec, body);
  } catch (error) {
    throw mapError(error);
  }
}

const vecTodo = codecs.vec(TodoCodec);
const optionTodo = codecs.option(TodoCodec);
const mapStringU32 = codecs.map(codecs.string, codecs.u32);
const optionTodoError = codecs.option(TodoErrorCodec);
