// Generated by keel-bindgen from the Keel schema of `playground-core` (schema hash 0xcff750bbff3ee758). Do not edit.

package golden.full

import dev.keel.runtime.KeelCore
import dev.keel.runtime.KeelObject
import dev.keel.runtime.KeelReplyException
import dev.keel.runtime.wire.Codecs
import dev.keel.runtime.wire.Handle
import dev.keel.runtime.wire.KeelWriter
import dev.keel.runtime.wire.Payloads.CallTarget
import dev.keel.runtime.wire.decodeAll
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map

/** Adds numbers. */
class Calculator private constructor(core: KeelCore, handle: Long) : KeelObject(core, handle) {
    constructor(ctx: KeelCore = KeelCore.shared) : this(
        ctx,
        ctx.construct(KeelIds.Objects.Calculator.TYPE_ID, KeelIds.Objects.Calculator.NEW, ByteArray(0)),
    )

    fun add(a: Int, b: Int): Int {
        val w = KeelWriter()
        w.writeI32(a)
        w.writeI32(b)
        val body = this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.Calculator.ADD),
            KeelIds.Objects.Calculator.ADD,
            w.toByteArray(),
        )
        return Codecs.i32.decodeAll(body)
    }

    /** @throws HttpError */
    suspend fun fetch(url: String): String {
        val w = KeelWriter()
        w.writeStr(url)
        val body = try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.Calculator.FETCH),
                KeelIds.Objects.Calculator.FETCH,
                w.toByteArray(),
            )
        } catch (e: KeelReplyException) {
            throw HttpError.fromReply(e)
        }
        return Codecs.string.decodeAll(body)
    }

    fun ticks(): Flow<UInt> {
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.Calculator.TICKS),
            KeelIds.Objects.Calculator.TICKS,
            ByteArray(0),
        )
        return stream.map { bytes -> Codecs.u32.decodeAll(bytes) }
    }

    /** @throws TodoError */
    fun watch(priority: Priority): Flow<Todo> {
        val w = KeelWriter()
        Priority.encode(w, priority)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.Calculator.WATCH),
            KeelIds.Objects.Calculator.WATCH,
            w.toByteArray(),
        )
        return stream
            .map { bytes -> Todo.decodeAll(bytes) }
            .catch { error ->
                throw if (error is KeelReplyException) TodoError.fromReply(error) else error
            }
    }

    companion object {
        fun create(ctx: KeelCore = KeelCore.shared): Calculator {
            val handle = ctx.construct(KeelIds.Objects.Calculator.TYPE_ID, KeelIds.Objects.Calculator.NEW, ByteArray(0))
            return Calculator(ctx, handle)
        }
    }
}

fun greet(name: String, ctx: KeelCore = KeelCore.shared): String {
    val w = KeelWriter()
    w.writeStr(name)
    val body = ctx.callSync(
        CallTarget.FreeFunction(KeelIds.Functions.GREET),
        KeelIds.Functions.GREET,
        w.toByteArray(),
    )
    return Codecs.string.decodeAll(body)
}

/** @throws TodoError */
suspend fun ping(ctx: KeelCore = KeelCore.shared) {
    try {
        ctx.call(
            CallTarget.FreeFunction(KeelIds.Functions.PING),
            KeelIds.Functions.PING,
            ByteArray(0),
        )
    } catch (e: KeelReplyException) {
        throw TodoError.fromReply(e)
    }
}
