// Generated by keel-bindgen from the Keel schema of `playground-core` (schema hash 0x691eee0733e4a44f). Do not edit.

package golden.full

import dev.keel.runtime.KeelCore
import dev.keel.runtime.KeelReplyException
import dev.keel.runtime.KeelStore
import dev.keel.runtime.wire.Codecs
import dev.keel.runtime.wire.Handle
import dev.keel.runtime.wire.KeelReader
import dev.keel.runtime.wire.KeelWriter
import dev.keel.runtime.wire.Payloads.CallTarget
import dev.keel.runtime.wire.Payloads.ChangeOp
import dev.keel.runtime.wire.Timestamp
import dev.keel.runtime.wire.decodeAll
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Observes the `todos` query (cache key `todos:{page}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
class TodosQueryHandle private constructor(core: KeelCore, handle: Long) : KeelStore(core, handle) {
    private val _data: MutableStateFlow<Page?> = signal(null)
    /** The latest successful result, if any. */
    val data: StateFlow<Page?> = _data.asStateFlow()
    private val _status: MutableStateFlow<QueryStatus> = signal(QueryStatus.IDLE)
    /** Where the query is in its fetch lifecycle. */
    val status: StateFlow<QueryStatus> = _status.asStateFlow()
    private val _error: MutableStateFlow<TodoError?> = signal(null)
    /** The error of the latest failed fetch, cleared by the next success. */
    val error: StateFlow<TodoError?> = _error.asStateFlow()
    private val _fetching: MutableStateFlow<Boolean> = signal(false)
    /** Whether a fetch is in flight (also true while refetching stale data). */
    val fetching: StateFlow<Boolean> = _fetching.asStateFlow()
    private val _updatedAt: MutableStateFlow<Timestamp?> = signal(null)
    /** When `data` was last updated. */
    val updatedAt: StateFlow<Timestamp?> = _updatedAt.asStateFlow()

    init {
        core.observe(handle, UInt.MAX_VALUE, true)
    }

    /** Fetches again now, even if the data is fresh. */
    fun refetch() {
        this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.TodosQueryHandle.REFETCH),
            KeelIds.Objects.TodosQueryHandle.REFETCH,
            ByteArray(0),
        )
    }

    /** Marks the cached entry stale; it refetches while observed. */
    fun invalidate() {
        this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.TodosQueryHandle.INVALIDATE),
            KeelIds.Objects.TodosQueryHandle.INVALIDATE,
            ByteArray(0),
        )
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: KeelReader) {
        when (signalId) {
            0u -> {
                if (op == ChangeOp.FULL) {
                    _data.value = codecOptionPage.decode(reader)
                    reader.finish()
                }
            }
            1u -> {
                if (op == ChangeOp.FULL) {
                    _status.value = QueryStatus.decode(reader)
                    reader.finish()
                }
            }
            2u -> {
                if (op == ChangeOp.FULL) {
                    _error.value = codecOptionTodoError.decode(reader)
                    reader.finish()
                }
            }
            3u -> {
                if (op == ChangeOp.FULL) {
                    _fetching.value = Codecs.bool.decode(reader)
                    reader.finish()
                }
            }
            4u -> {
                if (op == ChangeOp.FULL) {
                    _updatedAt.value = codecOptionTimestamp.decode(reader)
                    reader.finish()
                }
            }
            else -> Unit
        }
    }

    companion object {
        fun create(page: UInt, ctx: KeelCore = KeelCore.shared): TodosQueryHandle {
            val w = KeelWriter()
            w.writeU32(page)
            val handle = ctx.construct(KeelIds.Objects.TodosQueryHandle.TYPE_ID, KeelIds.Objects.TodosQueryHandle.NEW, w.toByteArray())
            return TodosQueryHandle(ctx, handle)
        }
    }
}

/**
 * Runs the `add_todo` mutation.
 * @throws TodoError
 */
suspend fun addTodo(title: String, ctx: KeelCore = KeelCore.shared): Todo {
    val w = KeelWriter()
    w.writeStr(title)
    val body = try {
        ctx.call(
            CallTarget.FreeFunction(KeelIds.Queries.ADD_TODO),
            KeelIds.Queries.ADD_TODO,
            w.toByteArray(),
        )
    } catch (e: KeelReplyException) {
        throw TodoError.fromReply(e)
    }
    return Todo.decodeAll(body)
}

private val codecOptionPage = Codecs.option(Page)
private val codecOptionTodoError = Codecs.option(TodoError)
private val codecOptionTimestamp = Codecs.option(Codecs.timestamp)
