// Generated by keel-bindgen from the Keel schema of `golden-ports` (schema hash 0xde22690132b0e949). Do not edit.

package golden.ports

import dev.keel.runtime.KeelEnum
import dev.keel.runtime.KeelRecord
import dev.keel.runtime.wire.Codecs
import dev.keel.runtime.wire.KeelCodec
import dev.keel.runtime.wire.KeelReader
import dev.keel.runtime.wire.KeelWriter
import dev.keel.runtime.wire.WireException

data class HttpRequest(
    val url: String,
    val headers: Map<String, String>,
    val body: ByteArray?,
) : KeelRecord {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is HttpRequest) return false
        return url == other.url && headers == other.headers && body.contentEquals(other.body)
    }

    override fun hashCode(): Int {
        var result = url.hashCode()
        result = 31 * result + headers.hashCode()
        result = 31 * result + body.contentHashCode()
        return result
    }

    companion object : KeelCodec<HttpRequest> {
        override fun encode(w: KeelWriter, v: HttpRequest) {
            w.writeStr(v.url)
            codecMapStringString.encode(w, v.headers)
            codecOptionBytes.encode(w, v.body)
        }

        override fun decode(r: KeelReader): HttpRequest = HttpRequest(
            url = r.readStr(),
            headers = codecMapStringString.decode(r),
            body = codecOptionBytes.decode(r),
        )
    }
}

data class HttpResponse(
    val status: UShort,
    val body: ByteArray,
) : KeelRecord {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is HttpResponse) return false
        return status == other.status && body.contentEquals(other.body)
    }

    override fun hashCode(): Int {
        var result = status.hashCode()
        result = 31 * result + body.contentHashCode()
        return result
    }

    companion object : KeelCodec<HttpResponse> {
        override fun encode(w: KeelWriter, v: HttpResponse) {
            w.writeU16(v.status)
            w.writeBytes(v.body)
        }

        override fun decode(r: KeelReader): HttpResponse = HttpResponse(
            status = r.readU16(),
            body = r.readBytes(),
        )
    }
}

enum class NetKind(val index: UShort) : KeelEnum {
    WIFI(0u),
    CELLULAR(1u),
    NONE(2u);

    companion object : KeelCodec<NetKind> {
        override fun encode(w: KeelWriter, v: NetKind) = w.writeU16(v.index)

        override fun decode(r: KeelReader): NetKind {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> WIFI
                1 -> CELLULAR
                2 -> NONE
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "NetKind")
            }
        }
    }
}

private val codecMapStringString = Codecs.map(Codecs.string, Codecs.string)
private val codecOptionBytes = Codecs.option(Codecs.bytes)
