// Generated by undra-bindgen from the Undra schema of `golden-errors` (schema hash 0x8005bee6ac51e549). Do not edit.

package golden.errors

import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter

data class Payload(
    val text: String,
    val failure: HttpError?,
    val history: List<Boxed>,
) : UndraRecord {
    companion object : UndraCodec<Payload> {
        override fun encode(w: UndraWriter, v: Payload) {
            w.writeStr(v.text)
            codecOptionHttpError.encode(w, v.failure)
            codecVecBoxed.encode(w, v.history)
        }

        override fun decode(r: UndraReader): Payload = Payload(
            text = r.readStr(),
            failure = codecOptionHttpError.decode(r),
            history = codecVecBoxed.decode(r),
        )
    }
}

private val codecOptionHttpError = Codecs.option(HttpError)
private val codecVecBoxed = Codecs.vec(Boxed)
