// Generated by undra-bindgen from the Undra schema of `golden-object-graph` (schema hash 0x63ce15b6ad53100b). Do not edit.

import { type Codec, UndraError, WireError } from "@undra/runtime";

export type MailErrorKind = "noThread";

export abstract class MailError extends UndraError {
  declare readonly kind: MailErrorKind;
}

export namespace MailError {
  export class NoThread extends MailError {
    declare readonly kind: "noThread";

    constructor() {
      super("noThread", "no such thread");
    }
  }
}

export const MailErrorCodec: Codec<MailError> = {
  encode(w, v) {
    if (v instanceof MailError.NoThread) {
      w.writeU16(0);
    } else {
      throw new TypeError(`unknown MailError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new MailError.NoThread();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "MailError" });
    }
  },
};
