// Generated by undra-bindgen from the Undra schema of `golden-object-graph` (schema hash 0x9d413883b026d02f). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
export const UndraIds = {
  schemaHash: 0x9d413883b026d02fn,
  namespace: "golden_object_graph",
  Objects: {
    Account: {
      typeId: 0x59f8a2fc,
      new: 0xe01ae200,
      mailbox: 0x24623112,
      openThread: 0x87b7ff03,
      moveTo: 0xde2a315d,
      drafts: 0xbf5232f2,
      mailboxes: 0x95c6b5d2,
      chat: 0x0c44f808,
      merge: 0x15297446,
      findThread: 0xb8c641ae,
    },
    Mailbox: {
      typeId: 0xb211566b,
      name: 0x51436a9c,
    },
    Thread: {
      typeId: 0xea904991,
      id: 0xe5a9b838,
    },
    ChatStore: {
      typeId: 0x98ddf884,
      new: 0x70c95548,
      send: 0xbcb1a2c4,
    },
  },
  Functions: {
    mailboxOf: 0xebbc4349,
  },
  Ports: {
  },
  Queries: {
  },
} as const;
