// Generated by undra-bindgen from the Undra schema of `golden-object-graph` (schema hash 0x9d413883b026d02f). Do not edit.

import {
  CallTarget,
  UndraCallError,
  UndraCore,
  UndraObject,
  UndraWriter,
  adopt,
  adoptList,
  adoptObject,
  adoptOptional,
  codecs,
  decodeValue,
  requireOwn,
} from "@undra/runtime";
import { UndraGoldenObjectGraph } from "./core.js";
import { MailErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import { ChatStore } from "./stores.js";

/** An account that hands out its mailboxes. */
export class Account extends UndraObject {
  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraGoldenObjectGraph.core): Promise<Account> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Account.typeId,
        UndraIds.Objects.Account.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    return adopt(core, handle, Account);
  }

  /**
   * The mailbox for `folder`, created on first use.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  async mailbox(folder: string): Promise<Mailbox> {
    const w = new UndraWriter();
    w.writeStr(folder);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Account.mailbox,
        w.finish(),
      );
      return await adoptObject(this.core, body, Mailbox);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /**
   * Opens a thread.
   * @throws {MailError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async openThread(id: number, signal?: AbortSignal): Promise<Thread> {
    const w = new UndraWriter();
    w.writeU32(id);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Account.openThread,
        w.finish(),
        signal,
      );
      return await adoptObject(this.core, body, Thread);
    } catch (error) {
      throw UndraCallError.mapped(error, MailErrorCodec);
    }
  }

  /**
   * Moves a message to `target`.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async moveTo(message: number, target: Mailbox): Promise<void> {
    try {
      const w = new UndraWriter();
      w.writeU32(message);
      w.writeU64(requireOwn(this.core, target));
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Account.moveTo,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "Account.moveTo");
    }
  }

  /**
   * The drafts folder, if there is one.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  async drafts(): Promise<Mailbox | null> {
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Account.drafts,
        new Uint8Array(0),
      );
      return await adoptOptional(this.core, body, Mailbox);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /**
   * Every mailbox.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  async mailboxes(): Promise<Mailbox[]> {
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Account.mailboxes,
        new Uint8Array(0),
      );
      return await adoptList(this.core, body, Mailbox);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /**
   * The chat with `peer`: a store.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  async chat(peer: number): Promise<ChatStore> {
    const w = new UndraWriter();
    w.writeU32(peer);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Account.chat,
        w.finish(),
      );
      return await adoptObject(this.core, body, ChatStore);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /**
   * Merges the given mailboxes into the first and returns how many there were.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  async merge(boxes: Mailbox[], extra: Mailbox | null): Promise<number> {
    const w = new UndraWriter();
    handles.encode(w, boxes.map((item) => requireOwn(this.core, item)));
    optionalHandle.encode(w, extra === null ? null : requireOwn(this.core, extra));
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Account.merge,
        w.finish(),
      );
      return decodeValue(codecs.u32, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /**
   * Finds a thread, if it exists.
   * @throws {MailError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  async findThread(id: number): Promise<Thread | null> {
    const w = new UndraWriter();
    w.writeU32(id);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Account.findThread,
        w.finish(),
      );
      return await adoptOptional(this.core, body, Thread);
    } catch (error) {
      throw UndraCallError.mapped(error, MailErrorCodec);
    }
  }
}

/** A folder. */
export class Mailbox extends UndraObject {
  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  async name(): Promise<string> {
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Mailbox.name,
        new Uint8Array(0),
      );
      return decodeValue(codecs.string, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }
}

/** A conversation. */
export class Thread extends UndraObject {
  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  async id(): Promise<number> {
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Thread.id,
        new Uint8Array(0),
      );
      return decodeValue(codecs.u32, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }
}

/**
 * The mailbox of `account` for `folder`.
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 */
export async function mailboxOf(
  account: Account,
  folder: string,
  core: UndraCore = UndraGoldenObjectGraph.core,
): Promise<Mailbox> {
  const w = new UndraWriter();
  w.writeU64(requireOwn(core, account));
  w.writeStr(folder);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.mailboxOf,
      w.finish(),
    );
    return await adoptObject(core, body, Mailbox);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

const handles = codecs.vec(codecs.u64);
const optionalHandle = codecs.option(codecs.u64);
