// Generated by undra-bindgen from the Undra schema of `golden-object-graph` (schema hash 0x9d413883b026d02f). Do not edit.

import { type Codec } from "@undra/runtime";

/** A message in a chat. */
export interface Message {
  id: number;
  text: string;
}

export const MessageCodec: Codec<Message> = {
  encode(w, v) {
    w.writeU32(v.id);
    w.writeStr(v.text);
  },
  decode(r) {
    return {
      id: r.readU32(),
      text: r.readStr(),
    };
  },
};
