// Generated by keel-bindgen from the Keel schema of `golden-errors` (schema hash 0x8005bee6ac51e549). Do not edit.

package golden.errors

import dev.keel.runtime.KeelException
import dev.keel.runtime.KeelReplyException
import dev.keel.runtime.wire.KeelCodec
import dev.keel.runtime.wire.KeelReader
import dev.keel.runtime.wire.KeelWriter
import dev.keel.runtime.wire.Payloads.ReplyStatus
import dev.keel.runtime.wire.WireException
import dev.keel.runtime.wire.decodeAll

/** An error that wraps a record, so errors and types reference each other. */
sealed class Boxed(message: String) : KeelException(message) {
    data class Holding(val value: Payload) : Boxed("holding a payload")

    companion object : KeelCodec<Boxed> {
        override fun encode(w: KeelWriter, v: Boxed) {
            when (v) {
                is Holding -> {
                    w.writeU16(0u)
                    Payload.encode(w, v.value)
                }
            }
        }

        override fun decode(r: KeelReader): Boxed {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Holding(value = Payload.decode(r))
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Boxed")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: KeelReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}

/** A network failure. */
sealed class HttpError(message: String) : KeelException(message) {
    data object Timeout : HttpError("timed out")
    data class Status(val value: UShort) : HttpError("status ${value}")
    data class Network(val value: String) : HttpError("network error: ${value}")
    data object Cancelled : HttpError("cancelled")

    companion object : KeelCodec<HttpError> {
        override fun encode(w: KeelWriter, v: HttpError) {
            when (v) {
                Timeout -> w.writeU16(0u)
                is Status -> {
                    w.writeU16(1u)
                    w.writeU16(v.value)
                }
                is Network -> {
                    w.writeU16(2u)
                    w.writeStr(v.value)
                }
                Cancelled -> w.writeU16(3u)
            }
        }

        override fun decode(r: KeelReader): HttpError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Timeout
                1 -> Status(value = r.readU16())
                2 -> Network(value = r.readStr())
                3 -> Cancelled
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "HttpError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: KeelReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}

/** What can go wrong with todos. */
sealed class TodoError(message: String) : KeelException(message) {
    /** The title was blank after trimming. */
    data object EmptyTitle : TodoError("title cannot be empty")
    data class Http(override val cause: HttpError) : TodoError(cause.message.orEmpty())
    data class NotFound(val value: String) : TodoError("todo \"${value}\" not found, {sorry}")
    data class Storage(val reason: String, val code: Int, val message_: String) : TodoError("storage failure ${code}: ${reason} (\$${message_})")
    data class Range(val value0: UInt, val value1: UInt) : TodoError("${value0} is not below ${value1}")
    data class Detail(val default: String) : TodoError("detail ${default}")

    companion object : KeelCodec<TodoError> {
        override fun encode(w: KeelWriter, v: TodoError) {
            when (v) {
                EmptyTitle -> w.writeU16(0u)
                is Http -> {
                    w.writeU16(1u)
                    HttpError.encode(w, v.cause)
                }
                is NotFound -> {
                    w.writeU16(2u)
                    w.writeStr(v.value)
                }
                is Storage -> {
                    w.writeU16(3u)
                    w.writeStr(v.reason)
                    w.writeI32(v.code)
                    w.writeStr(v.message_)
                }
                is Range -> {
                    w.writeU16(4u)
                    w.writeU32(v.value0)
                    w.writeU32(v.value1)
                }
                is Detail -> {
                    w.writeU16(5u)
                    w.writeStr(v.default)
                }
            }
        }

        override fun decode(r: KeelReader): TodoError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> EmptyTitle
                1 -> Http(cause = HttpError.decode(r))
                2 -> NotFound(value = r.readStr())
                3 -> Storage(reason = r.readStr(), code = r.readI32(), message_ = r.readStr())
                4 -> Range(value0 = r.readU32(), value1 = r.readU32())
                5 -> Detail(default = r.readStr())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "TodoError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: KeelReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}
