// Generated by keel-bindgen from the Keel schema of `golden-errors` (schema hash 0xa3855d2aa1884ad8). Do not edit.

package golden.errors

import dev.keel.runtime.KeelRecord
import dev.keel.runtime.wire.Codecs
import dev.keel.runtime.wire.KeelCodec
import dev.keel.runtime.wire.KeelReader
import dev.keel.runtime.wire.KeelWriter

data class Payload(
    val text: String,
    val failure: HttpError?,
    val history: List<Boxed>,
) : KeelRecord {
    companion object : KeelCodec<Payload> {
        override fun encode(w: KeelWriter, v: Payload) {
            w.writeStr(v.text)
            codecOptionHttpError.encode(w, v.failure)
            codecVecBoxed.encode(w, v.history)
        }

        override fun decode(r: KeelReader): Payload = Payload(
            text = r.readStr(),
            failure = codecOptionHttpError.decode(r),
            history = codecVecBoxed.decode(r),
        )
    }
}

private val codecOptionHttpError = Codecs.option(HttpError)
private val codecVecBoxed = Codecs.vec(Boxed)
