// Generated by keel-bindgen from the Keel schema of `playground-core` (schema hash 0x3b1bd1062551c158). Do not edit.

import {
  KeelCore,
  type KeelPort,
  KeelPortError,
  KeelReader,
  KeelWriter,
  type PortImpl,
  codecs,
  encodeValue,
} from "@keel/runtime";
import { HttpError, HttpErrorCodec } from "./errors.js";
import { KeelIds } from "./ids.js";
import {
  type HttpRequest,
  HttpRequestCodec,
  type HttpResponse,
  HttpResponseCodec,
  type NetKind,
  NetKindCodec,
} from "./types.js";

/** Sends the events of this port from the host to the core. */
export class ConnectivityEvents {
  constructor(private readonly core: KeelCore = KeelCore.shared) {}

  changed(online: boolean, kind: NetKind): void {
    const w = new KeelWriter();
    w.writeBool(online);
    NetKindCodec.encode(w, kind);
    this.core.event(
      KeelIds.Ports.Connectivity.portId,
      KeelIds.Ports.Connectivity.changed,
      w.finish(),
    );
  }
}

export interface Http extends KeelPort {
  /** @throws {HttpError} */
  request(req: HttpRequest): Promise<HttpResponse>;
}

/** Adapts an implementation of `Http` to `KeelCore.registerPort(KeelIds.Ports.Http.portId, ..)`. */
export function httpPortImpl(impl: Http): PortImpl {
  return {
    sync: false,
    methods: {
      [KeelIds.Ports.Http.request]: async (args) => {
        const r = new KeelReader(args);
        const req = HttpRequestCodec.decode(r);
        r.finish();
        try {
          return encodeValue(HttpResponseCodec, await impl.request(req));
        } catch (error) {
          if (error instanceof HttpError) {
            throw new KeelPortError(encodeValue(HttpErrorCodec, error));
          }
          throw error;
        }
      },
    },
  };
}

export interface Kv extends KeelPort {
  get(key: string): Promise<Uint8Array | null>;
  set(key: string, value: Uint8Array): Promise<void>;
}

/** Adapts an implementation of `Kv` to `KeelCore.registerPort(KeelIds.Ports.Kv.portId, ..)`. */
export function kvPortImpl(impl: Kv): PortImpl {
  return {
    sync: false,
    methods: {
      [KeelIds.Ports.Kv.get]: async (args) => {
        const r = new KeelReader(args);
        const key = r.readStr();
        r.finish();
        return encodeValue(optionBytes, await impl.get(key));
      },
      [KeelIds.Ports.Kv.set]: async (args) => {
        const r = new KeelReader(args);
        const key = r.readStr();
        const value = codecs.bytes.decode(r);
        r.finish();
        await impl.set(key, value);
        return new Uint8Array(0);
      },
    },
  };
}

export interface WallClock extends KeelPort {
  nowMs(): bigint;
  monotonicNs(): bigint;
}

/** Adapts an implementation of `WallClock` to `KeelCore.registerPort(KeelIds.Ports.WallClock.portId, ..)`. */
export function wallClockPortImpl(impl: WallClock): PortImpl {
  return {
    sync: true,
    methods: {
      [KeelIds.Ports.WallClock.nowMs]: () => {
        return encodeValue(codecs.i64, impl.nowMs());
      },
      [KeelIds.Ports.WallClock.monotonicNs]: () => {
        return encodeValue(codecs.u64, impl.monotonicNs());
      },
    },
  };
}

const optionBytes = codecs.option(codecs.bytes);
