// Generated by keel-bindgen from the Keel schema of `playground-core` (schema hash 0xcff750bbff3ee758). Do not edit.

import {
  ALL_SIGNALS,
  CallTarget,
  ChangeOp,
  KeelCore,
  KeelStore,
  KeelWriter,
  Signal,
  type Timestamp,
  codecs,
  decodeValue,
} from "@keel/runtime";
import { TodoError, TodoErrorCodec } from "./errors.js";
import { KeelIds } from "./ids.js";
import {
  type Page,
  PageCodec,
  type QueryStatus,
  QueryStatusCodec,
  type Todo,
  TodoCodec,
} from "./types.js";

/**
 * Observes the `todos` query (cache key `todos:{page}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class TodosQueryHandle extends KeelStore {
  /** The latest successful result, if any. */
  readonly data: Signal<Page | null> = new Signal<Page | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<TodoError | null> = new Signal<TodoError | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: KeelCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  static async create(page: number, core: KeelCore = KeelCore.shared): Promise<TodosQueryHandle> {
    const w = new KeelWriter();
    w.writeU32(page);
    const handle = await core.construct(
      KeelIds.Objects.TodosQueryHandle.typeId,
      KeelIds.Objects.TodosQueryHandle.new,
      w.finish(),
    );
    const store = new TodosQueryHandle(core, handle);
    await core.observe(handle, ALL_SIGNALS, true);
    return store;
  }

  /** Fetches again now, even if the data is fresh. */
  async refetch(): Promise<void> {
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      KeelIds.Objects.TodosQueryHandle.refetch,
      new Uint8Array(0),
    );
  }

  /** Marks the cached entry stale; it refetches while observed. */
  async invalidate(): Promise<void> {
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      KeelIds.Objects.TodosQueryHandle.invalidate,
      new Uint8Array(0),
    );
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    switch (signalId) {
      case 0:
        if (op === ChangeOp.FullValue) {
          this.data._set(decodeValue(optionPage, value));
        }
        break;
      case 1:
        if (op === ChangeOp.FullValue) {
          this.status._set(decodeValue(QueryStatusCodec, value));
        }
        break;
      case 2:
        if (op === ChangeOp.FullValue) {
          this.error._set(decodeValue(optionTodoError, value));
        }
        break;
      case 3:
        if (op === ChangeOp.FullValue) {
          this.fetching._set(decodeValue(codecs.bool, value));
        }
        break;
      case 4:
        if (op === ChangeOp.FullValue) {
          this.updatedAt._set(decodeValue(optionTimestamp, value));
        }
        break;
      default:
        break;
    }
  }
}

/**
 * Runs the `add_todo` mutation.
 * @throws {TodoError}
 */
export async function addTodo(
  title: string,
  core: KeelCore = KeelCore.shared,
  signal?: AbortSignal,
): Promise<Todo> {
  const w = new KeelWriter();
  w.writeStr(title);
  let body: Uint8Array;
  try {
    body = await core.call(
      { target: CallTarget.FreeFunction },
      KeelIds.Queries.addTodo,
      w.finish(),
      signal,
    );
  } catch (error) {
    throw TodoError.fromReply(error);
  }
  return decodeValue(TodoCodec, body);
}

const optionPage = codecs.option(PageCodec);
const optionTodoError = codecs.option(TodoErrorCodec);
const optionTimestamp = codecs.option(codecs.timestamp);
