/* Generated by undra: do not edit.
 *
 * golden_callbacks_undra.h: the entry point of the Undra core `golden_callbacks` (C ABI version 2, docs/SPEC.md 6).
 * The core exports this one function. It returns the core's `UndraApi` table (declared by
 * undra.h), as `const void *` so that undra.h stays the one owner of that type.
 */
#ifndef GOLDEN_CALLBACKS_UNDRA_H
#define GOLDEN_CALLBACKS_UNDRA_H

#ifdef __cplusplus
extern "C" {
#endif

const void *golden_callbacks_undra_api(void);

#ifdef __cplusplus
}
#endif

#endif /* GOLDEN_CALLBACKS_UNDRA_H */
