// Generated by undra-bindgen from the Undra schema of `golden-recursive` (schema hash 0xfbaf2349b362d004). Do not edit.

import { type Codec, UndraError, WireError } from "@undra/runtime";

export type ParseErrorKind = "eof" | "nested";

/** A parse failure that can wrap the failure it came from. */
export abstract class ParseError extends UndraError {
  declare readonly kind: ParseErrorKind;
}

export namespace ParseError {
  export class Eof extends ParseError {
    declare readonly kind: "eof";

    constructor() {
      super("eof", "unexpected end of input");
    }
  }

  export class Nested extends ParseError {
    declare readonly kind: "nested";

    constructor(readonly depth: number, readonly inner: ParseError) {
      super("nested", `failed at depth ${depth}`);
    }
  }
}

export const ParseErrorCodec: Codec<ParseError> = {
  encode(w, v) {
    if (v instanceof ParseError.Eof) {
      w.writeU16(0);
    } else if (v instanceof ParseError.Nested) {
      w.writeU16(1);
      w.writeU32(v.depth);
      ParseErrorCodec.encode(w, v.inner);
    } else {
      throw new TypeError(`unknown ParseError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new ParseError.Eof();
      case 1:
        return new ParseError.Nested(r.readU32(), ParseErrorCodec.decode(r));
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "ParseError" });
    }
  },
};
