// Generated by undra-bindgen from the Undra schema of `golden-recursive` (schema hash 0xfbaf2349b362d004). Do not edit.

import {
  CallTarget,
  UndraCallError,
  UndraCore,
  UndraWriter,
  codecs,
  decodeValue,
} from "@undra/runtime";
import { ParseErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import { type Expr, ExprCodec, type ListNode, ListNodeCodec } from "./types.js";

/**
 * Evaluates an expression.
 * @throws {ParseError}
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
 */
export async function evaluate(
  expr: Expr,
  core: UndraCore = UndraCore.shared,
  signal?: AbortSignal,
): Promise<number> {
  const w = new UndraWriter();
  ExprCodec.encode(w, expr);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.evaluate,
      w.finish(),
      signal,
    );
    return decodeValue(codecs.f64, body);
  } catch (error) {
    throw UndraCallError.mapped(error, ParseErrorCodec);
  }
}

/**
 * Reverses a list.
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 */
export async function reverse(
  list: ListNode,
  core: UndraCore = UndraCore.shared,
): Promise<ListNode> {
  const w = new UndraWriter();
  ListNodeCodec.encode(w, list);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.reverse,
      w.finish(),
    );
    return decodeValue(ListNodeCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}
