// Generated by undra-bindgen from the Undra schema of `golden-recursive` (schema hash 0xfbaf2349b362d004). Do not edit.

import { type Codec, WireError, codecs } from "@undra/runtime";

/** Holds a `Parent` that holds a `Child`. */
export interface Child {
  name: string;
  parent: Parent | null;
}

export const ChildCodec: Codec<Child> = {
  encode(w, v) {
    w.writeStr(v.name);
    optionParent.encode(w, v.parent);
  },
  decode(r) {
    return {
      name: r.readStr(),
      parent: optionParent.decode(r),
    };
  },
};

/** A record that holds an expression, which holds the record again. */
export interface Group {
  label: string;
  inner: Expr | null;
}

export const GroupCodec: Codec<Group> = {
  encode(w, v) {
    w.writeStr(v.label);
    optionExpr.encode(w, v.inner);
  },
  decode(r) {
    return {
      label: r.readStr(),
      inner: optionExpr.decode(r),
    };
  },
};

/** A singly linked list: each node holds the rest of the list. */
export interface ListNode {
  value: number;
  /** The rest of the list; `None` at the end. */
  next: ListNode | null;
}

export const ListNodeCodec: Codec<ListNode> = {
  encode(w, v) {
    w.writeI32(v.value);
    optionListNode.encode(w, v.next);
  },
  decode(r) {
    return {
      value: r.readI32(),
      next: optionListNode.decode(r),
    };
  },
};

/** Holds a `Child` that holds a `Parent`. */
export interface Parent {
  name: string;
  child: Child | null;
}

export const ParentCodec: Codec<Parent> = {
  encode(w, v) {
    w.writeStr(v.name);
    optionChild.encode(w, v.child);
  },
  decode(r) {
    return {
      name: r.readStr(),
      child: optionChild.decode(r),
    };
  },
};

/** A tree: the children are in an array, which needs no indirection. */
export interface Tree {
  label: string;
  children: Tree[];
}

export const TreeCodec: Codec<Tree> = {
  encode(w, v) {
    w.writeStr(v.label);
    vecTree.encode(w, v.children);
  },
  decode(r) {
    return {
      label: r.readStr(),
      children: vecTree.decode(r),
    };
  },
};

/** An expression that holds a group, which holds an expression. */
export type Expr =
  | { kind: "num"; value: number }
  | { kind: "grouped"; value: Group };

export const ExprCodec: Codec<Expr> = {
  encode(w, v) {
    switch (v.kind) {
      case "num":
        w.writeU16(0);
        w.writeF64(v.value);
        break;
      case "grouped":
        w.writeU16(1);
        GroupCodec.encode(w, v.value);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return {
          kind: "num",
          value: r.readF64(),
        };
      case 1:
        return {
          kind: "grouped",
          value: GroupCodec.decode(r),
        };
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "Expr" });
    }
  },
};

/** A path whose steps hold the rest of it. */
export type Path =
  | { kind: "end" }
  | { kind: "step"; label: string; rest: Path };

export const PathCodec: Codec<Path> = {
  encode(w, v) {
    switch (v.kind) {
      case "end":
        w.writeU16(0);
        break;
      case "step":
        w.writeU16(1);
        w.writeStr(v.label);
        PathCodec.encode(w, v.rest);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return { kind: "end" };
      case 1:
        return {
          kind: "step",
          label: r.readStr(),
          rest: PathCodec.decode(r),
        };
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "Path" });
    }
  },
};

const optionParent = codecs.option(ParentCodec);
const optionExpr = codecs.option(ExprCodec);
const optionListNode = codecs.option(ListNodeCodec);
const optionChild = codecs.option(ChildCodec);
const vecTree = codecs.vec(TreeCodec);
