// Generated by undra-bindgen from the Undra schema of `golden-recursive` (schema hash 0x5b78096d0b449e75). Do not edit.

package golden.recursive

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0x5b78096d0b449e75uL
    const val NAMESPACE: String = "golden_recursive"

    object Objects {
        object Outline {
            const val TYPE_ID: UInt = 0x1085e05du
            const val NEW: UInt = 0xa0dce515u
            const val PUSH_FRONT: UInt = 0x380cf885u
            const val REPLACE_TREE: UInt = 0xd89e5f90u
            const val PARSE: UInt = 0xc8493140u
        }
    }

    object Functions {
        const val EVALUATE: UInt = 0x0f9c3776u
        const val REVERSE: UInt = 0xc4340489u
    }

    object Ports {}

    object Queries {}
}
