// Generated by undra-bindgen from the Undra schema of `golden-recursive` (schema hash 0xfbaf2349b362d004). Do not edit.

package golden.recursive

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraStore
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** A store whose signals are recursive types. */
class Outline private constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _head: MutableStateFlow<ListNode> = signal(ListNode(value = 0, next = null))
    val head: StateFlow<ListNode> = _head.asStateFlow()
    private val _maybeHead: MutableStateFlow<ListNode?> = signal(null)
    val maybeHead: StateFlow<ListNode?> = _maybeHead.asStateFlow()
    private val _tree: MutableStateFlow<Tree> = signal(Tree(label = "", children = emptyList()))
    val tree: StateFlow<Tree> = _tree.asStateFlow()
    private val _family: MutableStateFlow<Parent> = signal(Parent(name = "", child = null))
    val family: StateFlow<Parent> = _family.asStateFlow()
    private val _expr: MutableStateFlow<Expr> = signal(Expr.Num(value = 0.0))
    val expr: StateFlow<Expr> = _expr.asStateFlow()
    private val _path: MutableStateFlow<Path> = signal(Path.End)
    val path: StateFlow<Path> = _path.asStateFlow()
    private val _lastError: MutableStateFlow<ParseError?> = signal(null)
    val lastError: StateFlow<ParseError?> = _lastError.asStateFlow()

    init {
        observeAll()
    }

    /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
    constructor(ctx: UndraCore = UndraCore.shared) : this(
        ctx,
        ctx.constructObject(UndraIds.Objects.Outline.TYPE_ID, UndraIds.Objects.Outline.NEW, ByteArray(0)),
    )

    /**
     * Returns `list` with a new first node.
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     */
    fun pushFront(list: ListNode, value: Int): ListNode {
        val w = UndraWriter()
        ListNode.encode(w, list)
        w.writeI32(value)
        try {
            val body = this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Outline.PUSH_FRONT),
                UndraIds.Objects.Outline.PUSH_FRONT,
                w.toByteArray(),
            )
            return ListNode.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    /**
     * Shows `tree`.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun replaceTree(tree: Tree) {
        try {
            val w = UndraWriter()
            Tree.encode(w, tree)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Outline.REPLACE_TREE),
                UndraIds.Objects.Outline.REPLACE_TREE,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "Outline.replaceTree")
        }
    }

    /**
     * Parses `text`.
     * @throws ParseError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun parse(text: String): Expr {
        val w = UndraWriter()
        w.writeStr(text)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Outline.PARSE),
                UndraIds.Objects.Outline.PARSE,
                w.toByteArray(),
            )
            return Expr.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, ParseError)
        }
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        try {
            when (signalId) {
                0u -> {
                    if (op == ChangeOp.FULL) {
                        val value = ListNode.decode(reader)
                        reader.finish()
                        _head.value = value
                    }
                }
                1u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionListNode.decode(reader)
                        reader.finish()
                        _maybeHead.value = value
                    }
                }
                2u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Tree.decode(reader)
                        reader.finish()
                        _tree.value = value
                    }
                }
                3u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Parent.decode(reader)
                        reader.finish()
                        _family.value = value
                    }
                }
                4u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Expr.decode(reader)
                        reader.finish()
                        _expr.value = value
                    }
                }
                5u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Path.decode(reader)
                        reader.finish()
                        _path.value = value
                    }
                }
                6u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionParseError.decode(reader)
                        reader.finish()
                        _lastError.value = value
                    }
                }
                else -> Unit
            }
        } catch (e: Exception) {
            core.report(e, "Outline.apply(signal: $signalId)")
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraCore.shared): Outline {
            val handle = ctx.constructObject(UndraIds.Objects.Outline.TYPE_ID, UndraIds.Objects.Outline.NEW, ByteArray(0))
            return Outline(ctx, handle)
        }
    }
}

private val codecOptionListNode = Codecs.option(ListNode)
private val codecOptionParseError = Codecs.option(ParseError)
