// Generated by undra-bindgen from the Undra schema of `golden-stores` (schema hash 0xb38be47d1ea134a1). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.stores

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0xb38be47d1ea134a1uL
    const val NAMESPACE: String = "golden_stores"

    object Objects {
        object Clock {
            const val TYPE_ID: UInt = 0xbb5f80fdu
            const val NEW: UInt = 0x9dfc59b5u
        }
        object Todos {
            const val TYPE_ID: UInt = 0xf5e31faau
            const val NEW: UInt = 0x35935deau
            const val OPEN: UInt = 0x0d940cccu
            const val SET_FILTER: UInt = 0x07781993u
            const val ADD: UInt = 0xd13d7ad7u
            const val REMAINING_AFTER: UInt = 0x63b9a759u
            const val CHANGES: UInt = 0xe7ac349du
        }
    }

    object Functions {}

    object Ports {}

    object Queries {}
}
