// Generated by undra-bindgen from the Undra schema of `golden-enums` (schema hash 0x2533f60443b3d23b). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
export const UndraIds = {
  schemaHash: 0x2533f60443b3d23bn,
  namespace: "golden_enums",
  Objects: {
  },
  Functions: {
  },
  Ports: {
  },
  Queries: {
  },
} as const;
