// swift-tools-version: 6.0
// Generated by `keel bindgen`: do not edit, it is rewritten with the bindings.
import PackageDescription

let package = Package(
    name: "GoldenStores",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [.library(name: "GoldenStores", targets: ["GoldenStores"])],
    dependencies: [.package(url: "https://github.com/shreypdev/keel-swift", from: "0.1.0")],
    targets: [
        .target(
            name: "GoldenStores",
            dependencies: [.product(name: "KeelRuntime", package: "keel-swift")],
            path: "Sources/GoldenStores"
        ),
    ],
    swiftLanguageModes: [.v6]
)
