// Generated by undra-bindgen from the Undra schema of `golden-ports` (schema hash 0xde22690132b0e949). Do not edit.

package golden.ports

import dev.undra.runtime.UndraException
import dev.undra.runtime.UndraReplyException
import dev.undra.runtime.wire.Payloads.ReplyStatus
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import dev.undra.runtime.wire.decodeAll

sealed class FsError(message: String) : UndraException(message) {
    data object NotFound : FsError("not found")
    data class Io(val value: String) : FsError("io: ${value}")

    companion object : UndraCodec<FsError> {
        override fun encode(w: UndraWriter, v: FsError) {
            when (v) {
                NotFound -> w.writeU16(0u)
                is Io -> {
                    w.writeU16(1u)
                    w.writeStr(v.value)
                }
            }
        }

        override fun decode(r: UndraReader): FsError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> NotFound
                1 -> Io(value = r.readStr())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "FsError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: UndraReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}

sealed class HttpError(message: String) : UndraException(message) {
    data object Timeout : HttpError("timed out")
    data class Network(val value: String) : HttpError("${value}")

    companion object : UndraCodec<HttpError> {
        override fun encode(w: UndraWriter, v: HttpError) {
            when (v) {
                Timeout -> w.writeU16(0u)
                is Network -> {
                    w.writeU16(1u)
                    w.writeStr(v.value)
                }
            }
        }

        override fun decode(r: UndraReader): HttpError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Timeout
                1 -> Network(value = r.readStr())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "HttpError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: UndraReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}
