// Generated by undra-bindgen from the Undra schema of `golden-ports` (schema hash 0xde22690132b0e949). Do not edit.

package golden.ports

import dev.undra.runtime.PortImpl
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraPort
import dev.undra.runtime.UndraPortException
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.encodeToByteArray

/** Wall-clock and monotonic time. */
interface Clock : UndraPort {
    /** Milliseconds since the epoch. */
    fun nowMs(): Long
    fun monotonicNs(): ULong
    /** Logs a line. */
    fun log(level: UByte, target: String, message: String)
}

/** Adapts an implementation of `Clock` to `UndraCore.registerPort(UndraIds.Ports.Clock.PORT_ID, ..)`. */
fun clockPortImpl(impl: Clock): PortImpl {
    val methods = mutableMapOf<UInt, suspend (ByteArray) -> ByteArray>()
    methods[UndraIds.Ports.Clock.NOW_MS] = {
        val result = impl.nowMs()
        Codecs.i64.encodeToByteArray(result)
    }
    methods[UndraIds.Ports.Clock.MONOTONIC_NS] = {
        val result = impl.monotonicNs()
        Codecs.u64.encodeToByteArray(result)
    }
    methods[UndraIds.Ports.Clock.LOG] = { args ->
        val r = UndraReader(args)
        val level = r.readU8()
        val target = r.readStr()
        val message = r.readStr()
        r.finish()
        impl.log(level, target, message)
        ByteArray(0)
    }
    return PortImpl(sync = true, methods = methods)
}

/**
 * Connectivity changes, sent by the platform.
 * Sends the events of this port from the host to the core.
 */
class ConnectivityEvents(private val core: UndraCore = UndraCore.shared) {
    /** The network changed. */
    fun changed(online: Boolean, kind: NetKind) {
        val w = UndraWriter()
        w.writeBool(online)
        NetKind.encode(w, kind)
        this.core.event(
            UndraIds.Ports.Connectivity.PORT_ID,
            UndraIds.Ports.Connectivity.CHANGED,
            w.toByteArray(),
        )
    }

    fun reset() {
        this.core.event(
            UndraIds.Ports.Connectivity.PORT_ID,
            UndraIds.Ports.Connectivity.RESET,
            ByteArray(0),
        )
    }
}

/** Performs HTTP requests. */
interface Http : UndraPort {
    /**
     * Sends a request.
     * @throws HttpError
     */
    suspend fun request(req: HttpRequest): HttpResponse
}

/** Adapts an implementation of `Http` to `UndraCore.registerPort(UndraIds.Ports.Http.PORT_ID, ..)`. */
fun httpPortImpl(impl: Http): PortImpl {
    val methods = mutableMapOf<UInt, suspend (ByteArray) -> ByteArray>()
    methods[UndraIds.Ports.Http.REQUEST] = { args ->
        val r = UndraReader(args)
        val req = HttpRequest.decode(r)
        r.finish()
        try {
            val result = impl.request(req)
            HttpResponse.encodeToByteArray(result)
        } catch (e: HttpError) {
            throw UndraPortException(HttpError.encodeToByteArray(e))
        }
    }
    return PortImpl(sync = false, methods = methods)
}

/** A key-value store. */
interface Kv : UndraPort {
    suspend fun get(key: String): ByteArray?
    suspend fun set(key: String, value: ByteArray)
    suspend fun list(prefix: String): List<String>
    /**
     * A synchronous method on an async port.
     * @throws FsError
     */
    fun flush()
}

/** Adapts an implementation of `Kv` to `UndraCore.registerPort(UndraIds.Ports.Kv.PORT_ID, ..)`. */
fun kvPortImpl(impl: Kv): PortImpl {
    val methods = mutableMapOf<UInt, suspend (ByteArray) -> ByteArray>()
    methods[UndraIds.Ports.Kv.GET] = { args ->
        val r = UndraReader(args)
        val key = r.readStr()
        r.finish()
        val result = impl.get(key)
        codecOptionBytes.encodeToByteArray(result)
    }
    methods[UndraIds.Ports.Kv.SET] = { args ->
        val r = UndraReader(args)
        val key = r.readStr()
        val value = r.readBytes()
        r.finish()
        impl.set(key, value)
        ByteArray(0)
    }
    methods[UndraIds.Ports.Kv.LIST] = { args ->
        val r = UndraReader(args)
        val prefix = r.readStr()
        r.finish()
        val result = impl.list(prefix)
        codecVecString.encodeToByteArray(result)
    }
    methods[UndraIds.Ports.Kv.FLUSH] = {
        try {
            impl.flush()
            ByteArray(0)
        } catch (e: FsError) {
            throw UndraPortException(FsError.encodeToByteArray(e))
        }
    }
    return PortImpl(sync = false, methods = methods)
}

private val codecOptionBytes = Codecs.option(Codecs.bytes)
private val codecVecString = Codecs.vec(Codecs.string)
