# Generated by undra-bindgen: R8 rules of the Undra core `golden_errors`. Do not edit.
# Its JNI_OnLoad registers the natives of this class by name (ADR-044): keep both.
-keep class golden.errors.UndraCoreNative {
    native <methods>;
}
