// Generated by keel-bindgen from the Keel schema of `golden-errors` (schema hash 0x8005bee6ac51e549). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash to pass to `KeelCore.load` as `expectedSchemaHash`.
 */
export const KeelIds = {
  schemaHash: 0x8005bee6ac51e549n,
  Objects: {
  },
  Functions: {
  },
  Ports: {
  },
  Queries: {
  },
} as const;
