// Generated by keel-bindgen from the Keel schema of `golden-stores` (schema hash 0x1154cf24573d4e30). Do not edit.

import {
  type Codec,
  KeelError,
  KeelReplyError,
  ReplyStatus,
  WireError,
  decodeValue,
} from "@keel/runtime";

export type TodoErrorKind = "emptyTitle" | "storage";

export abstract class TodoError extends KeelError {
  declare readonly kind: TodoErrorKind;

  /** The typed error a failed call carries; any other failure is returned unchanged. */
  static fromReply(error: unknown): unknown {
    if (error instanceof KeelReplyError && error.status === ReplyStatus.Error) {
      return decodeValue(TodoErrorCodec, error.body);
    }
    return error;
  }
}

export namespace TodoError {
  export class EmptyTitle extends TodoError {
    declare readonly kind: "emptyTitle";

    constructor() {
      super("emptyTitle", "title cannot be empty");
    }
  }

  export class Storage extends TodoError {
    declare readonly kind: "storage";

    constructor() {
      super("storage", "storage failure");
    }
  }
}

export const TodoErrorCodec: Codec<TodoError> = {
  encode(w, v) {
    if (v instanceof TodoError.EmptyTitle) {
      w.writeU16(0);
    } else if (v instanceof TodoError.Storage) {
      w.writeU16(1);
    } else {
      throw new TypeError(`unknown TodoError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new TodoError.EmptyTitle();
      case 1:
        return new TodoError.Storage();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "TodoError" });
    }
  },
};
