// Generated by undra-bindgen from the Undra schema of `golden-generic-functions` (schema hash 0x032c4563a078af57). Do not edit.

import {
  CallTarget,
  type Codec,
  UndraCallError,
  UndraCore,
  UndraObject,
  UndraWriter,
  adopt,
  codecs,
  decodeValue,
} from "@undra/runtime";
import { UndraGoldenGenericFunctions } from "./core.js";
import { LoadErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import { type Note, NoteCodec, type Todo, TodoCodec } from "./types.js";

/** A shelf of rows. */
export class Library extends UndraObject {
  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraGoldenGenericFunctions.core): Promise<Library> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Library.typeId,
        UndraIds.Objects.Library.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    return adopt(core, handle, Library);
  }

  /**
   * The pinned rows of a type.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  pinned(type: "Todo"): Promise<Todo[]>;
  pinned(type: "Note"): Promise<Note[]>;
  pinned(type: "Todo" | "Note"): Promise<unknown> {
    switch (type) {
      case "Todo":
        return this.pinnedTodo();
      case "Note":
        return this.pinnedNote();
      default:
        return Promise.reject(new UndraCallError.Refused(`pinned is not declared for ${String(type)}`));
    }
  }

  private async pinnedTodo(): Promise<Todo[]> {
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Library.pinnedTodo,
        new Uint8Array(0),
      );
      return decodeValue(vecTodo, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  private async pinnedNote(): Promise<Note[]> {
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Library.pinnedNote,
        new Uint8Array(0),
      );
      return decodeValue(vecNote, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /**
   * Remembers a row and answers how many there are.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  remember(type: "Todo", row: Todo, signal?: AbortSignal): Promise<number>;
  remember(type: "Note", row: Note, signal?: AbortSignal): Promise<number>;
  remember(type: "Todo" | "Note", row: Todo | Note, signal?: AbortSignal): Promise<number> {
    switch (type) {
      case "Todo":
        return this.rememberTodo(row as Todo, signal);
      case "Note":
        return this.rememberNote(row as Note, signal);
      default:
        return Promise.reject(new UndraCallError.Refused(`remember is not declared for ${String(type)}`));
    }
  }

  private async rememberTodo(row: Todo, signal?: AbortSignal): Promise<number> {
    const w = new UndraWriter();
    TodoCodec.encode(w, row);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Library.rememberTodo,
        w.finish(),
        signal,
      );
      return decodeValue(codecs.u32, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  private async rememberNote(row: Note, signal?: AbortSignal): Promise<number> {
    const w = new UndraWriter();
    NoteCodec.encode(w, row);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Library.rememberNote,
        w.finish(),
        signal,
      );
      return decodeValue(codecs.u32, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /**
   * How many rows are pinned.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  async count(): Promise<number> {
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Library.count,
        new Uint8Array(0),
      );
      return decodeValue(codecs.u32, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }
}

/**
 * How many rows there are.
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 */
export async function countRows(
  core: UndraCore = UndraGoldenGenericFunctions.core,
): Promise<number> {
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.countRows,
      new Uint8Array(0),
    );
    return decodeValue(codecs.u32, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

/**
 * An empty row with a fresh id, ready to edit.
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 */
export function draft(type: "Note", core?: UndraCore): Promise<Note>;
export function draft(type: "Todo", core?: UndraCore): Promise<Todo>;
export function draft(
  type: "Note" | "Todo",
  core: UndraCore = UndraGoldenGenericFunctions.core,
): Promise<unknown> {
  switch (type) {
    case "Note":
      return draftNote(core);
    case "Todo":
      return draftTodo(core);
    default:
      return Promise.reject(new UndraCallError.Refused(`draft is not declared for ${String(type)}`));
  }
}

async function draftNote(core: UndraCore): Promise<Note> {
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.draftNote,
      new Uint8Array(0),
    );
    return decodeValue(NoteCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

async function draftTodo(core: UndraCore): Promise<Todo> {
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.draftTodo,
      new Uint8Array(0),
    );
    return decodeValue(TodoCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

/**
 * Drops a row from the cache.
 * A failure is logged and passed to `onError`; the returned promise never rejects.
 */
export function forget(type: "Note", row: Note, core?: UndraCore): Promise<void>;
export function forget(type: "Todo", row: Todo, core?: UndraCore): Promise<void>;
export function forget(
  type: "Note" | "Todo",
  row: Note | Todo,
  core: UndraCore = UndraGoldenGenericFunctions.core,
): Promise<void> {
  switch (type) {
    case "Note":
      return forgetNote(row as Note, core);
    case "Todo":
      return forgetTodo(row as Todo, core);
    default:
      core.report(new UndraCallError.Refused(`forget is not declared for ${String(type)}`), "forget");
      return Promise.resolve();
  }
}

async function forgetNote(row: Note, core: UndraCore): Promise<void> {
  try {
    const w = new UndraWriter();
    NoteCodec.encode(w, row);
    await core.call({ target: CallTarget.FreeFunction }, UndraIds.Functions.forgetNote, w.finish());
  } catch (error) {
    core.report(error, "forget");
  }
}

async function forgetTodo(row: Todo, core: UndraCore): Promise<void> {
  try {
    const w = new UndraWriter();
    TodoCodec.encode(w, row);
    await core.call({ target: CallTarget.FreeFunction }, UndraIds.Functions.forgetTodo, w.finish());
  } catch (error) {
    core.report(error, "forget");
  }
}

/**
 * Loads a row from the server.
 * @throws {LoadError}
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
 */
export function load(
  type: "Note",
  id: number,
  core?: UndraCore,
  signal?: AbortSignal,
): Promise<Note>;
export function load(
  type: "Todo",
  id: number,
  core?: UndraCore,
  signal?: AbortSignal,
): Promise<Todo>;
export function load(
  type: "Note" | "Todo",
  id: number,
  core: UndraCore = UndraGoldenGenericFunctions.core,
  signal?: AbortSignal,
): Promise<unknown> {
  switch (type) {
    case "Note":
      return loadNote(id, core, signal);
    case "Todo":
      return loadTodo(id, core, signal);
    default:
      return Promise.reject(new UndraCallError.Refused(`load is not declared for ${String(type)}`));
  }
}

async function loadNote(id: number, core: UndraCore, signal?: AbortSignal): Promise<Note> {
  const w = new UndraWriter();
  w.writeU32(id);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.loadNote,
      w.finish(),
      signal,
    );
    return decodeValue(NoteCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error, LoadErrorCodec);
  }
}

async function loadTodo(id: number, core: UndraCore, signal?: AbortSignal): Promise<Todo> {
  const w = new UndraWriter();
  w.writeU32(id);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.loadTodo,
      w.finish(),
      signal,
    );
    return decodeValue(TodoCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error, LoadErrorCodec);
  }
}

/**
 * Makes a row of the given kind: a parameter called `type` does not collide with the type token.
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 */
export function make(type_: "Note", type: string, core?: UndraCore): Promise<Note>;
export function make(type_: "Todo", type: string, core?: UndraCore): Promise<Todo>;
export function make(
  type_: "Note" | "Todo",
  type: string,
  core: UndraCore = UndraGoldenGenericFunctions.core,
): Promise<unknown> {
  switch (type_) {
    case "Note":
      return makeNote(type, core);
    case "Todo":
      return makeTodo(type, core);
    default:
      return Promise.reject(new UndraCallError.Refused(`make is not declared for ${String(type_)}`));
  }
}

async function makeNote(type: string, core: UndraCore): Promise<Note> {
  const w = new UndraWriter();
  w.writeStr(type);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.makeNote,
      w.finish(),
    );
    return decodeValue(NoteCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

async function makeTodo(type: string, core: UndraCore): Promise<Todo> {
  const w = new UndraWriter();
  w.writeStr(type);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.makeTodo,
      w.finish(),
    );
    return decodeValue(TodoCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

/**
 * The row that changed last, if there is one.
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 */
export function newest(type: "Note", rows: Note[], core?: UndraCore): Promise<Note | null>;
export function newest(type: "Todo", rows: Todo[], core?: UndraCore): Promise<Todo | null>;
export function newest(
  type: "Note" | "Todo",
  rows: Note[] | Todo[],
  core: UndraCore = UndraGoldenGenericFunctions.core,
): Promise<unknown> {
  switch (type) {
    case "Note":
      return newestNote(rows as Note[], core);
    case "Todo":
      return newestTodo(rows as Todo[], core);
    default:
      return Promise.reject(new UndraCallError.Refused(`newest is not declared for ${String(type)}`));
  }
}

async function newestNote(rows: Note[], core: UndraCore): Promise<Note | null> {
  const w = new UndraWriter();
  vecNote.encode(w, rows);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.newestNote,
      w.finish(),
    );
    return decodeValue(optionNote, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

async function newestTodo(rows: Todo[], core: UndraCore): Promise<Todo | null> {
  const w = new UndraWriter();
  vecTodo.encode(w, rows);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.newestTodo,
      w.finish(),
    );
    return decodeValue(optionTodo, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

/**
 * A stream of the first rows.
 * Iterating throws UndraCallError; leaving the loop early ends the stream quietly.
 */
export function rows(type: "Note", count: number, core?: UndraCore): AsyncIterable<Note>;
export function rows(type: "Todo", count: number, core?: UndraCore): AsyncIterable<Todo>;
export function rows(
  type: "Note" | "Todo",
  count: number,
  core: UndraCore = UndraGoldenGenericFunctions.core,
): AsyncIterable<unknown> {
  switch (type) {
    case "Note":
      return rowsNote(count, core);
    case "Todo":
      return rowsTodo(count, core);
    default:
      throw new UndraCallError.Refused(`rows is not declared for ${String(type)}`);
  }
}

function rowsNote(count: number, core: UndraCore): AsyncIterable<Note> {
  const w = new UndraWriter();
  w.writeU32(count);
  const source = core.stream(
    { target: CallTarget.FreeFunction },
    UndraIds.Functions.rowsNote,
    w.finish(),
  );
  return decodeStream(source, NoteCodec, (error) => UndraCallError.mappedStream(error));
}

function rowsTodo(count: number, core: UndraCore): AsyncIterable<Todo> {
  const w = new UndraWriter();
  w.writeU32(count);
  const source = core.stream(
    { target: CallTarget.FreeFunction },
    UndraIds.Functions.rowsTodo,
    w.finish(),
  );
  return decodeStream(source, TodoCodec, (error) => UndraCallError.mappedStream(error));
}

/**
 * Writes a row back.
 * @throws {LoadError}
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
 */
export function save(
  type: "Note",
  row: Note,
  core?: UndraCore,
  signal?: AbortSignal,
): Promise<void>;
export function save(
  type: "Todo",
  row: Todo,
  core?: UndraCore,
  signal?: AbortSignal,
): Promise<void>;
export function save(
  type: "Note" | "Todo",
  row: Note | Todo,
  core: UndraCore = UndraGoldenGenericFunctions.core,
  signal?: AbortSignal,
): Promise<void> {
  switch (type) {
    case "Note":
      return saveNote(row as Note, core, signal);
    case "Todo":
      return saveTodo(row as Todo, core, signal);
    default:
      return Promise.reject(new UndraCallError.Refused(`save is not declared for ${String(type)}`));
  }
}

async function saveNote(row: Note, core: UndraCore, signal?: AbortSignal): Promise<void> {
  const w = new UndraWriter();
  NoteCodec.encode(w, row);
  try {
    await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.saveNote,
      w.finish(),
      signal,
    );
  } catch (error) {
    throw UndraCallError.mapped(error, LoadErrorCodec);
  }
}

async function saveTodo(row: Todo, core: UndraCore, signal?: AbortSignal): Promise<void> {
  const w = new UndraWriter();
  TodoCodec.encode(w, row);
  try {
    await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Functions.saveTodo,
      w.finish(),
      signal,
    );
  } catch (error) {
    throw UndraCallError.mapped(error, LoadErrorCodec);
  }
}

/** Decodes every item of a core stream; a failure of the stream or of an item goes through `mapError`. */
async function* decodeStream<T>(
  source: AsyncIterable<Uint8Array>,
  codec: Codec<T>,
  mapError: (error: unknown) => unknown,
): AsyncGenerator<T, void, undefined> {
  try {
    for await (const body of source) yield decodeValue(codec, body);
  } catch (error) {
    throw mapError(error);
  }
}

const vecTodo = codecs.vec(TodoCodec);
const vecNote = codecs.vec(NoteCodec);
const optionNote = codecs.option(NoteCodec);
const optionTodo = codecs.option(TodoCodec);
