// Generated by undra-bindgen from the Undra schema of `golden-generic-functions` (schema hash 0x032c4563a078af57). Do not edit.

import {
  CallTarget,
  ChangeOp,
  Signal,
  UndraCallError,
  UndraCore,
  UndraStore,
  UndraWriter,
  adopt,
  codecs,
  decodeValue,
} from "@undra/runtime";
import { UndraGoldenGenericFunctions } from "./core.js";
import { UndraIds } from "./ids.js";
import { type Note, NoteCodec, type Todo, TodoCodec } from "./types.js";

/** A store with generic methods. */
export class Shelf extends UndraStore {
  readonly size: Signal<number> = new Signal<number>(0);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.size];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraGoldenGenericFunctions.core): Promise<Shelf> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Shelf.typeId,
        UndraIds.Objects.Shelf.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = adopt(core, handle, Shelf);
    await store._observeAll();
    return store;
  }

  /**
   * Sorts rows.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  tidy(type: "Todo", rows: Todo[]): Promise<void>;
  tidy(type: "Note", rows: Note[]): Promise<void>;
  tidy(type: "Todo" | "Note", rows: Todo[] | Note[]): Promise<void> {
    switch (type) {
      case "Todo":
        return this.tidyTodo(rows as Todo[]);
      case "Note":
        return this.tidyNote(rows as Note[]);
      default:
        this.core.report(new UndraCallError.Refused(`tidy is not declared for ${String(type)}`), "tidy");
        return Promise.resolve();
    }
  }

  private async tidyTodo(rows: Todo[]): Promise<void> {
    try {
      const w = new UndraWriter();
      vecTodo.encode(w, rows);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Shelf.tidyTodo,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "Shelf.tidy");
    }
  }

  private async tidyNote(rows: Note[]): Promise<void> {
    try {
      const w = new UndraWriter();
      vecNote.encode(w, rows);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Shelf.tidyNote,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "Shelf.tidy");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.size._set(decodeValue(codecs.u32, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `Shelf.apply(signal: ${signalId})`);
    }
  }
}

const vecTodo = codecs.vec(TodoCodec);
const vecNote = codecs.vec(NoteCodec);
