// Generated by undra-bindgen from the Undra schema of `golden-generic-functions` (schema hash 0x032c4563a078af57). Do not edit.

import { type Codec } from "@undra/runtime";

/** A note. */
export interface Note {
  id: number;
  body: string;
}

export const NoteCodec: Codec<Note> = {
  encode(w, v) {
    w.writeU32(v.id);
    w.writeStr(v.body);
  },
  decode(r) {
    return {
      id: r.readU32(),
      body: r.readStr(),
    };
  },
};

/** A todo. */
export interface Todo {
  id: number;
  title: string;
}

export const TodoCodec: Codec<Todo> = {
  encode(w, v) {
    w.writeU32(v.id);
    w.writeStr(v.title);
  },
  decode(r) {
    return {
      id: r.readU32(),
      title: r.readStr(),
    };
  },
};
