// Generated by undra-bindgen from the Undra schema of `playground-core` (schema hash 0x3b1bd1062551c158). Do not edit.

package golden.full

import dev.undra.runtime.UndraException
import dev.undra.runtime.UndraReplyException
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.Payloads.ReplyStatus
import dev.undra.runtime.wire.WireException
import dev.undra.runtime.wire.decodeAll

sealed class HttpError(message: String) : UndraException(message) {
    data object Timeout : HttpError("timed out")
    data class Status(val value: UShort) : HttpError("status ${value}")

    companion object : UndraCodec<HttpError> {
        override fun encode(w: UndraWriter, v: HttpError) {
            when (v) {
                Timeout -> w.writeU16(0u)
                is Status -> {
                    w.writeU16(1u)
                    w.writeU16(v.value)
                }
            }
        }

        override fun decode(r: UndraReader): HttpError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Timeout
                1 -> Status(value = r.readU16())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "HttpError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: UndraReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}

sealed class TodoError(message: String) : UndraException(message) {
    data object EmptyTitle : TodoError("title cannot be empty")
    data class Http(override val cause: HttpError) : TodoError(cause.message.orEmpty())
    data class NotFound(val value: String) : TodoError("todo ${value} not found")
    data class Storage(val reason: String) : TodoError("storage failure (${reason})")

    companion object : UndraCodec<TodoError> {
        override fun encode(w: UndraWriter, v: TodoError) {
            when (v) {
                EmptyTitle -> w.writeU16(0u)
                is Http -> {
                    w.writeU16(1u)
                    HttpError.encode(w, v.cause)
                }
                is NotFound -> {
                    w.writeU16(2u)
                    w.writeStr(v.value)
                }
                is Storage -> {
                    w.writeU16(3u)
                    w.writeStr(v.reason)
                }
            }
        }

        override fun decode(r: UndraReader): TodoError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> EmptyTitle
                1 -> Http(cause = HttpError.decode(r))
                2 -> NotFound(value = r.readStr())
                3 -> Storage(reason = r.readStr())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "TodoError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: UndraReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}
