// Generated by undra-bindgen from the Undra schema of `playground-core` (schema hash 0x3b1bd1062551c158). Do not edit.

package golden.full

import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraPort
import dev.undra.runtime.UndraPortException
import dev.undra.runtime.PortImpl
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.encodeToByteArray

/** Sends the events of this port from the host to the core. */
class ConnectivityEvents(private val core: UndraCore = UndraCore.shared) {
    fun changed(online: Boolean, kind: NetKind) {
        val w = UndraWriter()
        w.writeBool(online)
        NetKind.encode(w, kind)
        this.core.event(
            UndraIds.Ports.Connectivity.PORT_ID,
            UndraIds.Ports.Connectivity.CHANGED,
            w.toByteArray(),
        )
    }
}

interface Http : UndraPort {
    /** @throws HttpError */
    suspend fun request(req: HttpRequest): HttpResponse
}

/** Adapts an implementation of `Http` to `UndraCore.registerPort(UndraIds.Ports.Http.PORT_ID, ..)`. */
fun httpPortImpl(impl: Http): PortImpl {
    val methods = mutableMapOf<UInt, suspend (ByteArray) -> ByteArray>()
    methods[UndraIds.Ports.Http.REQUEST] = { args ->
        val r = UndraReader(args)
        val req = HttpRequest.decode(r)
        r.finish()
        try {
            val result = impl.request(req)
            HttpResponse.encodeToByteArray(result)
        } catch (e: HttpError) {
            throw UndraPortException(HttpError.encodeToByteArray(e))
        }
    }
    return PortImpl(sync = false, methods = methods)
}

interface Kv : UndraPort {
    suspend fun get(key: String): ByteArray?
    suspend fun set(key: String, value: ByteArray)
}

/** Adapts an implementation of `Kv` to `UndraCore.registerPort(UndraIds.Ports.Kv.PORT_ID, ..)`. */
fun kvPortImpl(impl: Kv): PortImpl {
    val methods = mutableMapOf<UInt, suspend (ByteArray) -> ByteArray>()
    methods[UndraIds.Ports.Kv.GET] = { args ->
        val r = UndraReader(args)
        val key = r.readStr()
        r.finish()
        val result = impl.get(key)
        codecOptionBytes.encodeToByteArray(result)
    }
    methods[UndraIds.Ports.Kv.SET] = { args ->
        val r = UndraReader(args)
        val key = r.readStr()
        val value = r.readBytes()
        r.finish()
        impl.set(key, value)
        ByteArray(0)
    }
    return PortImpl(sync = false, methods = methods)
}

interface WallClock : UndraPort {
    fun nowMs(): Long
    fun monotonicNs(): ULong
}

/** Adapts an implementation of `WallClock` to `UndraCore.registerPort(UndraIds.Ports.WallClock.PORT_ID, ..)`. */
fun wallClockPortImpl(impl: WallClock): PortImpl {
    val methods = mutableMapOf<UInt, suspend (ByteArray) -> ByteArray>()
    methods[UndraIds.Ports.WallClock.NOW_MS] = {
        val result = impl.nowMs()
        Codecs.i64.encodeToByteArray(result)
    }
    methods[UndraIds.Ports.WallClock.MONOTONIC_NS] = {
        val result = impl.monotonicNs()
        Codecs.u64.encodeToByteArray(result)
    }
    return PortImpl(sync = true, methods = methods)
}

private val codecOptionBytes = Codecs.option(Codecs.bytes)
