// Generated by undra-bindgen from the Undra schema of `playground-core` (schema hash 0x3b1bd1062551c158). Do not edit.

package golden.full

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraStore
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.Timestamp
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import kotlin.time.Duration
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Observes the `todos` query (cache key `todos:{page}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
class TodosQueryHandle internal constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _data: MutableStateFlow<Page?> = signal(null)
    /** The latest successful result, if any. */
    val data: StateFlow<Page?> = _data.asStateFlow()
    private val _status: MutableStateFlow<QueryStatus> = signal(QueryStatus.IDLE)
    /** Where the query is in its fetch lifecycle. */
    val status: StateFlow<QueryStatus> = _status.asStateFlow()
    private val _error: MutableStateFlow<TodoError?> = signal(null)
    /** The error of the latest failed fetch, cleared by the next success. */
    val error: StateFlow<TodoError?> = _error.asStateFlow()
    private val _fetching: MutableStateFlow<Boolean> = signal(false)
    /** Whether a fetch is in flight (also true while refetching stale data). */
    val fetching: StateFlow<Boolean> = _fetching.asStateFlow()
    private val _updatedAt: MutableStateFlow<Timestamp?> = signal(null)
    /** When `data` was last updated. */
    val updatedAt: StateFlow<Timestamp?> = _updatedAt.asStateFlow()

    /**
     * Fetches again now, even if the data is fresh.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun refetch() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodosQueryHandle.REFETCH),
                UndraIds.Objects.TodosQueryHandle.REFETCH,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "TodosQueryHandle.refetch")
        }
    }

    /**
     * Marks the cached entry stale; it refetches while observed.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun invalidate() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodosQueryHandle.INVALIDATE),
                UndraIds.Objects.TodosQueryHandle.INVALIDATE,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "TodosQueryHandle.invalidate")
        }
    }

    /**
     * Overrides how often the query polls while this handle observes it, counted from the end of a fetch.
     * The entry polls at the smallest interval among its observers; no interval clears this handle's override.
     * An interval below 1 second or above 7 days is clamped to that range.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun setPollInterval(interval: Duration?) {
        try {
            val w = UndraWriter()
            codecOptionDuration.encode(w, interval)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodosQueryHandle.SET_POLL_INTERVAL),
                UndraIds.Objects.TodosQueryHandle.SET_POLL_INTERVAL,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "TodosQueryHandle.setPollInterval")
        }
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        try {
            when (signalId) {
                0u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionPage.decode(reader)
                        reader.finish()
                        _data.value = value
                    }
                }
                1u -> {
                    if (op == ChangeOp.FULL) {
                        val value = QueryStatus.decode(reader)
                        reader.finish()
                        _status.value = value
                    }
                }
                2u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionTodoError.decode(reader)
                        reader.finish()
                        _error.value = value
                    }
                }
                3u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Codecs.bool.decode(reader)
                        reader.finish()
                        _fetching.value = value
                    }
                }
                4u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionTimestamp.decode(reader)
                        reader.finish()
                        _updatedAt.value = value
                    }
                }
                else -> Unit
            }
        } catch (e: Exception) {
            core.report(e, "TodosQueryHandle.apply(signal: $signalId)")
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(page: UInt, ctx: UndraCore = UndraPlaygroundCore.core): TodosQueryHandle {
            val w = UndraWriter()
            w.writeU32(page)
            val handle = ctx.constructObject(UndraIds.Objects.TodosQueryHandle.TYPE_ID, UndraIds.Objects.TodosQueryHandle.NEW, w.toByteArray())
            return ctx.adopt(handle, ::TodosQueryHandle)
        }
    }
}

/**
 * Runs the `add_todo` mutation.
 * @throws TodoError
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 * @throws CancellationException if the calling coroutine is cancelled.
 */
suspend fun addTodo(title: String, ctx: UndraCore = UndraPlaygroundCore.core): Todo {
    val w = UndraWriter()
    w.writeStr(title)
    try {
        val body = ctx.call(
            CallTarget.FreeFunction(UndraIds.Queries.ADD_TODO),
            UndraIds.Queries.ADD_TODO,
            w.toByteArray(),
        )
        return Todo.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e, TodoError)
    }
}

private val codecOptionDuration = Codecs.option(Codecs.duration)
private val codecOptionPage = Codecs.option(Page)
private val codecOptionTodoError = Codecs.option(TodoError)
private val codecOptionTimestamp = Codecs.option(Codecs.timestamp)
