// Generated by undra-bindgen from the Undra schema of `playground-core` (schema hash 0x3b1bd1062551c158). Do not edit.

package golden.full

import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraReplyException
import dev.undra.runtime.UndraStore
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.KeyedPatch
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import dev.undra.runtime.wire.decodeAll
import java.util.UUID
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** The todo list store. */
class TodoStore private constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _todos: MutableStateFlow<List<Todo>> = signal(emptyList())
    val todos: StateFlow<List<Todo>> = _todos.asStateFlow()
    private val _filter: MutableStateFlow<Filter> = signal(Filter.ALL)
    val filter: StateFlow<Filter> = _filter.asStateFlow()
    private val _visible: MutableStateFlow<List<Todo>> = signal(emptyList())
    /** Computed by the core; read-only. */
    val visible: StateFlow<List<Todo>> = _visible.asStateFlow()
    private val _remaining: MutableStateFlow<UInt> = signal(0u)
    /** Computed by the core; read-only. */
    val remaining: StateFlow<UInt> = _remaining.asStateFlow()
    private val _selected: MutableStateFlow<Todo?> = signal(null)
    val selected: StateFlow<Todo?> = _selected.asStateFlow()

    init {
        core.observe(handle, UInt.MAX_VALUE, true)
    }

    constructor(ctx: UndraCore = UndraCore.shared) : this(
        ctx,
        ctx.construct(UndraIds.Objects.TodoStore.TYPE_ID, UndraIds.Objects.TodoStore.NEW, ByteArray(0)),
    )

    fun setFilter(f: Filter) {
        val w = UndraWriter()
        Filter.encode(w, f)
        this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodoStore.SET_FILTER),
            UndraIds.Objects.TodoStore.SET_FILTER,
            w.toByteArray(),
        )
    }

    /** @throws TodoError */
    suspend fun add(title: String): Todo {
        val w = UndraWriter()
        w.writeStr(title)
        val body = try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodoStore.ADD),
                UndraIds.Objects.TodoStore.ADD,
                w.toByteArray(),
            )
        } catch (e: UndraReplyException) {
            throw TodoError.fromReply(e)
        }
        return Todo.decodeAll(body)
    }

    fun toggle(id: UUID) {
        val w = UndraWriter()
        Codecs.uuid.encode(w, id)
        this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodoStore.TOGGLE),
            UndraIds.Objects.TodoStore.TOGGLE,
            w.toByteArray(),
        )
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        when (signalId) {
            0u -> {
                if (op == ChangeOp.FULL) {
                    _todos.value = codecVecTodo.decode(reader)
                    reader.finish()
                } else if (op == ChangeOp.PATCH) {
                    val ops = KeyedPatch.decodePatch(reader, Todo)
                    reader.finish()
                    try {
                        _todos.value = KeyedPatch.applyPatch(_todos.value, ops)
                    } catch (e: WireException.PatchOutOfBounds) {
                        resync(0u)
                    }
                }
            }
            1u -> {
                if (op == ChangeOp.FULL) {
                    _filter.value = Filter.decode(reader)
                    reader.finish()
                }
            }
            2u -> {
                if (op == ChangeOp.FULL) {
                    _visible.value = codecVecTodo.decode(reader)
                    reader.finish()
                } else if (op == ChangeOp.PATCH) {
                    val ops = KeyedPatch.decodePatch(reader, Todo)
                    reader.finish()
                    try {
                        _visible.value = KeyedPatch.applyPatch(_visible.value, ops)
                    } catch (e: WireException.PatchOutOfBounds) {
                        resync(2u)
                    }
                }
            }
            3u -> {
                if (op == ChangeOp.FULL) {
                    _remaining.value = Codecs.u32.decode(reader)
                    reader.finish()
                }
            }
            4u -> {
                if (op == ChangeOp.FULL) {
                    _selected.value = codecOptionTodo.decode(reader)
                    reader.finish()
                }
            }
            else -> Unit
        }
    }

    /** Re-observes a signal whose mirror diverged from the core, to receive a full value. */
    private fun resync(signalId: UInt) {
        core.observe(handle, signalId, false)
        core.observe(handle, signalId, true)
    }

    companion object {
        fun create(ctx: UndraCore = UndraCore.shared): TodoStore {
            val handle = ctx.construct(UndraIds.Objects.TodoStore.TYPE_ID, UndraIds.Objects.TodoStore.NEW, ByteArray(0))
            return TodoStore(ctx, handle)
        }

        /** @throws TodoError */
        suspend fun open(path: String, ctx: UndraCore = UndraCore.shared): TodoStore {
            val w = UndraWriter()
            w.writeStr(path)
            val handle = try {
                Codecs.handle.decodeAll(ctx.call(CallTarget.Constructor(UndraIds.Objects.TodoStore.TYPE_ID, UndraIds.Objects.TodoStore.OPEN), UndraIds.Objects.TodoStore.OPEN, w.toByteArray()))
            } catch (e: UndraReplyException) {
                throw TodoError.fromReply(e)
            }
            return TodoStore(ctx, handle)
        }
    }
}

private val codecVecTodo = Codecs.vec(Todo)
private val codecOptionTodo = Codecs.option(Todo)
