// Generated by undra-bindgen from the Undra schema of `golden-callbacks` (schema hash 0xa6dee0cf4d9b6213). Do not edit.

package golden.callbacks

import dev.undra.runtime.UndraException
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

sealed class AuthError(message: String) : UndraException(message) {
    data object Expired : AuthError("the token expired")

    companion object : UndraCodec<AuthError> {
        override fun encode(w: UndraWriter, v: AuthError) {
            when (v) {
                Expired -> w.writeU16(0u)
            }
        }

        override fun decode(r: UndraReader): AuthError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Expired
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "AuthError")
            }
        }
    }
}

sealed class PromptError(message: String) : UndraException(message) {
    data object Declined : PromptError("the user declined")
    data class Unavailable(val value: String) : PromptError("${value}")

    companion object : UndraCodec<PromptError> {
        override fun encode(w: UndraWriter, v: PromptError) {
            when (v) {
                Declined -> w.writeU16(0u)
                is Unavailable -> {
                    w.writeU16(1u)
                    w.writeStr(v.value)
                }
            }
        }

        override fun decode(r: UndraReader): PromptError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Declined
                1 -> Unavailable(value = r.readStr())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "PromptError")
            }
        }
    }
}

sealed class UploadError(message: String) : UndraException(message) {
    data object Failed : UploadError("the upload failed")

    companion object : UndraCodec<UploadError> {
        override fun encode(w: UndraWriter, v: UploadError) {
            when (v) {
                Failed -> w.writeU16(0u)
            }
        }

        override fun decode(r: UndraReader): UploadError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Failed
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "UploadError")
            }
        }
    }
}
