// Generated by undra-bindgen from the Undra schema of `golden-callbacks` (schema hash 0xdcef0138feda9c54). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.callbacks

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0xdcef0138feda9c54uL
    const val NAMESPACE: String = "golden_callbacks"

    object Objects {
        object Uploader {
            const val TYPE_ID: UInt = 0x247ebc8bu
            const val NEW: UInt = 0x0b61967fu
            const val UPLOAD: UInt = 0x815b2b02u
            const val WATCH: UInt = 0x44514bf6u
            const val SET_PROVIDER: UInt = 0xe07bf10bu
            const val NOTIFY: UInt = 0x22c36ebau
            const val FOLLOW: UInt = 0x4e5d3d42u
            const val FOLLOW_CHECKED: UInt = 0x489acde0u
        }
        object Watch {
            const val TYPE_ID: UInt = 0xec266ec8u
            const val ID: UInt = 0x2075bd1fu
        }
    }

    object Functions {
        const val TAIL: UInt = 0x757a75cfu
        const val WITH_LISTENER: UInt = 0xf5ac9882u
    }

    object Ports {}

    object Callbacks {
        object TokenProvider {
            const val PORT_ID: UInt = 0x92be3d64u
            const val TOKEN: UInt = 0x606cf2d0u
            const val REFRESHED: UInt = 0xedd513d7u
            const val RELEASE_INSTANCE: UInt = 0xb1249b22u
            const val CANCEL_CALL: UInt = 0xca10907fu
        }
        object UploadListener {
            const val PORT_ID: UInt = 0x77a5fa4du
            const val PROGRESS: UInt = 0xd38d6519u
            const val FINISHED: UInt = 0x9849e9d8u
            const val CONFIRM_REPLACE: UInt = 0xe4077c65u
            const val RELEASE_INSTANCE: UInt = 0x1e812a11u
            const val CANCEL_CALL: UInt = 0x5f0899feu
        }
    }

    object Queries {}
}
