// Generated by undra-bindgen from the Undra schema of `golden-callbacks` (schema hash 0xa6dee0cf4d9b6213). Do not edit.

package golden.callbacks

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraObject
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll

/** Uploads files. */
class Uploader internal constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    /**
     * Uploads `file`, reporting to `listener`.
     * @throws UploadError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun upload(file: String, listener: UploadListener): UInt {
        val listenerInstance = this.core.callbacks.lend(listener)
        try {
            val w = UndraWriter()
            w.writeStr(file)
            w.writeU64(listenerInstance)
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Uploader.UPLOAD),
                UndraIds.Objects.Uploader.UPLOAD,
                w.toByteArray(),
            )
            return Codecs.u32.decodeAll(body)
        } catch (e: Exception) {
            this.core.callbacks.giveBackIfRefused(e, listenerInstance)
            throw UndraCallError.mapped(e, UploadError)
        }
    }

    /**
     * Keeps `listener` until the returned watch is closed.
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     */
    fun watch(listener: UploadListener): Watch {
        val listenerInstance = this.core.callbacks.lend(listener)
        try {
            val w = UndraWriter()
            w.writeU64(listenerInstance)
            val body = this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Uploader.WATCH),
                UndraIds.Objects.Uploader.WATCH,
                w.toByteArray(),
            )
            return this.core.adoptObject(body, ::Watch)
        } catch (e: Exception) {
            this.core.callbacks.giveBackIfRefused(e, listenerInstance)
            throw UndraCallError.mapped(e)
        }
    }

    /**
     * Uses `provider` for the tokens.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun setProvider(provider: TokenProvider) {
        val providerInstance = this.core.callbacks.lend(provider)
        try {
            val w = UndraWriter()
            w.writeU64(providerInstance)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Uploader.SET_PROVIDER),
                UndraIds.Objects.Uploader.SET_PROVIDER,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.callbacks.giveBackIfRefused(e, providerInstance)
            this.core.report(e, "Uploader.setProvider")
        }
    }

    /**
     * Tells the optional `listener` the upload is over.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun notify(listener: UploadListener?) {
        val listenerInstance = listener?.let { this.core.callbacks.lend(it) }
        try {
            val w = UndraWriter()
            codecOptionU64.encode(w, listenerInstance)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Uploader.NOTIFY),
                UndraIds.Objects.Uploader.NOTIFY,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.callbacks.giveBackIfRefused(e, listenerInstance)
            this.core.report(e, "Uploader.notify")
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(
            listener: UploadListener?,
            ctx: UndraCore = UndraGoldenCallbacks.core,
        ): Uploader {
            val listenerInstance = listener?.let { ctx.callbacks.lend(it) }
            val handle = try {
                val w = UndraWriter()
                codecOptionU64.encode(w, listenerInstance)
                ctx.construct(UndraIds.Objects.Uploader.TYPE_ID, UndraIds.Objects.Uploader.NEW, w.toByteArray())
            } catch (e: Exception) {
                ctx.callbacks.giveBackIfRefused(e, listenerInstance)
                throw UndraCallError.mapped(e)
            }
            return ctx.adopt(handle, ::Uploader)
        }
    }
}

/** A subscription. */
class Watch internal constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
    fun id(): UInt {
        try {
            val body = this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Watch.ID),
                UndraIds.Objects.Watch.ID,
                ByteArray(0),
            )
            return Codecs.u32.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }
}

/**
 * Calls `listener` once and returns how many arguments it had.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
fun withListener(listener: UploadListener, ctx: UndraCore = UndraGoldenCallbacks.core): UInt {
    val listenerInstance = ctx.callbacks.lend(listener)
    try {
        val w = UndraWriter()
        w.writeU64(listenerInstance)
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.WITH_LISTENER),
            UndraIds.Functions.WITH_LISTENER,
            w.toByteArray(),
        )
        return Codecs.u32.decodeAll(body)
    } catch (e: Exception) {
        ctx.callbacks.giveBackIfRefused(e, listenerInstance)
        throw UndraCallError.mapped(e)
    }
}

private val codecOptionU64 = Codecs.option(Codecs.u64)
