// Generated by undra-bindgen from the Undra schema of `golden-infinite` (schema hash 0x1b2522922dd3b430). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.infinite

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0x1b2522922dd3b430uL
    const val NAMESPACE: String = "golden_infinite"

    object Objects {
        object FeedQueryHandle {
            const val TYPE_ID: UInt = 0x015a66a3u
            const val NEW: UInt = 0x015a66a3u
            const val FETCH_NEXT_PAGE: UInt = 0x84920501u
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
            const val SET_POLL_INTERVAL: UInt = 0xe327e53bu
        }
        object ProfileQueryHandle {
            const val TYPE_ID: UInt = 0x9cc44f88u
            const val NEW: UInt = 0x9cc44f88u
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
            const val SET_POLL_INTERVAL: UInt = 0xe327e53bu
        }
        object SearchQueryHandle {
            const val TYPE_ID: UInt = 0x1082eab7u
            const val NEW: UInt = 0x1082eab7u
            const val FETCH_NEXT_PAGE: UInt = 0x84920501u
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
            const val SET_POLL_INTERVAL: UInt = 0xe327e53bu
        }
    }

    object Functions {}

    object Ports {}

    object Queries {
        const val FEED: UInt = 0x015a66a3u
        const val PROFILE: UInt = 0x9cc44f88u
        const val SEARCH: UInt = 0x1082eab7u
    }
}
