// Generated by undra-bindgen from the Undra schema of `golden-infinite` (schema hash 0x1b2522922dd3b430). Do not edit.

package golden.infinite

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

/** One search result. */
data class Hit(
    val slug: String,
    val title: String,
) : UndraRecord {
    companion object : UndraCodec<Hit> {
        override fun encode(w: UndraWriter, v: Hit) {
            w.writeStr(v.slug)
            w.writeStr(v.title)
        }

        override fun decode(r: UndraReader): Hit = Hit(slug = r.readStr(), title = r.readStr())
    }
}

/** One post of the feed. */
data class Post(
    val id: PostId,
    val author: String,
    val body: String,
) : UndraRecord {
    companion object : UndraCodec<Post> {
        override fun encode(w: UndraWriter, v: Post) {
            PostId.encode(w, v.id)
            w.writeStr(v.author)
            w.writeStr(v.body)
        }

        override fun decode(r: UndraReader): Post = Post(
            id = PostId.decode(r),
            author = r.readStr(),
            body = r.readStr(),
        )
    }
}

/** A post's id. */
@JvmInline
value class PostId(val value: ULong) : UndraRecord, Comparable<PostId> {
    override fun compareTo(other: PostId): Int = value.compareTo(other.value)

    companion object : UndraCodec<PostId> {
        override fun encode(w: UndraWriter, v: PostId) {
            w.writeU64(v.value)
        }

        override fun decode(r: UndraReader): PostId = PostId(r.readU64())
    }
}

enum class Filter(val index: UShort) : UndraEnum {
    ALL(0u),
    MINE(1u);

    companion object : UndraCodec<Filter> {
        override fun encode(w: UndraWriter, v: Filter) = w.writeU16(v.index)

        override fun decode(r: UndraReader): Filter {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> ALL
                1 -> MINE
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Filter")
            }
        }
    }
}

/** The fetch state of a query (SPEC section 9). */
enum class QueryStatus(val index: UShort) : UndraEnum {
    /** No fetch has started. */
    IDLE(0u),
    /** A fetch is in flight. */
    FETCHING(1u),
    /** The latest fetch succeeded. */
    SUCCESS(2u),
    /** The latest fetch failed. */
    ERROR(3u);

    companion object : UndraCodec<QueryStatus> {
        override fun encode(w: UndraWriter, v: QueryStatus) = w.writeU16(v.index)

        override fun decode(r: UndraReader): QueryStatus {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> IDLE
                1 -> FETCHING
                2 -> SUCCESS
                3 -> ERROR
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "QueryStatus")
            }
        }
    }
}
