// Generated by undra-bindgen from the Undra schema of `golden-decimal` (schema hash 0x166092f7b788cc34). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.decimal

import dev.undra.runtime.UndraException
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

sealed class PayError(message: String) : UndraException(message) {
    data object Declined : PayError("declined")

    companion object : UndraCodec<PayError> {
        override fun encode(w: UndraWriter, v: PayError) {
            when (v) {
                Declined -> w.writeU16(0u)
            }
        }

        override fun decode(r: UndraReader): PayError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Declined
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "PayError")
            }
        }
    }
}
