// Generated by undra-bindgen from the Undra schema of `golden-decimal` (schema hash 0x166092f7b788cc34). Do not edit.

package golden.decimal

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll

/**
 * Prices `qty` items.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
fun quote(qty: UInt, ctx: UndraCore = UndraGoldenDecimal.core): Invoice {
    val w = UndraWriter()
    w.writeU32(qty)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.QUOTE),
            UndraIds.Functions.QUOTE,
            w.toByteArray(),
        )
        return Invoice.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}
