// Generated by undra-bindgen from the Undra schema of `golden-decimal` (schema hash 0x166092f7b788cc34). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.decimal

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraStore
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import java.math.BigDecimal
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map

/** Takes payments. */
class Till internal constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _balance: MutableStateFlow<BigDecimal> = signal(BigDecimal.ZERO)
    val balance: StateFlow<BigDecimal> = _balance.asStateFlow()
    private val _last: MutableStateFlow<Price?> = signal(null)
    val last: StateFlow<Price?> = _last.asStateFlow()
    private val _history: MutableStateFlow<List<BigDecimal>> = signal(emptyList())
    val history: StateFlow<List<BigDecimal>> = _history.asStateFlow()
    private val _invoice: MutableStateFlow<Invoice> = signal(Invoice(total = BigDecimal.ZERO, lines = emptyList(), discount = null, price = Price(BigDecimal.ZERO), bySku = emptyMap(), prices = emptyMap(), tax = BigDecimal.ZERO))
    val invoice: StateFlow<Invoice> = _invoice.asStateFlow()

    /**
     * Takes `amount` and returns the balance.
     * @throws PayError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun charge(amount: BigDecimal): BigDecimal {
        val w = UndraWriter()
        Codecs.decimal.encode(w, amount)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Till.CHARGE),
                UndraIds.Objects.Till.CHARGE,
                w.toByteArray(),
            )
            return Codecs.decimal.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, PayError)
        }
    }

    /** A failure is logged and passed to `LoadOptions.onError`; the method does not throw. */
    fun refund(amount: BigDecimal?) {
        try {
            val w = UndraWriter()
            codecOptionDecimal.encode(w, amount)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Till.REFUND),
                UndraIds.Objects.Till.REFUND,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "Till.refund")
        }
    }

    /** Collecting throws UndraCallError; cancelling the collector ends it quietly. */
    fun totals(): Flow<BigDecimal> {
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Till.TOTALS),
            UndraIds.Objects.Till.TOTALS,
            ByteArray(0),
        )
        return stream
            .map { bytes -> Codecs.decimal.decodeAll(bytes) }
            .catch { error ->
                throw UndraCallError.mappedStream(error)
            }
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        try {
            when (signalId) {
                0u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Codecs.decimal.decode(reader)
                        reader.finish()
                        _balance.value = value
                    }
                }
                1u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionPrice.decode(reader)
                        reader.finish()
                        _last.value = value
                    }
                }
                2u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecVecDecimal.decode(reader)
                        reader.finish()
                        _history.value = value
                    }
                }
                3u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Invoice.decode(reader)
                        reader.finish()
                        _invoice.value = value
                    }
                }
                else -> Unit
            }
        } catch (e: Exception) {
            core.report(e, "Till.apply(signal: $signalId)")
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        operator fun invoke(ctx: UndraCore = UndraGoldenDecimal.core): Till = create(ctx)

        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraGoldenDecimal.core): Till {
            val handle = ctx.constructObject(UndraIds.Objects.Till.TYPE_ID, UndraIds.Objects.Till.NEW, ByteArray(0))
            return ctx.adopt(handle, ::Till)
        }
    }
}

private val codecOptionDecimal = Codecs.option(Codecs.decimal)
private val codecOptionPrice = Codecs.option(Price)
private val codecVecDecimal = Codecs.vec(Codecs.decimal)
