// Generated by undra-bindgen from the Undra schema of `golden-decimal` (schema hash 0x166092f7b788cc34). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.decimal

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import java.math.BigDecimal

/** Money amounts of every shape. */
data class Invoice(
    val total: BigDecimal,
    val lines: List<BigDecimal>,
    val discount: BigDecimal?,
    val price: Price,
    val bySku: Map<String, BigDecimal>,
    val prices: Map<UInt, Price>,
    val tax: BigDecimal = BigDecimal.ZERO,
) : UndraRecord {
    companion object : UndraCodec<Invoice> {
        override fun encode(w: UndraWriter, v: Invoice) {
            Codecs.decimal.encode(w, v.total)
            codecVecDecimal.encode(w, v.lines)
            codecOptionDecimal.encode(w, v.discount)
            Price.encode(w, v.price)
            codecMapStringDecimal.encode(w, v.bySku)
            codecMapU32Price.encode(w, v.prices)
            Codecs.decimal.encode(w, v.tax)
        }

        override fun decode(r: UndraReader): Invoice = Invoice(
            total = Codecs.decimal.decode(r),
            lines = codecVecDecimal.decode(r),
            discount = codecOptionDecimal.decode(r),
            price = Price.decode(r),
            bySku = codecMapStringDecimal.decode(r),
            prices = codecMapU32Price.decode(r),
            tax = Codecs.decimal.decode(r),
        )
    }
}

/** A price: a decimal with an order. */
@JvmInline
value class Price(val value: BigDecimal) : UndraRecord, Comparable<Price> {
    override fun compareTo(other: Price): Int = value.compareTo(other.value)

    companion object : UndraCodec<Price> {
        override fun encode(w: UndraWriter, v: Price) {
            Codecs.decimal.encode(w, v.value)
        }

        override fun decode(r: UndraReader): Price = Price(Codecs.decimal.decode(r))
    }
}

/** The fetch state of a query (SPEC section 9). */
enum class QueryStatus(val index: UShort) : UndraEnum {
    /** No fetch has started. */
    IDLE(0u),
    /** A fetch is in flight. */
    FETCHING(1u),
    /** The latest fetch succeeded. */
    SUCCESS(2u),
    /** The latest fetch failed. */
    ERROR(3u);

    companion object : UndraCodec<QueryStatus> {
        override fun encode(w: UndraWriter, v: QueryStatus) = w.writeU16(v.index)

        override fun decode(r: UndraReader): QueryStatus {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> IDLE
                1 -> FETCHING
                2 -> SUCCESS
                3 -> ERROR
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "QueryStatus")
            }
        }
    }
}

private val codecVecDecimal = Codecs.vec(Codecs.decimal)
private val codecOptionDecimal = Codecs.option(Codecs.decimal)
private val codecMapStringDecimal = Codecs.map(Codecs.string, Codecs.decimal)
private val codecMapU32Price = Codecs.map(Codecs.u32, Price)
