package dev.undra.android

import dev.undra.runtime.UndraException
import java.security.GeneralSecurityException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Why a secret could not be stored or read: the key is missing or unusable, or the stored bytes are not what this
 * store wrote (tampered with, moved to another key, or sealed under a key that is gone). `SecureStore` has no error
 * channel in its signature, so the core sees `PortError::Unavailable` (ADR-025) and the runtime logs this message.
 */
public class SecureStoreException(message: String, cause: Throwable? = null) : UndraException(message, cause)

/**
 * The sealed form of a secret: `format u8, iv (12 bytes), ciphertext and 16-byte tag`, with AES-256-GCM and the key
 * name as authenticated data (`undra.secure:<key>`), so a ciphertext cannot be moved to another key. This is the layout
 * of the TypeScript `webCryptoSecureStore`; only where the key lives differs (the Android Keystore here).
 *
 * Pure `javax.crypto`: the tests seal with a software key; the adapter seals with a key that never leaves the Keystore.
 */
internal object SecureSeal {
    const val FORMAT: Int = 1
    const val IV_BYTES: Int = 12
    const val TAG_BITS: Int = 128
    private const val TAG_BYTES = TAG_BITS / 8
    private const val TRANSFORMATION = "AES/GCM/NoPadding"

    /** The authenticated data of the entry [key]. */
    fun aad(key: String): ByteArray = "undra.secure:$key".toByteArray(Charsets.UTF_8)

    /** Seals [plain] under [secret] for the entry [key]; the IV is generated by the cipher, fresh for every call. */
    fun seal(secret: SecretKey, key: String, plain: ByteArray): ByteArray {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, secret)
            cipher.updateAAD(aad(key))
            val sealed = cipher.doFinal(plain)
            val iv = cipher.iv
            if (iv == null || iv.size != IV_BYTES) throw SecureStoreException("the cipher produced an IV of ${iv?.size} bytes, expected $IV_BYTES")
            val out = ByteArray(1 + IV_BYTES + sealed.size)
            out[0] = FORMAT.toByte()
            System.arraycopy(iv, 0, out, 1, IV_BYTES)
            System.arraycopy(sealed, 0, out, 1 + IV_BYTES, sealed.size)
            return out
        } catch (e: GeneralSecurityException) {
            throw SecureStoreException("could not encrypt the value for '$key': ${e.message}", e)
        } catch (e: RuntimeException) {
            // Android's Keystore reports some failures as unchecked exceptions (ProviderException, KeyStoreException).
            throw SecureStoreException("could not encrypt the value for '$key': ${e.message}", e)
        }
    }

    /** Opens what [seal] produced for the entry [key]. */
    fun open(secret: SecretKey, key: String, stored: ByteArray): ByteArray {
        if (stored.size < 1 + IV_BYTES + TAG_BYTES || stored[0].toInt() != FORMAT) {
            throw SecureStoreException("the value stored under '$key' is not in the secure-store format")
        }
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secret, GCMParameterSpec(TAG_BITS, stored, 1, IV_BYTES))
            cipher.updateAAD(aad(key))
            return cipher.doFinal(stored, 1 + IV_BYTES, stored.size - 1 - IV_BYTES)
        } catch (e: GeneralSecurityException) {
            throw SecureStoreException(
                "the value stored under '$key' failed authentication: it was altered, copied from another key, " +
                    "or sealed under a key this device no longer has",
                e,
            )
        } catch (e: RuntimeException) {
            throw SecureStoreException("could not decrypt the value stored under '$key': ${e.message}", e)
        }
    }
}
