package dev.undra.android

import android.security.keystore.KeyPermanentlyInvalidatedException
import android.security.keystore.UserNotAuthenticatedException
import dev.undra.runtime.adapters.StorageError
import java.io.IOException
import java.security.NoSuchProviderException
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * The sealed form of a secret: `format u8, iv (12 bytes), ciphertext and 16-byte tag`, with AES-256-GCM and the key
 * name as authenticated data (`undra.secure:<key>`), so a ciphertext cannot be moved to another key. This is the layout
 * of the TypeScript `webCryptoSecureStore`; only where the key lives differs (the Android Keystore here).
 *
 * Failures are [StorageError]s (ADR-049), mapped by [failure]: bytes that are not in this format, or that fail
 * authentication, are [StorageError.Corrupt]. No message ever contains the value.
 *
 * Pure `javax.crypto`: the tests seal with a software key; the adapter seals with a key that never leaves the Keystore.
 */
internal object SecureSeal {
    const val FORMAT: Int = 1
    const val IV_BYTES: Int = 12
    const val TAG_BITS: Int = 128
    private const val TAG_BYTES = TAG_BITS / 8
    private const val TRANSFORMATION = "AES/GCM/NoPadding"

    /** The authenticated data of the entry [key]. */
    fun aad(key: String): ByteArray = "undra.secure:$key".toByteArray(Charsets.UTF_8)

    /**
     * Seals [plain] under [secret] for the entry [key]; the IV is generated by the cipher, fresh for every call.
     *
     * @throws StorageError if the cipher refuses (see [failure]).
     */
    fun seal(secret: SecretKey, key: String, plain: ByteArray): ByteArray {
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.ENCRYPT_MODE, secret)
            cipher.updateAAD(aad(key))
            val sealed = cipher.doFinal(plain)
            val iv = cipher.iv
            if (iv == null || iv.size != IV_BYTES) throw StorageError.Io("the cipher produced an IV of ${iv?.size} bytes, expected $IV_BYTES")
            val out = ByteArray(1 + IV_BYTES + sealed.size)
            out[0] = FORMAT.toByte()
            System.arraycopy(iv, 0, out, 1, IV_BYTES)
            System.arraycopy(sealed, 0, out, 1 + IV_BYTES, sealed.size)
            return out
        } catch (e: Exception) {
            throw failure(e, "encrypting the value for '$key'")
        }
    }

    /**
     * Opens what [seal] produced for the entry [key].
     *
     * @throws StorageError.Corrupt if [stored] is not in this format or fails authentication (altered, copied from
     *   another key, or sealed under a key this device no longer has).
     * @throws StorageError if the cipher refuses for another reason (see [failure]).
     */
    fun open(secret: SecretKey, key: String, stored: ByteArray): ByteArray {
        if (stored.size < 1 + IV_BYTES + TAG_BYTES || stored[0].toInt() != FORMAT) {
            throw StorageError.Corrupt("the value stored under '$key' is not in the secure-store format")
        }
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION)
            cipher.init(Cipher.DECRYPT_MODE, secret, GCMParameterSpec(TAG_BITS, stored, 1, IV_BYTES))
            cipher.updateAAD(aad(key))
            return cipher.doFinal(stored, 1 + IV_BYTES, stored.size - 1 - IV_BYTES)
        } catch (e: AEADBadTagException) {
            throw StorageError.Corrupt(
                "the value stored under '$key' failed authentication: it was altered, copied from another key, " +
                    "or sealed under a key this device no longer has",
            )
        } catch (e: Exception) {
            throw failure(e, "decrypting the value stored under '$key'")
        }
    }

    /**
     * The [StorageError] a failure of the Keystore or of the cipher stands for while [doing] something (ADR-049, the
     * Kotlin column of decision 1.3):
     *
     * | Failure | StorageError |
     * |---|---|
     * | a [StorageError] already | itself |
     * | `UserNotAuthenticatedException` (a key that needs the user to authenticate first) | [StorageError.Locked] |
     * | `KeyPermanentlyInvalidatedException` (the lock screen was removed or reset, biometrics changed) | [StorageError.Corrupt] |
     * | `AEADBadTagException` (a ciphertext that fails authentication) | [StorageError.Corrupt] |
     * | `NoSuchProviderException` (no `AndroidKeyStore` provider) | [StorageError.Unavailable] |
     * | an `IOException` | [StorageError.of]: `Full` for `ENOSPC`, else `Io` |
     * | anything else (`ProviderException`, `android.security.KeyStoreException`, ...) | [StorageError.Io] |
     */
    fun failure(e: Exception, doing: String): StorageError = when (e) {
        is StorageError -> e
        is UserNotAuthenticatedException -> StorageError.Locked
        is KeyPermanentlyInvalidatedException ->
            StorageError.Corrupt("the Keystore key was permanently invalidated (the lock screen was removed or reset), so $doing failed")
        is AEADBadTagException -> StorageError.Corrupt("$doing failed authentication")
        is NoSuchProviderException -> StorageError.Unavailable("the Android Keystore is not available: ${e.message}")
        is IOException -> StorageError.of(e)
        else -> StorageError.Io("$doing failed: ${e.javaClass.simpleName}: ${e.message}")
    }
}
