// Generated by undra-bindgen from the Undra schema of `golden-objects` (schema hash 0x892e61432c31cead). Do not edit.

import { type Codec, WireError } from "@undra/runtime";

export interface Stats {
  count: number;
  total: bigint;
}

export const StatsCodec: Codec<Stats> = {
  encode(w, v) {
    w.writeU32(v.count);
    w.writeI64(v.total);
  },
  decode(r) {
    return {
      count: r.readU32(),
      total: r.readI64(),
    };
  },
};

export interface Todo {
  id: string;
  title: string;
}

export const TodoCodec: Codec<Todo> = {
  encode(w, v) {
    w.writeUuid(v.id);
    w.writeStr(v.title);
  },
  decode(r) {
    return {
      id: r.readUuid(),
      title: r.readStr(),
    };
  },
};

export type Mode = "fast" | "exact";

export const ModeCodec: Codec<Mode> = {
  encode(w, v) {
    switch (v) {
      case "fast":
        w.writeU16(0);
        break;
      case "exact":
        w.writeU16(1);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return "fast";
      case 1:
        return "exact";
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "Mode" });
    }
  },
};
