// Generated by keel-bindgen from the Keel schema of `golden-objects` (schema hash 0x0d92b39c89f299e1). Do not edit.

package golden.objects

import dev.keel.runtime.KeelException
import dev.keel.runtime.KeelReplyException
import dev.keel.runtime.wire.KeelCodec
import dev.keel.runtime.wire.KeelReader
import dev.keel.runtime.wire.KeelWriter
import dev.keel.runtime.wire.Payloads.ReplyStatus
import dev.keel.runtime.wire.WireException
import dev.keel.runtime.wire.decodeAll

sealed class CalcError(message: String) : KeelException(message) {
    data object Overflow : CalcError("overflow")
    data object DivideByZero : CalcError("divide by zero")

    companion object : KeelCodec<CalcError> {
        override fun encode(w: KeelWriter, v: CalcError) {
            when (v) {
                Overflow -> w.writeU16(0u)
                DivideByZero -> w.writeU16(1u)
            }
        }

        override fun decode(r: KeelReader): CalcError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Overflow
                1 -> DivideByZero
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "CalcError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: KeelReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}
