// Generated by keel-bindgen from the Keel schema of `golden-objects` (schema hash 0x0d92b39c89f299e1). Do not edit.

package golden.objects

import dev.keel.runtime.KeelEnum
import dev.keel.runtime.KeelRecord
import dev.keel.runtime.wire.Codecs
import dev.keel.runtime.wire.KeelCodec
import dev.keel.runtime.wire.KeelReader
import dev.keel.runtime.wire.KeelWriter
import dev.keel.runtime.wire.WireException
import java.util.UUID

data class Stats(
    val count: UInt,
    val total: Long,
) : KeelRecord {
    companion object : KeelCodec<Stats> {
        override fun encode(w: KeelWriter, v: Stats) {
            w.writeU32(v.count)
            w.writeI64(v.total)
        }

        override fun decode(r: KeelReader): Stats = Stats(count = r.readU32(), total = r.readI64())
    }
}

data class Todo(
    val id: UUID,
    val title: String,
) : KeelRecord {
    companion object : KeelCodec<Todo> {
        override fun encode(w: KeelWriter, v: Todo) {
            Codecs.uuid.encode(w, v.id)
            w.writeStr(v.title)
        }

        override fun decode(r: KeelReader): Todo = Todo(
            id = Codecs.uuid.decode(r),
            title = r.readStr(),
        )
    }
}

enum class Mode(val index: UShort) : KeelEnum {
    FAST(0u),
    EXACT(1u);

    companion object : KeelCodec<Mode> {
        override fun encode(w: KeelWriter, v: Mode) = w.writeU16(v.index)

        override fun decode(r: KeelReader): Mode {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> FAST
                1 -> EXACT
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Mode")
            }
        }
    }
}
