// Generated by undra-bindgen from the Undra schema of `golden-records` (schema hash 0x3e314305379cf9a4). Do not edit.

package golden.records

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0x3e314305379cf9a4uL
    const val NAMESPACE: String = "golden_records"

    object Objects {}

    object Functions {}

    object Ports {}

    object Queries {}
}
