// Generated by undra-bindgen from the Undra schema of `golden-records` (schema hash 0x3e314305379cf9a4). Do not edit.

package golden.records

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.Timestamp
import dev.undra.runtime.wire.WireException
import java.util.UUID
import kotlin.time.Duration

/** Nested containers and bytes. */
data class Containers(
    val lines: List<String?>,
    val scores: Map<String, Int>,
    val byId: Map<UUID, List<Todo>>,
    val blob: ByteArray,
    val maybeBlob: ByteArray?,
    val matrix: List<List<Double>>,
    val counts: Map<UInt, ULong> = emptyMap(),
) : UndraRecord {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is Containers) return false
        return lines == other.lines && scores == other.scores && byId == other.byId && blob.contentEquals(other.blob) && maybeBlob.contentEquals(other.maybeBlob) && matrix == other.matrix && counts == other.counts
    }

    override fun hashCode(): Int {
        var result = lines.hashCode()
        result = 31 * result + scores.hashCode()
        result = 31 * result + byId.hashCode()
        result = 31 * result + blob.contentHashCode()
        result = 31 * result + maybeBlob.contentHashCode()
        result = 31 * result + matrix.hashCode()
        result = 31 * result + counts.hashCode()
        return result
    }

    companion object : UndraCodec<Containers> {
        override fun encode(w: UndraWriter, v: Containers) {
            codecVecOptionString.encode(w, v.lines)
            codecMapStringI32.encode(w, v.scores)
            codecMapUuidVecTodo.encode(w, v.byId)
            w.writeBytes(v.blob)
            codecOptionBytes.encode(w, v.maybeBlob)
            codecVecVecF64.encode(w, v.matrix)
            codecMapU32U64.encode(w, v.counts)
        }

        override fun decode(r: UndraReader): Containers = Containers(
            lines = codecVecOptionString.decode(r),
            scores = codecMapStringI32.decode(r),
            byId = codecMapUuidVecTodo.decode(r),
            blob = r.readBytes(),
            maybeBlob = codecOptionBytes.decode(r),
            matrix = codecVecVecF64.decode(r),
            counts = codecMapU32U64.decode(r),
        )
    }
}

/** A record without fields. */
class Empty : UndraRecord {
    override fun equals(other: Any?): Boolean = other is Empty

    override fun hashCode(): Int = 0

    override fun toString(): String = "Empty()"

    companion object : UndraCodec<Empty> {
        override fun encode(w: UndraWriter, v: Empty) {}

        override fun decode(r: UndraReader): Empty = Empty()
    }
}

/** Field names that are reserved words in some target language. */
data class Keywords(
    val default: String,
    val `in`: Int,
    val `object`: Boolean,
    val delete: Boolean,
    val new: Boolean,
    val className: String,
) : UndraRecord {
    companion object : UndraCodec<Keywords> {
        override fun encode(w: UndraWriter, v: Keywords) {
            w.writeStr(v.default)
            w.writeI32(v.`in`)
            w.writeBool(v.`object`)
            w.writeBool(v.delete)
            w.writeBool(v.new)
            w.writeStr(v.className)
        }

        override fun decode(r: UndraReader): Keywords = Keywords(
            default = r.readStr(),
            `in` = r.readI32(),
            `object` = r.readBool(),
            delete = r.readBool(),
            new = r.readBool(),
            className = r.readStr(),
        )
    }
}

/** Every fixed-width number type. */
data class Numbers(
    val a: Byte,
    val b: Short,
    val c: Int,
    val d: Long,
    val e: UByte,
    val f: UShort,
    val g: UInt,
    val h: ULong,
    val i: Float,
    val j: Double,
    val elapsed: Duration,
) : UndraRecord {
    companion object : UndraCodec<Numbers> {
        override fun encode(w: UndraWriter, v: Numbers) {
            w.writeI8(v.a)
            w.writeI16(v.b)
            w.writeI32(v.c)
            w.writeI64(v.d)
            w.writeU8(v.e)
            w.writeU16(v.f)
            w.writeU32(v.g)
            w.writeU64(v.h)
            w.writeF32(v.i)
            w.writeF64(v.j)
            Codecs.duration.encode(w, v.elapsed)
        }

        override fun decode(r: UndraReader): Numbers = Numbers(
            a = r.readI8(),
            b = r.readI16(),
            c = r.readI32(),
            d = r.readI64(),
            e = r.readU8(),
            f = r.readU16(),
            g = r.readU32(),
            h = r.readU64(),
            i = r.readF32(),
            j = r.readF64(),
            elapsed = Codecs.duration.decode(r),
        )
    }
}

/** A recursive record. */
data class Page(
    val items: List<Todo>,
    val next: String?,
    val children: List<Page>,
) : UndraRecord {
    companion object : UndraCodec<Page> {
        override fun encode(w: UndraWriter, v: Page) {
            codecVecTodo.encode(w, v.items)
            codecOptionString.encode(w, v.next)
            codecVecPage.encode(w, v.children)
        }

        override fun decode(r: UndraReader): Page = Page(
            items = codecVecTodo.decode(r),
            next = codecOptionString.decode(r),
            children = codecVecPage.decode(r),
        )
    }
}

/**
 * A todo item.
 * Shown in the list and synced to the server.
 */
data class Todo(
    /** Stable identifier. */
    val id: UUID,
    val title: String,
    val done: Boolean = false,
    val tags: List<String> = emptyList(),
    val due: Timestamp?,
    val priority: Priority,
) : UndraRecord {
    companion object : UndraCodec<Todo> {
        override fun encode(w: UndraWriter, v: Todo) {
            Codecs.uuid.encode(w, v.id)
            w.writeStr(v.title)
            w.writeBool(v.done)
            codecVecString.encode(w, v.tags)
            codecOptionTimestamp.encode(w, v.due)
            Priority.encode(w, v.priority)
        }

        override fun decode(r: UndraReader): Todo = Todo(
            id = Codecs.uuid.decode(r),
            title = r.readStr(),
            done = r.readBool(),
            tags = codecVecString.decode(r),
            due = codecOptionTimestamp.decode(r),
            priority = Priority.decode(r),
        )
    }
}

enum class Priority(val index: UShort) : UndraEnum {
    LOW(0u),
    NORMAL(1u),
    HIGH(2u);

    companion object : UndraCodec<Priority> {
        override fun encode(w: UndraWriter, v: Priority) = w.writeU16(v.index)

        override fun decode(r: UndraReader): Priority {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> LOW
                1 -> NORMAL
                2 -> HIGH
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Priority")
            }
        }
    }
}

private val codecOptionString = Codecs.option(Codecs.string)
private val codecVecOptionString = Codecs.vec(codecOptionString)
private val codecMapStringI32 = Codecs.map(Codecs.string, Codecs.i32)
private val codecVecTodo = Codecs.vec(Todo)
private val codecMapUuidVecTodo = Codecs.map(Codecs.uuid, codecVecTodo)
private val codecOptionBytes = Codecs.option(Codecs.bytes)
private val codecVecF64 = Codecs.vec(Codecs.f64)
private val codecVecVecF64 = Codecs.vec(codecVecF64)
private val codecMapU32U64 = Codecs.map(Codecs.u32, Codecs.u64)
private val codecVecPage = Codecs.vec(Page)
private val codecVecString = Codecs.vec(Codecs.string)
private val codecOptionTimestamp = Codecs.option(Codecs.timestamp)
