// Generated by undra-bindgen from the Undra schema of `golden-stdlib` (schema hash 0x8069411db116cf1c). Do not edit.

package golden.stdlib

import dev.undra.runtime.UndraException
import dev.undra.runtime.adapters.FsError
import dev.undra.runtime.adapters.HttpError
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

/** Why a sync failed. */
sealed class SyncError(message: String) : UndraException(message) {
    data object Offline : SyncError("offline")
    data class Http(override val cause: HttpError) : SyncError(cause.message.orEmpty())
    data class Disk(val value0: FsError, val value1: String) : SyncError("disk failure at ${value1}")
    data class Rejected(val status: UShort) : SyncError("status ${status}")

    companion object : UndraCodec<SyncError> {
        override fun encode(w: UndraWriter, v: SyncError) {
            when (v) {
                Offline -> w.writeU16(0u)
                is Http -> {
                    w.writeU16(1u)
                    HttpError.encode(w, v.cause)
                }
                is Disk -> {
                    w.writeU16(2u)
                    FsError.encode(w, v.value0)
                    w.writeStr(v.value1)
                }
                is Rejected -> {
                    w.writeU16(3u)
                    w.writeU16(v.status)
                }
            }
        }

        override fun decode(r: UndraReader): SyncError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Offline
                1 -> Http(cause = HttpError.decode(r))
                2 -> Disk(value0 = FsError.decode(r), value1 = r.readStr())
                3 -> Rejected(status = r.readU16())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "SyncError")
            }
        }
    }
}
