// Generated by undra-bindgen from the Undra schema of `golden-stdlib` (schema hash 0x68d664b4fa4eea2f). Do not edit.

package golden.stdlib

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0x68d664b4fa4eea2fuL
    const val NAMESPACE: String = "golden_stdlib"

    object Objects {
        object Syncer {
            const val TYPE_ID: UInt = 0xdc9167edu
            const val NEW: UInt = 0xb8a68205u
            const val SEND: UInt = 0xa583dcdbu
            const val FOLLOW: UInt = 0x0440a284u
            const val SAVE: UInt = 0x295cb30cu
            const val SYNC: UInt = 0x106ad916u
            const val LOCAL: UInt = 0x0f8be6acu
            const val LISTEN: UInt = 0xdc2f9c0au
            const val PUSH: UInt = 0x1e405c79u
        }
        object Link {
            const val TYPE_ID: UInt = 0x8e08e589u
            const val NEW: UInt = 0xab6c25b1u
        }
        object LatestResponseQueryHandle {
            const val TYPE_ID: UInt = 0xa033306au
            const val NEW: UInt = 0xa033306au
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
        }
    }

    object Functions {}

    object Ports {
        object Uploader {
            const val PORT_ID: UInt = 0x877288a2u
            const val UPLOAD: UInt = 0x815b2b02u
        }
    }

    object Queries {
        const val LATEST_RESPONSE: UInt = 0xa033306au
        const val RETRY: UInt = 0x0fc1ccaeu
    }
}
