// Generated by undra-bindgen from the Undra schema of `golden-stdlib` (schema hash 0x6b4638c4a5e34313). Do not edit.

package golden.stdlib

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraObject
import dev.undra.runtime.adapters.FsError
import dev.undra.runtime.adapters.HttpError
import dev.undra.runtime.adapters.HttpRequest
import dev.undra.runtime.adapters.HttpResponse
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map

/** Talks to the server. */
class Syncer private constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
    constructor(ctx: UndraCore = UndraGoldenStdlib.core) : this(
        ctx,
        ctx.constructObject(UndraIds.Objects.Syncer.TYPE_ID, UndraIds.Objects.Syncer.NEW, ByteArray(0)),
    )

    /**
     * Performs one request.
     * @throws HttpError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun send(request: HttpRequest): HttpResponse {
        val w = UndraWriter()
        HttpRequest.encode(w, request)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SEND),
                UndraIds.Objects.Syncer.SEND,
                w.toByteArray(),
            )
            return HttpResponse.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, HttpError)
        }
    }

    /**
     * Streams the responses of a request that repeats.
     * Collecting throws HttpError or UndraCallError; cancelling the collector ends it quietly.
     */
    fun follow(endpoint: Endpoint): Flow<HttpResponse> {
        val w = UndraWriter()
        Endpoint.encode(w, endpoint)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.FOLLOW),
            UndraIds.Objects.Syncer.FOLLOW,
            w.toByteArray(),
        )
        return stream
            .map { bytes -> HttpResponse.decodeAll(bytes) }
            .catch { error ->
                throw UndraCallError.mappedStream(error, HttpError)
            }
    }

    /**
     * Writes the last response to disk.
     * @throws FsError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun save(path: String) {
        val w = UndraWriter()
        w.writeStr(path)
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SAVE),
                UndraIds.Objects.Syncer.SAVE,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, FsError)
        }
    }

    /**
     * @throws SyncError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun sync() {
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SYNC),
                UndraIds.Objects.Syncer.SYNC,
                ByteArray(0),
            )
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, SyncError)
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraGoldenStdlib.core): Syncer {
            val handle = ctx.constructObject(UndraIds.Objects.Syncer.TYPE_ID, UndraIds.Objects.Syncer.NEW, ByteArray(0))
            return Syncer(ctx, handle)
        }
    }
}
