// Generated by undra-bindgen from the Undra schema of `golden-stdlib` (schema hash 0x6b4638c4a5e34313). Do not edit.

package golden.stdlib

import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraObject
import dev.undra.runtime.UndraReplyException
import dev.undra.runtime.adapters.FsError
import dev.undra.runtime.adapters.HttpError
import dev.undra.runtime.adapters.HttpRequest
import dev.undra.runtime.adapters.HttpResponse
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ReplyStatus
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map

/** Talks to the server. */
class Syncer private constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    constructor(ctx: UndraCore = UndraCore.shared) : this(
        ctx,
        ctx.construct(UndraIds.Objects.Syncer.TYPE_ID, UndraIds.Objects.Syncer.NEW, ByteArray(0)),
    )

    /**
     * Performs one request.
     * @throws HttpError
     */
    suspend fun send(request: HttpRequest): HttpResponse {
        val w = UndraWriter()
        HttpRequest.encode(w, request)
        val body = try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SEND),
                UndraIds.Objects.Syncer.SEND,
                w.toByteArray(),
            )
        } catch (e: UndraReplyException) {
            throw if (e.status == ReplyStatus.ERROR) HttpError.decodeAll(e.body) else e
        }
        return HttpResponse.decodeAll(body)
    }

    /**
     * Streams the responses of a request that repeats.
     * @throws HttpError
     */
    fun follow(endpoint: Endpoint): Flow<HttpResponse> {
        val w = UndraWriter()
        Endpoint.encode(w, endpoint)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.FOLLOW),
            UndraIds.Objects.Syncer.FOLLOW,
            w.toByteArray(),
        )
        return stream
            .map { bytes -> HttpResponse.decodeAll(bytes) }
            .catch { error ->
                throw if (error is UndraReplyException && error.status == ReplyStatus.ERROR) HttpError.decodeAll(error.body) else error
            }
    }

    /**
     * Writes the last response to disk.
     * @throws FsError
     */
    suspend fun save(path: String) {
        val w = UndraWriter()
        w.writeStr(path)
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SAVE),
                UndraIds.Objects.Syncer.SAVE,
                w.toByteArray(),
            )
        } catch (e: UndraReplyException) {
            throw if (e.status == ReplyStatus.ERROR) FsError.decodeAll(e.body) else e
        }
    }

    /** @throws SyncError */
    suspend fun sync() {
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SYNC),
                UndraIds.Objects.Syncer.SYNC,
                ByteArray(0),
            )
        } catch (e: UndraReplyException) {
            throw SyncError.fromReply(e)
        }
    }

    companion object {
        fun create(ctx: UndraCore = UndraCore.shared): Syncer {
            val handle = ctx.construct(UndraIds.Objects.Syncer.TYPE_ID, UndraIds.Objects.Syncer.NEW, ByteArray(0))
            return Syncer(ctx, handle)
        }
    }
}
