// Generated by undra-bindgen from the Undra schema of `golden-stdlib` (schema hash 0xfa67a4e57ec4340c). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.stdlib

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraObject
import dev.undra.runtime.adapters.DbError
import dev.undra.runtime.adapters.DbRows
import dev.undra.runtime.adapters.FsError
import dev.undra.runtime.adapters.HttpError
import dev.undra.runtime.adapters.HttpRequest
import dev.undra.runtime.adapters.HttpResponse
import dev.undra.runtime.adapters.SseError
import dev.undra.runtime.adapters.SseEvent
import dev.undra.runtime.adapters.WsError
import dev.undra.runtime.adapters.WsMessage
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map

/** Talks to the server. */
class Syncer internal constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    /**
     * Performs one request.
     * @throws HttpError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun send(request: HttpRequest): HttpResponse {
        val w = UndraWriter()
        HttpRequest.encode(w, request)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SEND),
                UndraIds.Objects.Syncer.SEND,
                w.toByteArray(),
            )
            return HttpResponse.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, HttpError)
        }
    }

    /**
     * Streams the responses of a request that repeats.
     * Collecting throws HttpError or UndraCallError; cancelling the collector ends it quietly.
     */
    fun follow(endpoint: Endpoint): Flow<HttpResponse> {
        val w = UndraWriter()
        Endpoint.encode(w, endpoint)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.FOLLOW),
            UndraIds.Objects.Syncer.FOLLOW,
            w.toByteArray(),
        )
        return stream
            .map { bytes -> HttpResponse.decodeAll(bytes) }
            .catch { error ->
                throw UndraCallError.mappedStream(error, HttpError)
            }
    }

    /**
     * Writes the last response to disk.
     * @throws FsError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun save(path: String) {
        val w = UndraWriter()
        w.writeStr(path)
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SAVE),
                UndraIds.Objects.Syncer.SAVE,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, FsError)
        }
    }

    /**
     * @throws SyncError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun sync() {
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.SYNC),
                UndraIds.Objects.Syncer.SYNC,
                ByteArray(0),
            )
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, SyncError)
        }
    }

    /**
     * Reads the local database.
     * @throws DbError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun local(sql: String): DbRows {
        val w = UndraWriter()
        w.writeStr(sql)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.LOCAL),
                UndraIds.Objects.Syncer.LOCAL,
                w.toByteArray(),
            )
            return DbRows.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, DbError)
        }
    }

    /**
     * Streams the server's events.
     * Collecting throws SseError or UndraCallError; cancelling the collector ends it quietly.
     */
    fun listen(): Flow<SseEvent> {
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.LISTEN),
            UndraIds.Objects.Syncer.LISTEN,
            ByteArray(0),
        )
        return stream
            .map { bytes -> SseEvent.decodeAll(bytes) }
            .catch { error ->
                throw UndraCallError.mappedStream(error, SseError)
            }
    }

    /**
     * Sends one message on the live connection.
     * @throws WsError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun push(message: WsMessage) {
        val w = UndraWriter()
        WsMessage.encode(w, message)
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Syncer.PUSH),
                UndraIds.Objects.Syncer.PUSH,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, WsError)
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        operator fun invoke(ctx: UndraCore = UndraGoldenStdlib.core): Syncer = create(ctx)

        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraGoldenStdlib.core): Syncer {
            val handle = ctx.constructObject(UndraIds.Objects.Syncer.TYPE_ID, UndraIds.Objects.Syncer.NEW, ByteArray(0))
            return ctx.adopt(handle, ::Syncer)
        }
    }
}
