// Generated by undra-bindgen from the Undra schema of `golden-stdlib` (schema hash 0x6b4638c4a5e34313). Do not edit.

package golden.stdlib

import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraReplyException
import dev.undra.runtime.UndraStore
import dev.undra.runtime.adapters.HttpError
import dev.undra.runtime.adapters.HttpRequest
import dev.undra.runtime.adapters.HttpResponse
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.Payloads.ReplyStatus
import dev.undra.runtime.wire.Timestamp
import dev.undra.runtime.wire.decodeAll
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Observes the `latest_response` query (cache key `latest`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
class LatestResponseQueryHandle private constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _data: MutableStateFlow<HttpResponse?> = signal(null)
    /** The latest successful result, if any. */
    val data: StateFlow<HttpResponse?> = _data.asStateFlow()
    private val _status: MutableStateFlow<QueryStatus> = signal(QueryStatus.IDLE)
    /** Where the query is in its fetch lifecycle. */
    val status: StateFlow<QueryStatus> = _status.asStateFlow()
    private val _error: MutableStateFlow<HttpError?> = signal(null)
    /** The error of the latest failed fetch, cleared by the next success. */
    val error: StateFlow<HttpError?> = _error.asStateFlow()
    private val _fetching: MutableStateFlow<Boolean> = signal(false)
    /** Whether a fetch is in flight (also true while refetching stale data). */
    val fetching: StateFlow<Boolean> = _fetching.asStateFlow()
    private val _updatedAt: MutableStateFlow<Timestamp?> = signal(null)
    /** When `data` was last updated. */
    val updatedAt: StateFlow<Timestamp?> = _updatedAt.asStateFlow()

    init {
        core.observe(handle, UInt.MAX_VALUE, true)
    }

    constructor(ctx: UndraCore = UndraCore.shared) : this(
        ctx,
        ctx.construct(UndraIds.Objects.LatestResponseQueryHandle.TYPE_ID, UndraIds.Objects.LatestResponseQueryHandle.NEW, ByteArray(0)),
    )

    /** Fetches again now, even if the data is fresh. */
    fun refetch() {
        this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.LatestResponseQueryHandle.REFETCH),
            UndraIds.Objects.LatestResponseQueryHandle.REFETCH,
            ByteArray(0),
        )
    }

    /** Marks the cached entry stale; it refetches while observed. */
    fun invalidate() {
        this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.LatestResponseQueryHandle.INVALIDATE),
            UndraIds.Objects.LatestResponseQueryHandle.INVALIDATE,
            ByteArray(0),
        )
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        when (signalId) {
            0u -> {
                if (op == ChangeOp.FULL) {
                    _data.value = codecOptionHttpResponse.decode(reader)
                    reader.finish()
                }
            }
            1u -> {
                if (op == ChangeOp.FULL) {
                    _status.value = QueryStatus.decode(reader)
                    reader.finish()
                }
            }
            2u -> {
                if (op == ChangeOp.FULL) {
                    _error.value = codecOptionHttpError.decode(reader)
                    reader.finish()
                }
            }
            3u -> {
                if (op == ChangeOp.FULL) {
                    _fetching.value = Codecs.bool.decode(reader)
                    reader.finish()
                }
            }
            4u -> {
                if (op == ChangeOp.FULL) {
                    _updatedAt.value = codecOptionTimestamp.decode(reader)
                    reader.finish()
                }
            }
            else -> Unit
        }
    }

    companion object {
        fun create(ctx: UndraCore = UndraCore.shared): LatestResponseQueryHandle {
            val handle = ctx.construct(UndraIds.Objects.LatestResponseQueryHandle.TYPE_ID, UndraIds.Objects.LatestResponseQueryHandle.NEW, ByteArray(0))
            return LatestResponseQueryHandle(ctx, handle)
        }
    }
}

/**
 * Runs the `retry` mutation.
 * @throws HttpError
 */
suspend fun retry(request: HttpRequest, ctx: UndraCore = UndraCore.shared): HttpResponse {
    val w = UndraWriter()
    HttpRequest.encode(w, request)
    val body = try {
        ctx.call(
            CallTarget.FreeFunction(UndraIds.Queries.RETRY),
            UndraIds.Queries.RETRY,
            w.toByteArray(),
        )
    } catch (e: UndraReplyException) {
        throw if (e.status == ReplyStatus.ERROR) HttpError.decodeAll(e.body) else e
    }
    return HttpResponse.decodeAll(body)
}

private val codecOptionHttpResponse = Codecs.option(HttpResponse)
private val codecOptionHttpError = Codecs.option(HttpError)
private val codecOptionTimestamp = Codecs.option(Codecs.timestamp)
