// Generated by undra-bindgen from the Undra schema of `golden-stdlib` (schema hash 0x6b4638c4a5e34313). Do not edit.

package golden.stdlib

import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraStore
import dev.undra.runtime.adapters.AppState
import dev.undra.runtime.adapters.HttpError
import dev.undra.runtime.adapters.HttpRequest
import dev.undra.runtime.adapters.HttpResponse
import dev.undra.runtime.adapters.NetKind
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.UndraReader
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Mirrors what the platform reports about the connection. */
class Link private constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _state: MutableStateFlow<AppState> = signal(AppState.ACTIVE)
    val state: StateFlow<AppState> = _state.asStateFlow()
    private val _kind: MutableStateFlow<NetKind> = signal(NetKind.WIFI)
    val kind: StateFlow<NetKind> = _kind.asStateFlow()
    private val _last: MutableStateFlow<HttpResponse?> = signal(null)
    val last: StateFlow<HttpResponse?> = _last.asStateFlow()
    private val _failure: MutableStateFlow<HttpError?> = signal(null)
    val failure: StateFlow<HttpError?> = _failure.asStateFlow()
    private val _pending: MutableStateFlow<List<HttpRequest>> = signal(emptyList())
    val pending: StateFlow<List<HttpRequest>> = _pending.asStateFlow()

    init {
        core.observe(handle, UInt.MAX_VALUE, true)
    }

    constructor(ctx: UndraCore = UndraCore.shared) : this(
        ctx,
        ctx.construct(UndraIds.Objects.Link.TYPE_ID, UndraIds.Objects.Link.NEW, ByteArray(0)),
    )

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        when (signalId) {
            0u -> {
                if (op == ChangeOp.FULL) {
                    _state.value = AppState.decode(reader)
                    reader.finish()
                }
            }
            1u -> {
                if (op == ChangeOp.FULL) {
                    _kind.value = NetKind.decode(reader)
                    reader.finish()
                }
            }
            2u -> {
                if (op == ChangeOp.FULL) {
                    _last.value = codecOptionHttpResponse.decode(reader)
                    reader.finish()
                }
            }
            3u -> {
                if (op == ChangeOp.FULL) {
                    _failure.value = codecOptionHttpError.decode(reader)
                    reader.finish()
                }
            }
            4u -> {
                if (op == ChangeOp.FULL) {
                    _pending.value = codecVecHttpRequest.decode(reader)
                    reader.finish()
                }
            }
            else -> Unit
        }
    }

    companion object {
        fun create(ctx: UndraCore = UndraCore.shared): Link {
            val handle = ctx.construct(UndraIds.Objects.Link.TYPE_ID, UndraIds.Objects.Link.NEW, ByteArray(0))
            return Link(ctx, handle)
        }
    }
}

private val codecOptionHttpResponse = Codecs.option(HttpResponse)
private val codecOptionHttpError = Codecs.option(HttpError)
private val codecVecHttpRequest = Codecs.vec(HttpRequest)
