// Generated by undra-bindgen from the Undra schema of `golden-generic-objects` (schema hash 0x9879017575e7dc8f). Do not edit.

package golden.generic_objects

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0x9879017575e7dc8fuL
    const val NAMESPACE: String = "golden_generic_objects"

    object Objects {
        object NoteCache {
            const val TYPE_ID: UInt = 0xdf3acbddu
            const val NEW: UInt = 0x5ad50895u
            const val PUT: UInt = 0x12bd60dau
            const val GET: UInt = 0x643c740bu
            const val ALL: UInt = 0xdcbe63f0u
        }
        object TodoCache {
            const val TYPE_ID: UInt = 0x8965f31du
            const val NEW: UInt = 0x10c55355u
            const val PUT: UInt = 0xcb26819au
            const val GET: UInt = 0x1a2cbecbu
            const val ALL: UInt = 0x92ad1bb0u
        }
        object NoteSelection {
            const val TYPE_ID: UInt = 0x5f5e349du
            const val NEW: UInt = 0xa0602cd5u
            const val TOGGLE: UInt = 0xce377229u
            const val CONTAINS: UInt = 0x70769efcu
            const val CLEAR: UInt = 0xb304c15eu
        }
        object TodoSelection {
            const val TYPE_ID: UInt = 0xd88b75ddu
            const val NEW: UInt = 0xfb065295u
            const val TOGGLE: UInt = 0x5a64c3e9u
            const val CONTAINS: UInt = 0xfb46e6bcu
            const val CLEAR: UInt = 0x1658621eu
        }
    }

    object Functions {
        const val OPEN_SELECTION_NOTE: UInt = 0x8969f86au
        const val OPEN_SELECTION_TODO: UInt = 0x8c8670d6u
        const val PAGE_OF_NOTE: UInt = 0x14e5aec0u
        const val PAGE_OF_TODO: UInt = 0xac0c8cf4u
        const val TICKED_NOTE: UInt = 0x20691623u
        const val TICKED_TODO: UInt = 0xd3c39063u
    }

    object Ports {}

    object Queries {}
}
