// Generated by undra-bindgen from the Undra schema of `golden-generic-objects` (schema hash 0x9879017575e7dc8f). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.generic_objects

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraObject
import dev.undra.runtime.reachabilityFence
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import kotlin.reflect.KClass

/** Keeps rows by id. */
class NoteCache internal constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    /**
     * Stores a row, replacing the one with its id.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun put(row: Note) {
        try {
            val w = UndraWriter()
            Note.encode(w, row)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.NoteCache.PUT),
                UndraIds.Objects.NoteCache.PUT,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "NoteCache.put")
        }
    }

    /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
    fun get(id: UInt): Note? {
        val w = UndraWriter()
        w.writeU32(id)
        try {
            val body = this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.NoteCache.GET),
                UndraIds.Objects.NoteCache.GET,
                w.toByteArray(),
            )
            return codecOptionNote.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    /**
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun all(): List<Note> {
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.NoteCache.ALL),
                UndraIds.Objects.NoteCache.ALL,
                ByteArray(0),
            )
            return codecVecNote.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        operator fun invoke(
            ctx: UndraCore = UndraGoldenGenericObjects.core,
        ): NoteCache = create(ctx)

        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraGoldenGenericObjects.core): NoteCache {
            val handle = ctx.constructObject(UndraIds.Objects.NoteCache.TYPE_ID, UndraIds.Objects.NoteCache.NEW, ByteArray(0))
            return ctx.adopt(handle, ::NoteCache)
        }
    }
}

/** Keeps rows by id. */
class TodoCache internal constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    /**
     * Stores a row, replacing the one with its id.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun put(row: Todo) {
        try {
            val w = UndraWriter()
            Todo.encode(w, row)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodoCache.PUT),
                UndraIds.Objects.TodoCache.PUT,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "TodoCache.put")
        }
    }

    /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
    fun get(id: UInt): Todo? {
        val w = UndraWriter()
        w.writeU32(id)
        try {
            val body = this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodoCache.GET),
                UndraIds.Objects.TodoCache.GET,
                w.toByteArray(),
            )
            return codecOptionTodo.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    /**
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun all(): List<Todo> {
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TodoCache.ALL),
                UndraIds.Objects.TodoCache.ALL,
                ByteArray(0),
            )
            return codecVecTodo.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        operator fun invoke(
            ctx: UndraCore = UndraGoldenGenericObjects.core,
        ): TodoCache = create(ctx)

        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraGoldenGenericObjects.core): TodoCache {
            val handle = ctx.constructObject(UndraIds.Objects.TodoCache.TYPE_ID, UndraIds.Objects.TodoCache.NEW, ByteArray(0))
            return ctx.adopt(handle, ::TodoCache)
        }
    }
}

/**
 * A fresh selection of rows.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
@JvmName("openSelectionNote")
fun openSelection(
    type: KClass<Note>,
    limit: UInt,
    ctx: UndraCore = UndraGoldenGenericObjects.core,
): NoteSelection {
    val w = UndraWriter()
    w.writeU32(limit)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.OPEN_SELECTION_NOTE),
            UndraIds.Functions.OPEN_SELECTION_NOTE,
            w.toByteArray(),
        )
        return ctx.adoptObject(body, ::NoteSelection)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}

/**
 * A fresh selection of rows.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
@JvmName("openSelectionTodo")
fun openSelection(
    type: KClass<Todo>,
    limit: UInt,
    ctx: UndraCore = UndraGoldenGenericObjects.core,
): TodoSelection {
    val w = UndraWriter()
    w.writeU32(limit)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.OPEN_SELECTION_TODO),
            UndraIds.Functions.OPEN_SELECTION_TODO,
            w.toByteArray(),
        )
        return ctx.adoptObject(body, ::TodoSelection)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}

/**
 * Wraps rows in a page.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
@JvmName("pageOfNote")
fun pageOf(rows: List<Note>, ctx: UndraCore = UndraGoldenGenericObjects.core): NotePage {
    val w = UndraWriter()
    codecVecNote.encode(w, rows)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.PAGE_OF_NOTE),
            UndraIds.Functions.PAGE_OF_NOTE,
            w.toByteArray(),
        )
        return NotePage.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}

/**
 * Wraps rows in a page.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
@JvmName("pageOfTodo")
fun pageOf(rows: List<Todo>, ctx: UndraCore = UndraGoldenGenericObjects.core): TodoPage {
    val w = UndraWriter()
    codecVecTodo.encode(w, rows)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.PAGE_OF_TODO),
            UndraIds.Functions.PAGE_OF_TODO,
            w.toByteArray(),
        )
        return TodoPage.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}

/**
 * How many rows the selection holds.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
@JvmName("tickedNote")
fun ticked(selection: NoteSelection, ctx: UndraCore = UndraGoldenGenericObjects.core): UInt {
    ctx.requireOwn(selection)
    val w = UndraWriter()
    w.writeI64(selection.handle)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.TICKED_NOTE),
            UndraIds.Functions.TICKED_NOTE,
            w.toByteArray(),
        )
        reachabilityFence(selection)
        return Codecs.u32.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}

/**
 * How many rows the selection holds.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
@JvmName("tickedTodo")
fun ticked(selection: TodoSelection, ctx: UndraCore = UndraGoldenGenericObjects.core): UInt {
    ctx.requireOwn(selection)
    val w = UndraWriter()
    w.writeI64(selection.handle)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.TICKED_TODO),
            UndraIds.Functions.TICKED_TODO,
            w.toByteArray(),
        )
        reachabilityFence(selection)
        return Codecs.u32.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}

private val codecOptionNote = Codecs.option(Note)
private val codecVecNote = Codecs.vec(Note)
private val codecOptionTodo = Codecs.option(Todo)
private val codecVecTodo = Codecs.vec(Todo)
