// Generated by undra-bindgen from the Undra schema of `golden-queries` (schema hash 0xbfc1afa630b0b63d). Do not edit.

import { UndraCore, UndraError, type AttachOptions, type LoadOptions, type Transport } from "@undra/runtime";
import { UndraIds } from "./ids.js";

/** The core `load` or `attach` gave this package, until it is closed. */
let loaded: UndraCore | null = null;
/** Set while `load` or `attach` is running, so a second one is refused. */
let starting = false;

function claim(): void {
  if (starting || (loaded !== null && !loaded.closed)) {
    throw new UndraError("state", "the core `golden_queries` is already loaded: close it (core.close()) before loading it again");
  }
  starting = true;
}

async function started(start: Promise<UndraCore>): Promise<UndraCore> {
  try {
    loaded = await start;
    return loaded;
  } finally {
    starting = false;
  }
}

/**
 * The core these bindings belong to, `golden_queries` (`[core] namespace` in undra.toml): `load` starts it,
 * and `core` is the core every generated class and function of this package uses unless it is given
 * another one.
 *
 * ```ts
 * await UndraGoldenQueries.load({ mode: "wasm-main", wasm: new URL("golden_queries.wasm", import.meta.url) });
 * ```
 */
export const UndraGoldenQueries = {
  /** The core's namespace: its wasm module is `golden_queries.wasm`, its native library `libgolden_queries`. */
  namespace: "golden_queries",
  /** The schema hash these bindings were generated for. */
  schemaHash: UndraIds.schemaHash,

  /**
   * Loads the core (`UndraCore.load` with this package's schema hash) and makes it `core`. Rejects with
   * `UndraSchemaMismatchError` when the core was built from another schema, and with `UndraError` while
   * this core is already loaded.
   */
  load(options: Omit<LoadOptions, "expectedSchemaHash">): Promise<UndraCore> {
    claim();
    return started(UndraCore.load({ ...options, expectedSchemaHash: UndraIds.schemaHash }));
  },

  /**
   * Attaches the core over a transport you provide (React Native's `NativeTransport`, a test double),
   * with this package's schema hash, and makes it `core`.
   */
  attach(transport: Transport, options: Omit<AttachOptions, "expectedSchemaHash"> = {}): Promise<UndraCore> {
    claim();
    return started(UndraCore.attach(transport, { ...options, expectedSchemaHash: UndraIds.schemaHash }));
  },

  /**
   * The loaded core, or, while none is loaded (or after it was closed), the closed placeholder
   * `UndraCore.unloaded`, whose calls reject with `UndraCallError.Unavailable`.
   */
  get core(): UndraCore {
    return loaded !== null && !loaded.closed ? loaded : UndraCore.unloaded;
  },
};
