// Generated by undra-bindgen from the Undra schema of `golden-queries` (schema hash 0xbfc1afa630b0b63d). Do not edit.

import {
  CallTarget,
  ChangeOp,
  Signal,
  type Timestamp,
  UndraCallError,
  UndraCore,
  UndraStore,
  UndraWriter,
  codecs,
  decodeValue,
} from "@undra/runtime";
import { type TodoError, TodoErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import {
  type Page,
  PageCodec,
  type QueryStatus,
  QueryStatusCodec,
  type Todo,
  TodoCodec,
} from "./types.js";

/**
 * Observes the `todo_by_id` query (cache key `todo:{id}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class TodoByIdQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<Todo | null> = new Signal<Todo | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<TodoError | null> = new Signal<TodoError | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(
    id: string,
    fresh: boolean,
    core: UndraCore = UndraCore.shared,
  ): Promise<TodoByIdQueryHandle> {
    const w = new UndraWriter();
    w.writeUuid(id);
    w.writeBool(fresh);
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.TodoByIdQueryHandle.typeId,
        UndraIds.Objects.TodoByIdQueryHandle.new,
        w.finish(),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = new TodoByIdQueryHandle(core, handle);
    await store._observeAll();
    return store;
  }

  /**
   * Fetches again now, even if the data is fresh.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async refetch(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TodoByIdQueryHandle.refetch,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "TodoByIdQueryHandle.refetch");
    }
  }

  /**
   * Marks the cached entry stale; it refetches while observed.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async invalidate(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TodoByIdQueryHandle.invalidate,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "TodoByIdQueryHandle.invalidate");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.data._set(decodeValue(optionTodo, value));
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.status._set(decodeValue(QueryStatusCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.error._set(decodeValue(optionTodoError, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.fetching._set(decodeValue(codecs.bool, value));
          }
          break;
        case 4:
          if (op === ChangeOp.FullValue) {
            this.updatedAt._set(decodeValue(optionTimestamp, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `TodoByIdQueryHandle.apply(signal: ${signalId})`);
    }
  }
}

/**
 * Observes the `todo_count` query (cache key `todo-count`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class TodoCountQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<number | null> = new Signal<number | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<string | null> = new Signal<string | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraCore.shared): Promise<TodoCountQueryHandle> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.TodoCountQueryHandle.typeId,
        UndraIds.Objects.TodoCountQueryHandle.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = new TodoCountQueryHandle(core, handle);
    await store._observeAll();
    return store;
  }

  /**
   * Fetches again now, even if the data is fresh.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async refetch(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TodoCountQueryHandle.refetch,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "TodoCountQueryHandle.refetch");
    }
  }

  /**
   * Marks the cached entry stale; it refetches while observed.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async invalidate(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TodoCountQueryHandle.invalidate,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "TodoCountQueryHandle.invalidate");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.data._set(decodeValue(optionU32, value));
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.status._set(decodeValue(QueryStatusCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.error._set(decodeValue(optionString, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.fetching._set(decodeValue(codecs.bool, value));
          }
          break;
        case 4:
          if (op === ChangeOp.FullValue) {
            this.updatedAt._set(decodeValue(optionTimestamp, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `TodoCountQueryHandle.apply(signal: ${signalId})`);
    }
  }
}

/**
 * Observes the `todos` query (cache key `todos:{page}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class TodosQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<Page | null> = new Signal<Page | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<TodoError | null> = new Signal<TodoError | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(page: number, core: UndraCore = UndraCore.shared): Promise<TodosQueryHandle> {
    const w = new UndraWriter();
    w.writeU32(page);
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.TodosQueryHandle.typeId,
        UndraIds.Objects.TodosQueryHandle.new,
        w.finish(),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = new TodosQueryHandle(core, handle);
    await store._observeAll();
    return store;
  }

  /**
   * Fetches again now, even if the data is fresh.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async refetch(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TodosQueryHandle.refetch,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "TodosQueryHandle.refetch");
    }
  }

  /**
   * Marks the cached entry stale; it refetches while observed.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async invalidate(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TodosQueryHandle.invalidate,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "TodosQueryHandle.invalidate");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.data._set(decodeValue(optionPage, value));
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.status._set(decodeValue(QueryStatusCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.error._set(decodeValue(optionTodoError, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.fetching._set(decodeValue(codecs.bool, value));
          }
          break;
        case 4:
          if (op === ChangeOp.FullValue) {
            this.updatedAt._set(decodeValue(optionTimestamp, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `TodosQueryHandle.apply(signal: ${signalId})`);
    }
  }
}

/**
 * Runs the `add_todo` mutation.
 * @throws {TodoError}
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
 */
export async function addTodo(
  title: string,
  core: UndraCore = UndraCore.shared,
  signal?: AbortSignal,
): Promise<Todo> {
  const w = new UndraWriter();
  w.writeStr(title);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Queries.addTodo,
      w.finish(),
      signal,
    );
    return decodeValue(TodoCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error, TodoErrorCodec);
  }
}

/**
 * Runs the `clear_todos` mutation.
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
 */
export async function clearTodos(
  core: UndraCore = UndraCore.shared,
  signal?: AbortSignal,
): Promise<void> {
  try {
    await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Queries.clearTodos,
      new Uint8Array(0),
      signal,
    );
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

const optionTodo = codecs.option(TodoCodec);
const optionTodoError = codecs.option(TodoErrorCodec);
const optionTimestamp = codecs.option(codecs.timestamp);
const optionU32 = codecs.option(codecs.u32);
const optionString = codecs.option(codecs.string);
const optionPage = codecs.option(PageCodec);
