// Generated by undra-bindgen from the Undra schema of `golden-queries` (schema hash 0xbfc1afa630b0b63d). Do not edit.

import {
  ALL_SIGNALS,
  CallTarget,
  ChangeOp,
  UndraCore,
  UndraStore,
  UndraWriter,
  Signal,
  type Timestamp,
  codecs,
  decodeValue,
} from "@undra/runtime";
import { TodoError, TodoErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import {
  type Page,
  PageCodec,
  type QueryStatus,
  QueryStatusCodec,
  type Todo,
  TodoCodec,
} from "./types.js";

/**
 * Observes the `todo_by_id` query (cache key `todo:{id}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class TodoByIdQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<Todo | null> = new Signal<Todo | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<TodoError | null> = new Signal<TodoError | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  static async create(
    id: string,
    fresh: boolean,
    core: UndraCore = UndraCore.shared,
  ): Promise<TodoByIdQueryHandle> {
    const w = new UndraWriter();
    w.writeUuid(id);
    w.writeBool(fresh);
    const handle = await core.construct(
      UndraIds.Objects.TodoByIdQueryHandle.typeId,
      UndraIds.Objects.TodoByIdQueryHandle.new,
      w.finish(),
    );
    const store = new TodoByIdQueryHandle(core, handle);
    await core.observe(handle, ALL_SIGNALS, true);
    return store;
  }

  /** Fetches again now, even if the data is fresh. */
  async refetch(): Promise<void> {
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.TodoByIdQueryHandle.refetch,
      new Uint8Array(0),
    );
  }

  /** Marks the cached entry stale; it refetches while observed. */
  async invalidate(): Promise<void> {
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.TodoByIdQueryHandle.invalidate,
      new Uint8Array(0),
    );
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    switch (signalId) {
      case 0:
        if (op === ChangeOp.FullValue) {
          this.data._set(decodeValue(optionTodo, value));
        }
        break;
      case 1:
        if (op === ChangeOp.FullValue) {
          this.status._set(decodeValue(QueryStatusCodec, value));
        }
        break;
      case 2:
        if (op === ChangeOp.FullValue) {
          this.error._set(decodeValue(optionTodoError, value));
        }
        break;
      case 3:
        if (op === ChangeOp.FullValue) {
          this.fetching._set(decodeValue(codecs.bool, value));
        }
        break;
      case 4:
        if (op === ChangeOp.FullValue) {
          this.updatedAt._set(decodeValue(optionTimestamp, value));
        }
        break;
      default:
        break;
    }
  }
}

/**
 * Observes the `todo_count` query (cache key `todo-count`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class TodoCountQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<number | null> = new Signal<number | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<string | null> = new Signal<string | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  static async create(core: UndraCore = UndraCore.shared): Promise<TodoCountQueryHandle> {
    const handle = await core.construct(
      UndraIds.Objects.TodoCountQueryHandle.typeId,
      UndraIds.Objects.TodoCountQueryHandle.new,
      new Uint8Array(0),
    );
    const store = new TodoCountQueryHandle(core, handle);
    await core.observe(handle, ALL_SIGNALS, true);
    return store;
  }

  /** Fetches again now, even if the data is fresh. */
  async refetch(): Promise<void> {
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.TodoCountQueryHandle.refetch,
      new Uint8Array(0),
    );
  }

  /** Marks the cached entry stale; it refetches while observed. */
  async invalidate(): Promise<void> {
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.TodoCountQueryHandle.invalidate,
      new Uint8Array(0),
    );
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    switch (signalId) {
      case 0:
        if (op === ChangeOp.FullValue) {
          this.data._set(decodeValue(optionU32, value));
        }
        break;
      case 1:
        if (op === ChangeOp.FullValue) {
          this.status._set(decodeValue(QueryStatusCodec, value));
        }
        break;
      case 2:
        if (op === ChangeOp.FullValue) {
          this.error._set(decodeValue(optionString, value));
        }
        break;
      case 3:
        if (op === ChangeOp.FullValue) {
          this.fetching._set(decodeValue(codecs.bool, value));
        }
        break;
      case 4:
        if (op === ChangeOp.FullValue) {
          this.updatedAt._set(decodeValue(optionTimestamp, value));
        }
        break;
      default:
        break;
    }
  }
}

/**
 * Observes the `todos` query (cache key `todos:{page}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class TodosQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<Page | null> = new Signal<Page | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<TodoError | null> = new Signal<TodoError | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  static async create(page: number, core: UndraCore = UndraCore.shared): Promise<TodosQueryHandle> {
    const w = new UndraWriter();
    w.writeU32(page);
    const handle = await core.construct(
      UndraIds.Objects.TodosQueryHandle.typeId,
      UndraIds.Objects.TodosQueryHandle.new,
      w.finish(),
    );
    const store = new TodosQueryHandle(core, handle);
    await core.observe(handle, ALL_SIGNALS, true);
    return store;
  }

  /** Fetches again now, even if the data is fresh. */
  async refetch(): Promise<void> {
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.TodosQueryHandle.refetch,
      new Uint8Array(0),
    );
  }

  /** Marks the cached entry stale; it refetches while observed. */
  async invalidate(): Promise<void> {
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.TodosQueryHandle.invalidate,
      new Uint8Array(0),
    );
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    switch (signalId) {
      case 0:
        if (op === ChangeOp.FullValue) {
          this.data._set(decodeValue(optionPage, value));
        }
        break;
      case 1:
        if (op === ChangeOp.FullValue) {
          this.status._set(decodeValue(QueryStatusCodec, value));
        }
        break;
      case 2:
        if (op === ChangeOp.FullValue) {
          this.error._set(decodeValue(optionTodoError, value));
        }
        break;
      case 3:
        if (op === ChangeOp.FullValue) {
          this.fetching._set(decodeValue(codecs.bool, value));
        }
        break;
      case 4:
        if (op === ChangeOp.FullValue) {
          this.updatedAt._set(decodeValue(optionTimestamp, value));
        }
        break;
      default:
        break;
    }
  }
}

/**
 * Runs the `add_todo` mutation.
 * @throws {TodoError}
 */
export async function addTodo(
  title: string,
  core: UndraCore = UndraCore.shared,
  signal?: AbortSignal,
): Promise<Todo> {
  const w = new UndraWriter();
  w.writeStr(title);
  let body: Uint8Array;
  try {
    body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Queries.addTodo,
      w.finish(),
      signal,
    );
  } catch (error) {
    throw TodoError.fromReply(error);
  }
  return decodeValue(TodoCodec, body);
}

/** Runs the `clear_todos` mutation. */
export async function clearTodos(
  core: UndraCore = UndraCore.shared,
  signal?: AbortSignal,
): Promise<void> {
  await core.call(
    { target: CallTarget.FreeFunction },
    UndraIds.Queries.clearTodos,
    new Uint8Array(0),
    signal,
  );
}

const optionTodo = codecs.option(TodoCodec);
const optionTodoError = codecs.option(TodoErrorCodec);
const optionTimestamp = codecs.option(codecs.timestamp);
const optionU32 = codecs.option(codecs.u32);
const optionString = codecs.option(codecs.string);
const optionPage = codecs.option(PageCodec);
