// Generated by undra-bindgen from the Undra schema of `golden-generics` (schema hash 0xa08c3e607ebcebbe). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.generics

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0xa08c3e607ebcebbeuL
    const val NAMESPACE: String = "golden_generics"

    object Objects {
        object Browser {
            const val TYPE_ID: UInt = 0x8df5852fu
            const val NEW: UInt = 0xfd604863u
            const val LOAD_TODOS: UInt = 0x42b44bedu
            const val LOAD_USERS: UInt = 0x2ce170dcu
            const val SELECT: UInt = 0x65955c83u
        }
    }

    object Functions {
        const val FIRST_PAGE: UInt = 0xa8d4baa5u
    }

    object Ports {}

    object Queries {}
}
