// Generated by undra-bindgen from the Undra schema of `golden-generics` (schema hash 0xa08c3e607ebcebbe). Do not edit.

package golden.generics

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.decodeAll

/** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
fun firstPage(ctx: UndraCore = UndraGoldenGenerics.core): TodoPage {
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.FIRST_PAGE),
            UndraIds.Functions.FIRST_PAGE,
            ByteArray(0),
        )
        return TodoPage.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}
