// Generated by undra-bindgen from the Undra schema of `golden-generics` (schema hash 0xa08c3e607ebcebbe). Do not edit.

package golden.generics

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraStore
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Pages through todos and users. */
class Browser internal constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _todos: MutableStateFlow<TodoPage> = signal(TodoPage(items = emptyList(), next = null))
    val todos: StateFlow<TodoPage> = _todos.asStateFlow()
    private val _users: MutableStateFlow<UserPage> = signal(UserPage(items = emptyList(), next = null))
    val users: StateFlow<UserPage> = _users.asStateFlow()
    private val _selected: MutableStateFlow<LoadableTodo> = signal(LoadableTodo.Loading)
    val selected: StateFlow<LoadableTodo> = _selected.asStateFlow()
    private val _owner: MutableStateFlow<LoadableUser> = signal(LoadableUser.Loading)
    val owner: StateFlow<LoadableUser> = _owner.asStateFlow()

    /**
     * @throws BrowseError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun loadTodos(cursor: String?): TodoPage {
        val w = UndraWriter()
        codecOptionString.encode(w, cursor)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Browser.LOAD_TODOS),
                UndraIds.Objects.Browser.LOAD_TODOS,
                w.toByteArray(),
            )
            return TodoPage.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, BrowseError)
        }
    }

    /**
     * @throws BrowseError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun loadUsers(cursor: String?): UserPage {
        val w = UndraWriter()
        codecOptionString.encode(w, cursor)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Browser.LOAD_USERS),
                UndraIds.Objects.Browser.LOAD_USERS,
                w.toByteArray(),
            )
            return UserPage.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, BrowseError)
        }
    }

    /** A failure is logged and passed to `LoadOptions.onError`; the method does not throw. */
    fun select(todo: LoadableTodo) {
        try {
            val w = UndraWriter()
            LoadableTodo.encode(w, todo)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Browser.SELECT),
                UndraIds.Objects.Browser.SELECT,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "Browser.select")
        }
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        try {
            when (signalId) {
                0u -> {
                    if (op == ChangeOp.FULL) {
                        val value = TodoPage.decode(reader)
                        reader.finish()
                        _todos.value = value
                    }
                }
                1u -> {
                    if (op == ChangeOp.FULL) {
                        val value = UserPage.decode(reader)
                        reader.finish()
                        _users.value = value
                    }
                }
                2u -> {
                    if (op == ChangeOp.FULL) {
                        val value = LoadableTodo.decode(reader)
                        reader.finish()
                        _selected.value = value
                    }
                }
                3u -> {
                    if (op == ChangeOp.FULL) {
                        val value = LoadableUser.decode(reader)
                        reader.finish()
                        _owner.value = value
                    }
                }
                else -> Unit
            }
        } catch (e: Exception) {
            core.report(e, "Browser.apply(signal: $signalId)")
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        operator fun invoke(ctx: UndraCore = UndraGoldenGenerics.core): Browser = create(ctx)

        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraGoldenGenerics.core): Browser {
            val handle = ctx.constructObject(UndraIds.Objects.Browser.TYPE_ID, UndraIds.Objects.Browser.NEW, ByteArray(0))
            return ctx.adopt(handle, ::Browser)
        }
    }
}

private val codecOptionString = Codecs.option(Codecs.string)
