// Generated by undra-bindgen from the Undra schema of `golden-generics` (schema hash 0xa08c3e607ebcebbe). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.generics

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

data class Todo(
    val id: UInt,
    val title: String,
) : UndraRecord {
    companion object : UndraCodec<Todo> {
        override fun encode(w: UndraWriter, v: Todo) {
            w.writeU32(v.id)
            w.writeStr(v.title)
        }

        override fun decode(r: UndraReader): Todo = Todo(id = r.readU32(), title = r.readStr())
    }
}

/** A page of todos: `Page<Todo>`. */
data class TodoPage(
    val items: List<Todo>,
    val next: String?,
) : UndraRecord {
    companion object : UndraCodec<TodoPage> {
        override fun encode(w: UndraWriter, v: TodoPage) {
            codecVecTodo.encode(w, v.items)
            codecOptionString.encode(w, v.next)
        }

        override fun decode(r: UndraReader): TodoPage = TodoPage(
            items = codecVecTodo.decode(r),
            next = codecOptionString.decode(r),
        )
    }
}

data class User(
    val id: UInt,
    val name: String,
) : UndraRecord {
    companion object : UndraCodec<User> {
        override fun encode(w: UndraWriter, v: User) {
            w.writeU32(v.id)
            w.writeStr(v.name)
        }

        override fun decode(r: UndraReader): User = User(id = r.readU32(), name = r.readStr())
    }
}

/** A page of users: `Page<User>`. */
data class UserPage(
    val items: List<User>,
    val next: String?,
) : UndraRecord {
    companion object : UndraCodec<UserPage> {
        override fun encode(w: UndraWriter, v: UserPage) {
            codecVecUser.encode(w, v.items)
            codecOptionString.encode(w, v.next)
        }

        override fun decode(r: UndraReader): UserPage = UserPage(
            items = codecVecUser.decode(r),
            next = codecOptionString.decode(r),
        )
    }
}

/** A todo on its way: `Loadable<Todo>`. */
sealed interface LoadableTodo : UndraEnum {
    data object Loading : LoadableTodo
    data class Loaded(val value: Todo) : LoadableTodo
    data class Failed(val value: String) : LoadableTodo

    companion object : UndraCodec<LoadableTodo> {
        override fun encode(w: UndraWriter, v: LoadableTodo) {
            when (v) {
                Loading -> w.writeU16(0u)
                is Loaded -> {
                    w.writeU16(1u)
                    Todo.encode(w, v.value)
                }
                is Failed -> {
                    w.writeU16(2u)
                    w.writeStr(v.value)
                }
            }
        }

        override fun decode(r: UndraReader): LoadableTodo {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Loading
                1 -> Loaded(value = Todo.decode(r))
                2 -> Failed(value = r.readStr())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "LoadableTodo")
            }
        }
    }
}

/** A user on its way: `Loadable<User>`. */
sealed interface LoadableUser : UndraEnum {
    data object Loading : LoadableUser
    data class Loaded(val value: User) : LoadableUser
    data class Failed(val value: String) : LoadableUser

    companion object : UndraCodec<LoadableUser> {
        override fun encode(w: UndraWriter, v: LoadableUser) {
            when (v) {
                Loading -> w.writeU16(0u)
                is Loaded -> {
                    w.writeU16(1u)
                    User.encode(w, v.value)
                }
                is Failed -> {
                    w.writeU16(2u)
                    w.writeStr(v.value)
                }
            }
        }

        override fun decode(r: UndraReader): LoadableUser {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Loading
                1 -> Loaded(value = User.decode(r))
                2 -> Failed(value = r.readStr())
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "LoadableUser")
            }
        }
    }
}

private val codecVecTodo = Codecs.vec(Todo)
private val codecOptionString = Codecs.option(Codecs.string)
private val codecVecUser = Codecs.vec(User)
