// Generated by keel-bindgen from the Keel schema of `golden-stdlib` (schema hash 0x6b4638c4a5e34313). Do not edit.

import {
  HttpError,
  HttpErrorCodec,
  type HttpRequest,
  HttpRequestCodec,
  type HttpResponse,
  HttpResponseCodec,
  type KeelPort,
  KeelPortError,
  KeelReader,
  type PortImpl,
  encodeValue,
} from "@keel/runtime";
import { KeelIds } from "./ids.js";

/** The platform uploads a request in the background. */
export interface Uploader extends KeelPort {
  /** @throws {HttpError} */
  upload(request: HttpRequest): Promise<HttpResponse>;
}

/** Adapts an implementation of `Uploader` to `KeelCore.registerPort(KeelIds.Ports.Uploader.portId, ..)`. */
export function uploaderPortImpl(impl: Uploader): PortImpl {
  return {
    sync: false,
    methods: {
      [KeelIds.Ports.Uploader.upload]: async (args) => {
        const r = new KeelReader(args);
        const request = HttpRequestCodec.decode(r);
        r.finish();
        try {
          return encodeValue(HttpResponseCodec, await impl.upload(request));
        } catch (error) {
          if (error instanceof HttpError) {
            throw new KeelPortError(encodeValue(HttpErrorCodec, error));
          }
          throw error;
        }
      },
    },
  };
}
