// Generated by undra-bindgen from the Undra schema of `golden-lazy` (schema hash 0xd202b600b0fecfff). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.lazy

import dev.undra.runtime.UndraException
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

sealed class LibraryError(message: String) : UndraException(message) {
    data object Missing : LibraryError("missing")

    companion object : UndraCodec<LibraryError> {
        override fun encode(w: UndraWriter, v: LibraryError) {
            when (v) {
                Missing -> w.writeU16(0u)
            }
        }

        override fun decode(r: UndraReader): LibraryError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Missing
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "LibraryError")
            }
        }
    }
}
