// Generated by undra-bindgen from the Undra schema of `golden-lazy` (schema hash 0x1b2e19aa5e8a1bef). Do not edit.

package golden.lazy

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0x1b2e19aa5e8a1befuL
    const val NAMESPACE: String = "golden_lazy"

    object Objects {
        object Library {
            const val TYPE_ID: UInt = 0xa8532270u
            const val NEW: UInt = 0xf94159c4u
            const val ADD: UInt = 0x087d1501u
            const val CLEAR: UInt = 0xc4554183u
        }
    }

    object Functions {}

    object Ports {}

    object Queries {}
}
