// Generated by undra-bindgen from the Undra schema of `golden-lazy` (schema hash 0x1b2e19aa5e8a1bef). Do not edit.

package golden.lazy

import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter

/** One book of the library. */
data class Book(
    val id: ULong,
    val title: String,
    val year: UShort,
) : UndraRecord {
    companion object : UndraCodec<Book> {
        override fun encode(w: UndraWriter, v: Book) {
            w.writeU64(v.id)
            w.writeStr(v.title)
            w.writeU16(v.year)
        }

        override fun decode(r: UndraReader): Book = Book(
            id = r.readU64(),
            title = r.readStr(),
            year = r.readU16(),
        )
    }
}

data class Shelf(
    val name: String,
    val count: UInt,
) : UndraRecord {
    companion object : UndraCodec<Shelf> {
        override fun encode(w: UndraWriter, v: Shelf) {
            w.writeStr(v.name)
            w.writeU32(v.count)
        }

        override fun decode(r: UndraReader): Shelf = Shelf(name = r.readStr(), count = r.readU32())
    }
}
