// Generated by keel-bindgen from the Keel schema of `golden-objects` (schema hash 0x0d92b39c89f299e1). Do not edit.

import {
  type Codec,
  KeelError,
  KeelReplyError,
  ReplyStatus,
  WireError,
  decodeValue,
} from "@keel/runtime";

export type CalcErrorKind = "overflow" | "divideByZero";

export abstract class CalcError extends KeelError {
  declare readonly kind: CalcErrorKind;

  /** The typed error a failed call carries; any other failure is returned unchanged. */
  static fromReply(error: unknown): unknown {
    if (error instanceof KeelReplyError && error.status === ReplyStatus.Error) {
      return decodeValue(CalcErrorCodec, error.body);
    }
    return error;
  }
}

export namespace CalcError {
  export class Overflow extends CalcError {
    declare readonly kind: "overflow";

    constructor() {
      super("overflow", "overflow");
    }
  }

  export class DivideByZero extends CalcError {
    declare readonly kind: "divideByZero";

    constructor() {
      super("divideByZero", "divide by zero");
    }
  }
}

export const CalcErrorCodec: Codec<CalcError> = {
  encode(w, v) {
    if (v instanceof CalcError.Overflow) {
      w.writeU16(0);
    } else if (v instanceof CalcError.DivideByZero) {
      w.writeU16(1);
    } else {
      throw new TypeError(`unknown CalcError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new CalcError.Overflow();
      case 1:
        return new CalcError.DivideByZero();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "CalcError" });
    }
  },
};
