//! Generated code says what it is (ADR-062): every generated file declares its origin, and the
//! `.gitattributes` the CLI writes into each tree is the one the golden holds.
//!
//! `UPDATE_GOLDEN=1 cargo test -p undra-bindgen --test provenance` rewrites the goldens in
//! `tests/golden/provenance/`.

mod common;

use std::fs;
use std::path::PathBuf;

use undra_bindgen::{GeneratedFile, provenance};
use undra_meta::Schema;

fn golden(name: &str) -> PathBuf {
    common::manifest_dir()
        .join("tests/golden/provenance")
        .join(name)
}

fn updating() -> bool {
    std::env::var("UPDATE_GOLDEN").is_ok_and(|v| v == "1")
}

/// Compares `actual` with the golden `name`, or writes it with `UPDATE_GOLDEN=1`.
fn check_golden(name: &str, actual: &str) {
    let path = golden(name);
    if updating() {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, actual).unwrap();
        return;
    }
    let expected = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("{}: {e}; run with UPDATE_GOLDEN=1", path.display()));
    assert_eq!(
        actual, expected,
        "{name} differs from its golden; UPDATE_GOLDEN=1 cargo test -p undra-bindgen --test provenance after reviewing"
    );
}

/// The three trees of a case: `(tree, files)`.
fn trees(case: &str) -> (Schema, Vec<(&'static str, Vec<GeneratedFile>)>) {
    let schema = common::case(case);
    let generator = common::generator_for(case, &schema);
    let trees = vec![
        ("swift", generator.swift(&schema).unwrap()),
        ("kotlin", generator.kotlin(&schema).unwrap()),
        ("ts", generator.typescript(&schema).unwrap()),
    ];
    (schema, trees)
}

/// The line of `file` that says what it is: its first line, or for `package.json` (which has no
/// comments) its `"//"` member.
fn header_of(file: &GeneratedFile) -> String {
    if file.path == "package.json" {
        let json: serde_json::Value = serde_json::from_str(&file.contents).unwrap();
        let said = json["//"]
            .as_str()
            .expect("package.json has a \"//\" member");
        return format!("\"//\": {said}");
    }
    file.contents.lines().next().unwrap_or_default().to_owned()
}

#[test]
fn every_generated_file_declares_its_origin() {
    for case in ["full", "stores", "ports", "callbacks"] {
        let (schema, trees) = trees(case);
        let sentence = provenance::sentence(&schema.crate_name, schema.hash());
        for (tree, files) in &trees {
            for file in files {
                let header = header_of(file);
                let what = format!("{case}/{tree}/{}", file.path);
                let source_or_tsconfig = [".swift", ".kt", ".ts"]
                    .iter()
                    .any(|ext| file.path.ends_with(ext))
                    || file.path == "tsconfig.json";
                if source_or_tsconfig {
                    // The sentence with the schema hash, as a line comment, on the first line.
                    assert_eq!(header, format!("// {sentence}"), "{what}");
                } else if file.path == "package.json" {
                    assert_eq!(header, format!("\"//\": {sentence}"), "{what}");
                } else {
                    // The files that do not depend on the schema (the C entry, the module map, the
                    // R8 rules) say so without a hash: a hash would move on every API change and
                    // mean nothing for them.
                    let top: String = file.contents.lines().take(3).collect::<Vec<_>>().join(" ");
                    assert!(
                        top.to_lowercase().contains("generated by undra")
                            && top.to_lowercase().contains("do not edit"),
                        "{what} does not say it is generated: {top}"
                    );
                }
            }
        }
    }
}

#[test]
fn package_json_and_tsconfig_stay_valid_for_their_tools() {
    let (schema, trees) = trees("stores");
    let (_, ts) = trees.iter().find(|(tree, _)| *tree == "ts").unwrap();
    let get = |path: &str| ts.iter().find(|f| f.path == path).unwrap();
    // npm reads package.json as strict JSON: the header is a member, and the rest is as it was.
    let package: serde_json::Value = serde_json::from_str(&get("package.json").contents).unwrap();
    assert_eq!(
        package["//"],
        provenance::sentence(&schema.crate_name, schema.hash())
    );
    assert_eq!(package["type"], "module");
    assert!(package["name"].as_str().is_some());
    // tsc reads tsconfig.json as JSONC: with its comment line removed it is strict JSON again.
    let tsconfig = &get("tsconfig.json").contents;
    let without_comment: String = tsconfig
        .lines()
        .filter(|l| !l.starts_with("//"))
        .collect::<Vec<_>>()
        .join("\n");
    let parsed: serde_json::Value = serde_json::from_str(&without_comment).unwrap();
    assert_eq!(parsed["compilerOptions"]["strict"], true);
}

/// The first line of every file of the `stores` case, per tree: the golden of the header.
#[test]
fn the_headers_are_locked() {
    let (_, trees) = trees("stores");
    let mut listing = String::new();
    for (tree, files) in &trees {
        for file in files {
            listing.push_str(&format!("{tree}/{}: {}\n", file.path, header_of(file)));
        }
    }
    check_golden("headers.txt", &listing);
}

#[test]
fn the_gitattributes_is_locked() {
    check_golden("gitattributes.txt", provenance::GITATTRIBUTES);
}
