// Generated by undra-bindgen from the Undra schema of `golden-polling` (schema hash 0xd1471391a5bc5da2). Do not edit.

import { type Codec, UndraError, WireError } from "@undra/runtime";

export type MarketErrorKind = "offline";

export abstract class MarketError extends UndraError {
  declare readonly kind: MarketErrorKind;
}

export namespace MarketError {
  export class Offline extends MarketError {
    declare readonly kind: "offline";

    constructor() {
      super("offline", "offline");
    }
  }
}

export const MarketErrorCodec: Codec<MarketError> = {
  encode(w, v) {
    if (v instanceof MarketError.Offline) {
      w.writeU16(0);
    } else {
      throw new TypeError(`unknown MarketError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new MarketError.Offline();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "MarketError" });
    }
  },
};
