// Generated by undra-bindgen from the Undra schema of `golden-polling` (schema hash 0xd1471391a5bc5da2). Do not edit.

import {
  CallTarget,
  ChangeOp,
  type Duration,
  Signal,
  type Timestamp,
  UndraCallError,
  UndraCore,
  UndraStore,
  UndraWriter,
  codecs,
  decodeValue,
} from "@undra/runtime";
import { UndraGoldenPolling } from "./core.js";
import { type MarketError, MarketErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import { type QueryStatus, QueryStatusCodec, type Quote, QuoteCodec } from "./types.js";

/**
 * Observes the `headlines` query (cache key `headlines`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class HeadlinesQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<string[] | null> = new Signal<string[] | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<MarketError | null> = new Signal<MarketError | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint, args: Uint8Array) {
    super(core, handle, {
      recreate: {
        typeId: UndraIds.Objects.HeadlinesQueryHandle.typeId,
        methodId: UndraIds.Objects.HeadlinesQueryHandle.new,
        args,
      },
    });
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraGoldenPolling.core): Promise<HeadlinesQueryHandle> {
    const args = new Uint8Array(0);
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.HeadlinesQueryHandle.typeId,
        UndraIds.Objects.HeadlinesQueryHandle.new,
        args,
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = new HeadlinesQueryHandle(core, handle, args);
    await store._observeAll();
    return store;
  }

  /**
   * Fetches again now, even if the data is fresh.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async refetch(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.HeadlinesQueryHandle.refetch,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "HeadlinesQueryHandle.refetch");
    }
  }

  /**
   * Marks the cached entry stale; it refetches while observed.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async invalidate(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.HeadlinesQueryHandle.invalidate,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "HeadlinesQueryHandle.invalidate");
    }
  }

  /**
   * Overrides how often the query polls while this handle observes it, counted from the end of a fetch.
   * The entry polls at the smallest interval among its observers; no interval clears this handle's override.
   * An interval below 1 second or above 7 days is clamped to that range.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async setPollInterval(ms: Duration | null): Promise<void> {
    try {
      const w = new UndraWriter();
      optionDuration.encode(w, ms);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.HeadlinesQueryHandle.setPollInterval,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "HeadlinesQueryHandle.setPollInterval");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.data._set(decodeValue(optionVecString, value));
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.status._set(decodeValue(QueryStatusCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.error._set(decodeValue(optionMarketError, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.fetching._set(decodeValue(codecs.bool, value));
          }
          break;
        case 4:
          if (op === ChangeOp.FullValue) {
            this.updatedAt._set(decodeValue(optionTimestamp, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `HeadlinesQueryHandle.apply(signal: ${signalId})`);
    }
  }
}

/**
 * Observes the `status` query (cache key `status`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class StatusQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<boolean | null> = new Signal<boolean | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<MarketError | null> = new Signal<MarketError | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint, args: Uint8Array) {
    super(core, handle, {
      recreate: {
        typeId: UndraIds.Objects.StatusQueryHandle.typeId,
        methodId: UndraIds.Objects.StatusQueryHandle.new,
        args,
      },
    });
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraGoldenPolling.core): Promise<StatusQueryHandle> {
    const args = new Uint8Array(0);
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.StatusQueryHandle.typeId,
        UndraIds.Objects.StatusQueryHandle.new,
        args,
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = new StatusQueryHandle(core, handle, args);
    await store._observeAll();
    return store;
  }

  /**
   * Fetches again now, even if the data is fresh.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async refetch(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.StatusQueryHandle.refetch,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "StatusQueryHandle.refetch");
    }
  }

  /**
   * Marks the cached entry stale; it refetches while observed.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async invalidate(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.StatusQueryHandle.invalidate,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "StatusQueryHandle.invalidate");
    }
  }

  /**
   * Overrides how often the query polls while this handle observes it, counted from the end of a fetch.
   * The entry polls at the smallest interval among its observers; no interval clears this handle's override.
   * An interval below 1 second or above 7 days is clamped to that range.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async setPollInterval(ms: Duration | null): Promise<void> {
    try {
      const w = new UndraWriter();
      optionDuration.encode(w, ms);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.StatusQueryHandle.setPollInterval,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "StatusQueryHandle.setPollInterval");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.data._set(decodeValue(optionBool, value));
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.status._set(decodeValue(QueryStatusCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.error._set(decodeValue(optionMarketError, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.fetching._set(decodeValue(codecs.bool, value));
          }
          break;
        case 4:
          if (op === ChangeOp.FullValue) {
            this.updatedAt._set(decodeValue(optionTimestamp, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `StatusQueryHandle.apply(signal: ${signalId})`);
    }
  }
}

/**
 * Observes the `ticker` query (cache key `ticker/{symbol}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
export class TickerQueryHandle extends UndraStore {
  /** The latest successful result, if any. */
  readonly data: Signal<Quote | null> = new Signal<Quote | null>(null);
  /** Where the query is in its fetch lifecycle. */
  readonly status: Signal<QueryStatus> = new Signal<QueryStatus>("idle");
  /** The error of the latest failed fetch, cleared by the next success. */
  readonly error: Signal<MarketError | null> = new Signal<MarketError | null>(null);
  /** Whether a fetch is in flight (also true while refetching stale data). */
  readonly fetching: Signal<boolean> = new Signal<boolean>(false);
  /** When `data` was last updated. */
  readonly updatedAt: Signal<Timestamp | null> = new Signal<Timestamp | null>(null);

  private constructor(core: UndraCore, handle: bigint, args: Uint8Array) {
    super(core, handle, {
      recreate: {
        typeId: UndraIds.Objects.TickerQueryHandle.typeId,
        methodId: UndraIds.Objects.TickerQueryHandle.new,
        args,
      },
    });
    this._signals = [this.data, this.status, this.error, this.fetching, this.updatedAt];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(
    symbol: string,
    core: UndraCore = UndraGoldenPolling.core,
  ): Promise<TickerQueryHandle> {
    const w = new UndraWriter();
    w.writeStr(symbol);
    const args = w.finish();
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.TickerQueryHandle.typeId,
        UndraIds.Objects.TickerQueryHandle.new,
        args,
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = new TickerQueryHandle(core, handle, args);
    await store._observeAll();
    return store;
  }

  /**
   * Fetches again now, even if the data is fresh.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async refetch(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TickerQueryHandle.refetch,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "TickerQueryHandle.refetch");
    }
  }

  /**
   * Marks the cached entry stale; it refetches while observed.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async invalidate(): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TickerQueryHandle.invalidate,
        new Uint8Array(0),
      );
    } catch (error) {
      this.core.report(error, "TickerQueryHandle.invalidate");
    }
  }

  /**
   * Overrides how often the query polls while this handle observes it, counted from the end of a fetch.
   * The entry polls at the smallest interval among its observers; no interval clears this handle's override.
   * An interval below 1 second or above 7 days is clamped to that range.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async setPollInterval(ms: Duration | null): Promise<void> {
    try {
      const w = new UndraWriter();
      optionDuration.encode(w, ms);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.TickerQueryHandle.setPollInterval,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "TickerQueryHandle.setPollInterval");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.data._set(decodeValue(optionQuote, value));
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.status._set(decodeValue(QueryStatusCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.error._set(decodeValue(optionMarketError, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.fetching._set(decodeValue(codecs.bool, value));
          }
          break;
        case 4:
          if (op === ChangeOp.FullValue) {
            this.updatedAt._set(decodeValue(optionTimestamp, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `TickerQueryHandle.apply(signal: ${signalId})`);
    }
  }
}

/**
 * Runs the `buy` mutation.
 * @throws {MarketError}
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
 */
export async function buy(
  symbol: string,
  core: UndraCore = UndraGoldenPolling.core,
  signal?: AbortSignal,
): Promise<Quote> {
  const w = new UndraWriter();
  w.writeStr(symbol);
  try {
    const body = await core.call(
      { target: CallTarget.FreeFunction },
      UndraIds.Queries.buy,
      w.finish(),
      signal,
    );
    return decodeValue(QuoteCodec, body);
  } catch (error) {
    throw UndraCallError.mapped(error, MarketErrorCodec);
  }
}

const optionDuration = codecs.option(codecs.duration);
const vecString = codecs.vec(codecs.string);
const optionVecString = codecs.option(vecString);
const optionMarketError = codecs.option(MarketErrorCodec);
const optionTimestamp = codecs.option(codecs.timestamp);
const optionBool = codecs.option(codecs.bool);
const optionQuote = codecs.option(QuoteCodec);
