// Generated by undra-bindgen from the Undra schema of `golden-generic-functions` (schema hash 0x032c4563a078af57). Do not edit.

package golden.generic_functions

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0x032c4563a078af57uL
    const val NAMESPACE: String = "golden_generic_functions"

    object Objects {
        object Library {
            const val TYPE_ID: UInt = 0xa8532270u
            const val NEW: UInt = 0xf94159c4u
            const val PINNED_TODO: UInt = 0x7cccf94au
            const val PINNED_NOTE: UInt = 0x30f1b50eu
            const val REMEMBER_TODO: UInt = 0xb5b214ffu
            const val REMEMBER_NOTE: UInt = 0xebc347dfu
            const val COUNT: UInt = 0x4503ed51u
        }
        object Shelf {
            const val TYPE_ID: UInt = 0xb01959e3u
            const val NEW: UInt = 0x4e9d4957u
            const val TIDY_TODO: UInt = 0x3dc411ddu
            const val TIDY_NOTE: UInt = 0x3719433du
        }
    }

    object Functions {
        const val COUNT_ROWS: UInt = 0x07ff8318u
        const val DRAFT_NOTE: UInt = 0x1ee40222u
        const val DRAFT_TODO: UInt = 0x0c13e0eeu
        const val FORGET_NOTE: UInt = 0x48bc78bau
        const val FORGET_TODO: UInt = 0xf3e14766u
        const val LOAD_NOTE: UInt = 0xc1b32b37u
        const val LOAD_TODO: UInt = 0x76309337u
        const val MAKE_NOTE: UInt = 0x94161359u
        const val MAKE_TODO: UInt = 0xfa084e19u
        const val NEWEST_NOTE: UInt = 0x4835685du
        const val NEWEST_TODO: UInt = 0xb9743b7du
        const val ROWS_NOTE: UInt = 0x0efa400eu
        const val ROWS_TODO: UInt = 0x5ad5844au
        const val SAVE_NOTE: UInt = 0xea8bfd5eu
        const val SAVE_TODO: UInt = 0x8beca6dau
    }

    object Ports {}

    object Queries {}
}
