// Generated by undra-bindgen from the Undra schema of `golden-generic-functions` (schema hash 0x032c4563a078af57). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.generic_functions

import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter

/** A note. */
data class Note(
    val id: UInt,
    val body: String,
) : UndraRecord {
    companion object : UndraCodec<Note> {
        override fun encode(w: UndraWriter, v: Note) {
            w.writeU32(v.id)
            w.writeStr(v.body)
        }

        override fun decode(r: UndraReader): Note = Note(id = r.readU32(), body = r.readStr())
    }
}

/** A todo. */
data class Todo(
    val id: UInt,
    val title: String,
) : UndraRecord {
    companion object : UndraCodec<Todo> {
        override fun encode(w: UndraWriter, v: Todo) {
            w.writeU32(v.id)
            w.writeStr(v.title)
        }

        override fun decode(r: UndraReader): Todo = Todo(id = r.readU32(), title = r.readStr())
    }
}
