// Generated by keel-bindgen from the Keel schema of `golden-stdlib` (schema hash 0x6b4638c4a5e34313). Do not edit.

package golden.stdlib

import dev.keel.runtime.KeelCore
import dev.keel.runtime.KeelObject
import dev.keel.runtime.KeelReplyException
import dev.keel.runtime.adapters.FsError
import dev.keel.runtime.adapters.HttpError
import dev.keel.runtime.adapters.HttpRequest
import dev.keel.runtime.adapters.HttpResponse
import dev.keel.runtime.wire.Handle
import dev.keel.runtime.wire.KeelWriter
import dev.keel.runtime.wire.Payloads.CallTarget
import dev.keel.runtime.wire.Payloads.ReplyStatus
import dev.keel.runtime.wire.decodeAll
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map

/** Talks to the server. */
class Syncer private constructor(core: KeelCore, handle: Long) : KeelObject(core, handle) {
    constructor(ctx: KeelCore = KeelCore.shared) : this(
        ctx,
        ctx.construct(KeelIds.Objects.Syncer.TYPE_ID, KeelIds.Objects.Syncer.NEW, ByteArray(0)),
    )

    /**
     * Performs one request.
     * @throws HttpError
     */
    suspend fun send(request: HttpRequest): HttpResponse {
        val w = KeelWriter()
        HttpRequest.encode(w, request)
        val body = try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.Syncer.SEND),
                KeelIds.Objects.Syncer.SEND,
                w.toByteArray(),
            )
        } catch (e: KeelReplyException) {
            throw if (e.status == ReplyStatus.ERROR) HttpError.decodeAll(e.body) else e
        }
        return HttpResponse.decodeAll(body)
    }

    /**
     * Streams the responses of a request that repeats.
     * @throws HttpError
     */
    fun follow(endpoint: Endpoint): Flow<HttpResponse> {
        val w = KeelWriter()
        Endpoint.encode(w, endpoint)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.Syncer.FOLLOW),
            KeelIds.Objects.Syncer.FOLLOW,
            w.toByteArray(),
        )
        return stream
            .map { bytes -> HttpResponse.decodeAll(bytes) }
            .catch { error ->
                throw if (error is KeelReplyException && error.status == ReplyStatus.ERROR) HttpError.decodeAll(error.body) else error
            }
    }

    /**
     * Writes the last response to disk.
     * @throws FsError
     */
    suspend fun save(path: String) {
        val w = KeelWriter()
        w.writeStr(path)
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.Syncer.SAVE),
                KeelIds.Objects.Syncer.SAVE,
                w.toByteArray(),
            )
        } catch (e: KeelReplyException) {
            throw if (e.status == ReplyStatus.ERROR) FsError.decodeAll(e.body) else e
        }
    }

    /** @throws SyncError */
    suspend fun sync() {
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), KeelIds.Objects.Syncer.SYNC),
                KeelIds.Objects.Syncer.SYNC,
                ByteArray(0),
            )
        } catch (e: KeelReplyException) {
            throw SyncError.fromReply(e)
        }
    }

    companion object {
        fun create(ctx: KeelCore = KeelCore.shared): Syncer {
            val handle = ctx.construct(KeelIds.Objects.Syncer.TYPE_ID, KeelIds.Objects.Syncer.NEW, ByteArray(0))
            return Syncer(ctx, handle)
        }
    }
}
