// Generated by keel-bindgen from the Keel schema of `golden-stdlib` (schema hash 0x6b4638c4a5e34313). Do not edit.

package golden.stdlib

import dev.keel.runtime.KeelCore
import dev.keel.runtime.KeelStore
import dev.keel.runtime.adapters.AppState
import dev.keel.runtime.adapters.HttpError
import dev.keel.runtime.adapters.HttpRequest
import dev.keel.runtime.adapters.HttpResponse
import dev.keel.runtime.adapters.NetKind
import dev.keel.runtime.wire.Codecs
import dev.keel.runtime.wire.KeelReader
import dev.keel.runtime.wire.Payloads.ChangeOp
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Mirrors what the platform reports about the connection. */
class Link private constructor(core: KeelCore, handle: Long) : KeelStore(core, handle) {
    private val _state: MutableStateFlow<AppState> = signal(AppState.ACTIVE)
    val state: StateFlow<AppState> = _state.asStateFlow()
    private val _kind: MutableStateFlow<NetKind> = signal(NetKind.WIFI)
    val kind: StateFlow<NetKind> = _kind.asStateFlow()
    private val _last: MutableStateFlow<HttpResponse?> = signal(null)
    val last: StateFlow<HttpResponse?> = _last.asStateFlow()
    private val _failure: MutableStateFlow<HttpError?> = signal(null)
    val failure: StateFlow<HttpError?> = _failure.asStateFlow()
    private val _pending: MutableStateFlow<List<HttpRequest>> = signal(emptyList())
    val pending: StateFlow<List<HttpRequest>> = _pending.asStateFlow()

    init {
        core.observe(handle, UInt.MAX_VALUE, true)
    }

    constructor(ctx: KeelCore = KeelCore.shared) : this(
        ctx,
        ctx.construct(KeelIds.Objects.Link.TYPE_ID, KeelIds.Objects.Link.NEW, ByteArray(0)),
    )

    override fun apply(signalId: UInt, op: ChangeOp, reader: KeelReader) {
        when (signalId) {
            0u -> {
                if (op == ChangeOp.FULL) {
                    _state.value = AppState.decode(reader)
                    reader.finish()
                }
            }
            1u -> {
                if (op == ChangeOp.FULL) {
                    _kind.value = NetKind.decode(reader)
                    reader.finish()
                }
            }
            2u -> {
                if (op == ChangeOp.FULL) {
                    _last.value = codecOptionHttpResponse.decode(reader)
                    reader.finish()
                }
            }
            3u -> {
                if (op == ChangeOp.FULL) {
                    _failure.value = codecOptionHttpError.decode(reader)
                    reader.finish()
                }
            }
            4u -> {
                if (op == ChangeOp.FULL) {
                    _pending.value = codecVecHttpRequest.decode(reader)
                    reader.finish()
                }
            }
            else -> Unit
        }
    }

    companion object {
        fun create(ctx: KeelCore = KeelCore.shared): Link {
            val handle = ctx.construct(KeelIds.Objects.Link.TYPE_ID, KeelIds.Objects.Link.NEW, ByteArray(0))
            return Link(ctx, handle)
        }
    }
}

private val codecOptionHttpResponse = Codecs.option(HttpResponse)
private val codecOptionHttpError = Codecs.option(HttpError)
private val codecVecHttpRequest = Codecs.vec(HttpRequest)
