// Generated by undra-bindgen from the Undra schema of `golden-lazy` (schema hash 0x1b2e19aa5e8a1bef). Do not edit.

import { type Codec } from "@undra/runtime";

/** One book of the library. */
export interface Book {
  id: bigint;
  title: string;
  year: number;
}

export const BookCodec: Codec<Book> = {
  encode(w, v) {
    w.writeU64(v.id);
    w.writeStr(v.title);
    w.writeU16(v.year);
  },
  decode(r) {
    return {
      id: r.readU64(),
      title: r.readStr(),
      year: r.readU16(),
    };
  },
};

export interface Shelf {
  name: string;
  count: number;
}

export const ShelfCodec: Codec<Shelf> = {
  encode(w, v) {
    w.writeStr(v.name);
    w.writeU32(v.count);
  },
  decode(r) {
    return {
      name: r.readStr(),
      count: r.readU32(),
    };
  },
};
