"""`undra_binaryen`: the `wasm-opt` the web size gate is measured with, pinned.

`undra build --platform web` runs `wasm-opt -Oz` over the module when it finds one, and its output size moves between binaryen
releases, so the repository's web budgets are measured with one (bench.yml pins version_133). This downloads that release for
the machine Bazel runs on, by checksum, so a Bazel build of a core gives the module the CLI gives on a developer's machine
that has the same binaryen.
"""

VERSION = "version_133"

_ASSETS = {
    "linux x86_64": ("x86_64-linux", "2dc9c7813f5375db93d96ead4b78222fcc3e2677bbb832297af4797782a37489"),
    "linux aarch64": ("aarch64-linux", "89c07ea56faf38d0fbecf36ca8ec0721756716185f265b568e133d427f299bf8"),
    "mac x86_64": ("x86_64-macos", "13a9b90be775c6389ce3d1f879cb8627bea56708ba8c122983941d53a8199b95"),
    "mac aarch64": ("arm64-macos", "ad66da82ac13f163e424b1643f16c6dfcccc98b5966296b43e52d3cab04f84a8"),
}

def _impl(rctx):
    os = rctx.os.name.lower()
    os = "mac" if os.startswith("mac") else ("linux" if os.startswith("linux") else os)
    arch = rctx.os.arch
    arch = {"amd64": "x86_64", "arm64": "aarch64"}.get(arch, arch)
    key = os + " " + arch
    if key not in _ASSETS:
        fail("undra_binaryen: no binaryen {} release is pinned for {}; pass your own `wasm_opt` to undra_core".format(VERSION, key))
    asset, sha256 = _ASSETS[key]
    rctx.download_and_extract(
        url = "https://github.com/WebAssembly/binaryen/releases/download/{v}/binaryen-{v}-{a}.tar.gz".format(v = VERSION, a = asset),
        sha256 = sha256,
        stripPrefix = "binaryen-" + VERSION,
    )
    rctx.file("BUILD.bazel", """# Generated by undra_binaryen.
package(default_visibility = ["//visibility:public"])

# `wasm-opt` and what it needs next to it.
filegroup(
    name = "wasm_opt",
    srcs = glob(["bin/**", "lib/**"], allow_empty = True),
)
""")

undra_binaryen = repository_rule(
    implementation = _impl,
    doc = "The pinned binaryen release for this machine.",
)
