"""`undra_vendor`: the crates a build needs, downloaded by the checksum `Cargo.lock` records.

Cargo is what builds a core (the `undra` CLI drives it, ADR-061), and Cargo cannot be allowed to reach the network from a
Bazel action: this repository rule is where the network is used, once, at fetch time, with Bazel's repository cache and
downloader. It reads one or more `Cargo.lock` files, downloads every registry package they name from crates.io and checks
it against the lock's own SHA-256. An action extracts the archives it is given into a Cargo "directory source"
(`run.sh`), so no action ever touches the network and none can build a dependency the lock does not name.

A package from a git repository, or from a registry other than crates.io, is refused with a message naming it: depend on
a crates.io release or on a path instead.
"""

CRATES_IO = "registry+https://github.com/rust-lang/crates.io-index"
SPARSE_CRATES_IO = "sparse+https://index.crates.io/"

def parse_lock(text):
    """Reads the `[[package]]` tables of a Cargo.lock.

    Args:
        text: the file's text.

    Returns:
        a list of dicts with the keys `name`, `version` and, when the lock has them, `source` and `checksum`.
    """
    packages = []
    current = None
    for raw in text.splitlines():
        line = raw.strip()
        if line == "[[package]]":
            current = {}
            packages.append(current)
        elif line.startswith("["):
            # `[metadata]`, `[[patch.unused]]`: not part of the build.
            current = None
        elif current != None and "=" in line:
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip()
            if key in ("name", "version", "source", "checksum") and value.startswith("\"") and value.endswith("\""):
                current[key] = value[1:-1]
    return packages

def registry_packages(packages, origin):
    """The packages that come from crates.io, de-duplicated; fails for any other remote source.

    Args:
        packages: the result of `parse_lock`.
        origin: what to call the lock file in an error message.

    Returns:
        a sorted list of `(name, version, checksum)`.
    """
    found = {}
    for package in packages:
        source = package.get("source")
        if not source:
            continue  # a path package: the workspace's own crates
        if source not in (CRATES_IO, SPARSE_CRATES_IO):
            fail(("{origin}: package {name} {version} comes from `{source}`. `undra_vendor` downloads crates.io packages by " +
                  "the checksum the lock records; depend on a crates.io release (or a path) instead.").format(
                origin = origin,
                name = package.get("name"),
                version = package.get("version"),
                source = source,
            ))
        checksum = package.get("checksum")
        if not checksum:
            fail(("{origin}: package {name} {version} has no checksum in the lock file; run `cargo generate-lockfile` " +
                  "with a Cargo that writes them.").format(
                origin = origin,
                name = package.get("name"),
                version = package.get("version"),
            ))
        found[(package["name"], package["version"], checksum)] = True
    return sorted(found.keys())

def _impl(rctx):
    wanted = {}
    for label in rctx.attr.lockfiles:
        rctx.watch(label)
        text = rctx.read(label)
        for entry in registry_packages(parse_lock(text), str(label)):
            wanted[entry] = True

    manifest = []
    for name, version, checksum in sorted(wanted.keys()):
        archive = "crates/{}-{}.crate".format(name, version)
        rctx.download(
            url = [
                "https://static.crates.io/crates/{n}/{n}-{v}.crate".format(n = name, v = version),
                "https://crates.io/api/v1/crates/{n}/{v}/download".format(n = name, v = version),
            ],
            output = archive,
            sha256 = checksum,
        )
        manifest.append("{}|{}|{}|{}".format(name, version, checksum, archive))
    rctx.file("manifest.txt", "\n".join(manifest) + "\n")
    rctx.file("BUILD.bazel", """# Generated by undra_vendor from {locks}.
package(default_visibility = ["//visibility:public"])

# Every archive and the manifest an action reads to unpack them (name|version|sha256|path).
filegroup(
    name = "crates",
    srcs = glob(["crates/*.crate"]) + ["manifest.txt"],
)

exports_files(["manifest.txt"])
""".format(locks = ", ".join([str(l) for l in rctx.attr.lockfiles])))

undra_vendor = repository_rule(
    implementation = _impl,
    attrs = {
        "lockfiles": attr.label_list(
            doc = "The Cargo.lock files whose registry packages are vendored: the application's, and the Undra checkout's.",
            allow_files = True,
        ),
    },
    doc = "Downloads the crates.io packages named by Cargo.lock files, by checksum.",
)
