//! Case conversion and reserved-word escaping for the three target languages.
//!
//! Rust `snake_case` field, parameter and method names become `camelCase`
//! (`UPPER_SNAKE` for Kotlin enum entries and constants). Type names are
//! already `PascalCase` in Rust and are kept exactly as declared, so a name in
//! the schema is the name in every language. Identifiers that collide with a
//! keyword of the target language are escaped the way that language spells it:
//!
//! * Swift: backticks (`` `default` ``);
//! * Kotlin: backticks for hard keywords (`` `object` ``);
//! * TypeScript: a trailing underscore for binding identifiers (`default_`);
//!   property and method names may be reserved words in TypeScript and are not
//!   escaped.
//!
//! ```
//! use undra_bindgen::naming;
//!
//! assert_eq!(naming::camel("set_filter"), "setFilter");
//! assert_eq!(naming::pascal("todo_store"), "TodoStore");
//! assert_eq!(naming::upper_snake("EmptyTitle"), "EMPTY_TITLE");
//! assert_eq!(naming::swift_ident("default"), "`default`");
//! assert_eq!(naming::kotlin_ident("object"), "`object`");
//! assert_eq!(naming::ts_ident("delete"), "delete_");
//! ```

use heck::{ToLowerCamelCase, ToShoutySnakeCase, ToUpperCamelCase};

/// `snake_case` or `PascalCase` to `lowerCamelCase`: `set_filter` to
/// `setFilter`, `EmptyTitle` to `emptyTitle`.
#[must_use]
pub fn camel(name: &str) -> String {
    name.to_lower_camel_case()
}

/// `snake_case` to `PascalCase`: `todo_store` to `TodoStore`.
#[must_use]
pub fn pascal(name: &str) -> String {
    name.to_upper_camel_case()
}

/// `snake_case` or `PascalCase` to `UPPER_SNAKE_CASE`: `EmptyTitle` to
/// `EMPTY_TITLE`.
#[must_use]
pub fn upper_snake(name: &str) -> String {
    name.to_shouty_snake_case()
}

/// The names ADR-044 derives from a core's namespace (`[core] namespace` of `undra.toml`), so the
/// CLI's artefacts and the generated entry points always agree.
///
/// ```
/// use undra_bindgen::naming::CoreNames;
///
/// let pay = CoreNames::new("acme_pay");
/// assert_eq!(pay.entry(), "UndraAcmePay");
/// assert_eq!(pay.bundle(), "AcmePayCore");
/// assert_eq!(pay.ffi_module(), "AcmePayCoreFFI");
/// assert_eq!(pay.api_symbol(), "acme_pay_undra_api");
/// assert_eq!(pay.header(), "acme_pay_undra.h");
/// // A namespace that already ends in `core` is not suffixed twice.
/// assert_eq!(CoreNames::new("playground_core").bundle(), "PlaygroundCore");
/// assert_eq!(CoreNames::jni_class("dev.acme.pay.core"), "dev/acme/pay/core/UndraCoreNative");
/// ```
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct CoreNames {
    namespace: String,
}

impl CoreNames {
    /// The names of the core whose namespace is `namespace` (a lowercase C identifier).
    #[must_use]
    pub fn new(namespace: &str) -> CoreNames {
        CoreNames {
            namespace: namespace.to_owned(),
        }
    }

    /// The namespace itself (`acme_pay`).
    #[must_use]
    pub fn namespace(&self) -> &str {
        &self.namespace
    }

    /// The default namespace of a core crate: its package name in snake case (`playground-core`
    /// becomes `playground_core`).
    #[must_use]
    pub fn default_namespace(crate_name: &str) -> String {
        crate_name
            .chars()
            .map(|c| {
                if c.is_ascii_alphanumeric() {
                    c.to_ascii_lowercase()
                } else {
                    '_'
                }
            })
            .collect()
    }

    /// The generated entry point in every language: `Undra` and the namespace in `PascalCase`
    /// (`UndraAcmePay`).
    #[must_use]
    pub fn entry(&self) -> String {
        format!("Undra{}", pascal(&self.namespace))
    }

    /// The base name of the core's packaged artefacts (`AcmePayCore`: `AcmePayCore.xcframework`,
    /// the `AcmePayCore` pod): the namespace in `PascalCase` plus `Core`, unless it already ends so.
    #[must_use]
    pub fn bundle(&self) -> String {
        let base = pascal(&self.namespace);
        if base.ends_with("Core") {
            base
        } else {
            format!("{base}Core")
        }
    }

    /// The C module that declares the core's entry for Swift (`AcmePayCoreFFI`).
    #[must_use]
    pub fn ffi_module(&self) -> String {
        format!("{}FFI", self.bundle())
    }

    /// The core's one C export, `<namespace>_undra_api`.
    #[must_use]
    pub fn api_symbol(&self) -> String {
        format!("{}_undra_api", self.namespace)
    }

    /// The C header that declares it, `<namespace>_undra.h`.
    #[must_use]
    pub fn header(&self) -> String {
        format!("{}_undra.h", self.namespace)
    }

    /// The text of [`header`](Self::header): the entry, returning `const void *` so the
    /// `UndraApi` type stays owned by `undra.h` (the runtime's `UndraFFI` module).
    #[must_use]
    pub fn header_text(&self) -> String {
        let guard = format!("{}_UNDRA_H", self.namespace.to_ascii_uppercase());
        format!(
            "/* Generated by undra: do not edit.\n \
             *\n \
             * {header}: the entry point of the Undra core `{ns}` (C ABI version 2, docs/SPEC.md 6).\n \
             * The core exports this one function. It returns the core's `UndraApi` table (declared by\n \
             * undra.h), as `const void *` so that undra.h stays the one owner of that type.\n \
             */\n\
             #ifndef {guard}\n\
             #define {guard}\n\
             \n\
             #ifdef __cplusplus\n\
             extern \"C\" {{\n\
             #endif\n\
             \n\
             const void *{symbol}(void);\n\
             \n\
             #ifdef __cplusplus\n\
             }}\n\
             #endif\n\
             \n\
             #endif /* {guard} */\n",
            header = self.header(),
            ns = self.namespace,
            symbol = self.api_symbol(),
        )
    }

    /// The JNI name of the class the core registers its natives on: `UndraCoreNative` in the
    /// Kotlin package of the bindings (`dev/acme/pay/core/UndraCoreNative`).
    #[must_use]
    pub fn jni_class(kotlin_package: &str) -> String {
        format!("{}/UndraCoreNative", kotlin_package.replace('.', "/"))
    }

    /// Whether [`entry`](Self::entry) is a name the generated bindings cannot declare: one of
    /// [`RESERVED_ENTRIES`] (the namespace `core` would make the entry `UndraCore`, the runtime's
    /// own type, and the bindings would not compile).
    #[must_use]
    pub fn entry_is_reserved(&self) -> bool {
        RESERVED_ENTRIES.contains(&self.entry().as_str())
    }
}

/// The names a core's entry `Undra<Namespace>` must not take: every `Undra…` type, module and
/// top-level name the Swift, Kotlin, TypeScript and React Native runtimes declare, the ones the
/// generated bindings declare beside the entry (`UndraIds`, `UndraCoreNative`) and the ones the
/// `undra init` app templates declare (`UndraApp`, `UndraBootstrap`, `UndraBuild`). The entry is
/// declared in the same scope as all of them, so a namespace whose entry is one of these
/// (`core`, `ids`, `store`, ...) is refused by `undra` with this reason rather than producing
/// bindings that do not compile. A test keeps it in step with the runtimes' sources.
pub const RESERVED_ENTRIES: &[&str] = &[
    "UndraAdapter",
    "UndraApi",
    "UndraApp",
    "UndraAppState",
    "UndraBackground",
    "UndraBackgroundReport",
    "UndraBackgroundStats",
    "UndraBootstrap",
    "UndraBuild",
    "UndraBuildError",
    "UndraBytes",
    "UndraCallError",
    "UndraCallErrorKind",
    "UndraCallFailure",
    "UndraClass",
    "UndraClosedReason",
    "UndraCodec",
    "UndraConnection",
    "UndraConnectionState",
    "UndraCore",
    "UndraCoreEntry",
    "UndraCoreNative",
    "UndraCoreRestarted",
    "UndraDispatchers",
    "UndraDuration",
    "UndraEmbeddingApi",
    "UndraEnum",
    "UndraError",
    "UndraException",
    "UndraFFI",
    "UndraHandle",
    "UndraIds",
    "UndraInbound",
    "UndraIndirect",
    "UndraLifecycle",
    "UndraLoadError",
    "UndraLog",
    "UndraMode",
    "UndraModeError",
    "UndraModeException",
    "UndraNative",
    "UndraNativeModule",
    "UndraObject",
    "UndraPanicFrame",
    "UndraPanicReport",
    "UndraPayload",
    "UndraPluginOptions",
    "UndraPort",
    "UndraPortError",
    "UndraPortException",
    "UndraProtocolError",
    "UndraProtocolException",
    "UndraReactNative",
    "UndraReader",
    "UndraReconnectPolicy",
    "UndraRecord",
    "UndraReplyError",
    "UndraReplyException",
    "UndraRestoreError",
    "UndraRestoreException",
    "UndraResult",
    "UndraRuntime",
    "UndraSchemaMismatchError",
    "UndraSchemaMismatchException",
    "UndraSessionLostError",
    "UndraSessionLostException",
    "UndraStats",
    "UndraStore",
    "UndraTimestamp",
    "UndraTransport",
    "UndraTransportError",
    "UndraTransportException",
    "UndraUUID",
    "UndraUnhandledError",
    "UndraUnit",
    "UndraVitePlugin",
    "UndraWriter",
];

/// Whether `name` is usable as an identifier in all three languages: ASCII
/// letters, digits and underscores, not starting with a digit, not empty.
#[must_use]
pub fn is_valid_ident(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_') && name.chars().any(|c| c != '_')
}

/// Swift keywords that cannot be used as identifiers without backticks.
const SWIFT_RESERVED: &[&str] = &[
    "Any",
    "Protocol",
    "Self",
    "Type",
    "as",
    "associatedtype",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "continue",
    "default",
    "defer",
    "deinit",
    "do",
    "else",
    "enum",
    "extension",
    "fallthrough",
    "false",
    "fileprivate",
    "for",
    "func",
    "guard",
    "if",
    "import",
    "in",
    "init",
    "inout",
    "internal",
    "is",
    "let",
    "nil",
    "open",
    "operator",
    "precedencegroup",
    "private",
    "protocol",
    "public",
    "repeat",
    "rethrows",
    "return",
    "self",
    "static",
    "struct",
    "subscript",
    "super",
    "switch",
    "throw",
    "throws",
    "true",
    "try",
    "typealias",
    "var",
    "where",
    "while",
];

/// Kotlin hard keywords (soft keywords and modifiers are legal identifiers).
const KOTLIN_RESERVED: &[&str] = &[
    "as",
    "break",
    "class",
    "continue",
    "do",
    "else",
    "false",
    "for",
    "fun",
    "if",
    "in",
    "interface",
    "is",
    "null",
    "object",
    "package",
    "return",
    "super",
    "this",
    "throw",
    "true",
    "try",
    "typealias",
    "typeof",
    "val",
    "var",
    "when",
    "while",
];

/// TypeScript / JavaScript reserved words, including the strict-mode ones and
/// the names a module may not bind.
const TS_RESERVED: &[&str] = &[
    "arguments",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "eval",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "undefined",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

/// Member names a TypeScript class cannot declare as methods or fields.
const TS_RESERVED_MEMBERS: &[&str] = &["constructor", "prototype", "__proto__"];

/// Whether `name` is a Swift keyword.
#[must_use]
pub fn is_swift_reserved(name: &str) -> bool {
    SWIFT_RESERVED.contains(&name)
}

/// Whether `name` is a Kotlin hard keyword.
#[must_use]
pub fn is_kotlin_reserved(name: &str) -> bool {
    KOTLIN_RESERVED.contains(&name)
}

/// Whether `name` is a TypeScript reserved word.
#[must_use]
pub fn is_ts_reserved(name: &str) -> bool {
    TS_RESERVED.contains(&name)
}

/// A Swift identifier: backticked when `name` is a keyword.
#[must_use]
pub fn swift_ident(name: &str) -> String {
    if is_swift_reserved(name) {
        format!("`{name}`")
    } else {
        name.to_owned()
    }
}

/// A Swift stored-property name on an `@Observable` class: the macro rejects
/// backticked stored properties, so a reserved word gets a trailing underscore
/// instead (`default` becomes `default_`). The schema name is unchanged; only
/// the Swift spelling moves.
#[must_use]
pub fn swift_stored_property(name: &str) -> String {
    if is_swift_reserved(name) {
        format!("{name}_")
    } else {
        name.to_owned()
    }
}

/// A Kotlin identifier: backticked when `name` is a hard keyword.
#[must_use]
pub fn kotlin_ident(name: &str) -> String {
    if is_kotlin_reserved(name) {
        format!("`{name}`")
    } else {
        name.to_owned()
    }
}

/// A TypeScript binding identifier (parameter, local): a trailing underscore
/// when `name` is a reserved word.
#[must_use]
pub fn ts_ident(name: &str) -> String {
    if is_ts_reserved(name) {
        format!("{name}_")
    } else {
        name.to_owned()
    }
}

/// A TypeScript property or method name. Reserved words are legal there, so
/// only the few names a class cannot declare are escaped.
#[must_use]
pub fn ts_member(name: &str) -> String {
    if TS_RESERVED_MEMBERS.contains(&name) {
        format!("{name}_")
    } else {
        name.to_owned()
    }
}

/// `name` with underscores appended until it is not in `taken`. Generated
/// locals use this so a schema parameter called `w` or `body` never shadows
/// the writer or the reply.
#[must_use]
pub fn avoid(name: &str, taken: &[&str]) -> String {
    let mut out = name.to_owned();
    while taken.contains(&out.as_str()) {
        out.push('_');
    }
    out
}

/// The name of field number `index` of a tuple variant with `count` fields:
/// `value` for a single field, `value0`, `value1`, ... otherwise.
#[must_use]
pub fn tuple_field(index: usize, count: usize) -> String {
    if count == 1 {
        "value".to_owned()
    } else {
        format!("value{index}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn case_conversions() {
        assert_eq!(camel("set_filter"), "setFilter");
        assert_eq!(camel("EmptyTitle"), "emptyTitle");
        assert_eq!(camel("id"), "id");
        assert_eq!(camel("http_2_error"), "http2Error");
        assert_eq!(pascal("todo_store"), "TodoStore");
        assert_eq!(pascal("todos"), "Todos");
        assert_eq!(upper_snake("EmptyTitle"), "EMPTY_TITLE");
        assert_eq!(upper_snake("set_filter"), "SET_FILTER");
        assert_eq!(upper_snake("Wifi"), "WIFI");
        assert_eq!(camel("HTTPError"), "httpError");
    }

    #[test]
    fn reserved_words_are_escaped_per_language() {
        for word in ["default", "in", "where", "init", "self", "case"] {
            assert!(swift_ident(word).starts_with('`'), "{word}");
        }
        for word in ["object", "when", "fun", "in", "is", "val"] {
            assert!(kotlin_ident(word).starts_with('`'), "{word}");
        }
        for word in ["default", "delete", "new", "function", "let", "class"] {
            assert_eq!(ts_ident(word), format!("{word}_"));
        }
        assert_eq!(swift_ident("title"), "title");
        assert_eq!(kotlin_ident("title"), "title");
        assert_eq!(ts_ident("title"), "title");
        // Kotlin soft keywords and Swift contextual keywords stay bare.
        assert_eq!(kotlin_ident("data"), "data");
        assert_eq!(kotlin_ident("open"), "open");
        assert_eq!(swift_ident("some"), "some");
    }

    #[test]
    fn ts_members_may_be_reserved_words() {
        assert_eq!(ts_member("delete"), "delete");
        assert_eq!(ts_member("default"), "default");
        assert_eq!(ts_member("constructor"), "constructor_");
    }

    #[test]
    fn identifier_validation() {
        assert!(is_valid_ident("Todo"));
        assert!(is_valid_ident("_x1"));
        assert!(!is_valid_ident(""));
        assert!(!is_valid_ident("1x"));
        assert!(!is_valid_ident("a-b"));
        assert!(!is_valid_ident("_"));
        assert!(!is_valid_ident("Ünï"));
        assert!(!is_valid_ident("a::b"));
    }

    #[test]
    fn avoid_appends_underscores_until_free() {
        assert_eq!(avoid("w", &["a", "b"]), "w");
        assert_eq!(avoid("w", &["w"]), "w_");
        assert_eq!(avoid("w", &["w", "w_"]), "w__");
    }

    #[test]
    fn tuple_field_names() {
        assert_eq!(tuple_field(0, 1), "value");
        assert_eq!(tuple_field(0, 2), "value0");
        assert_eq!(tuple_field(1, 2), "value1");
    }

    #[test]
    fn a_namespace_whose_entry_is_a_runtime_name_is_reserved() {
        assert!(CoreNames::new("core").entry_is_reserved());
        assert!(CoreNames::new("core_native").entry_is_reserved());
        assert!(!CoreNames::new("acme_pay").entry_is_reserved());
        assert!(!CoreNames::new("playground_core").entry_is_reserved());
    }

    /// Every `Undra…` name a runtime or an app template declares is in [`RESERVED_ENTRIES`], so a
    /// runtime that gains a type cannot silently make some namespace generate uncompilable bindings.
    /// Skipped when the sources are not beside this crate (a published package).
    #[test]
    fn the_reserved_entries_cover_every_name_the_runtimes_declare() {
        let repo = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let roots = [
            "runtimes/swift/UndraRuntime/Sources",
            "runtimes/kotlin/undra-runtime/runtime/src/main",
            "runtimes/kotlin/undra-runtime/android-adapters/src/main",
            "runtimes/ts/@undra/runtime/src",
            "runtimes/rn/@undra/react-native/src",
            "crates/undra-cli/templates",
        ];
        if !repo.join(roots[0]).is_dir() {
            return;
        }
        const DECLARATIONS: &[&str] = &[
            "class",
            "struct",
            "enum",
            "protocol",
            "actor",
            "typealias",
            "object",
            "interface",
            "const",
            "function",
            "type",
            "let",
            "var",
            "val",
            "fun",
            "func",
        ];
        let mut files = Vec::new();
        let mut dirs: Vec<std::path::PathBuf> = roots.iter().map(|r| repo.join(r)).collect();
        while let Some(dir) = dirs.pop() {
            let Ok(entries) = std::fs::read_dir(&dir) else {
                continue;
            };
            for entry in entries.flatten() {
                let path = entry.path();
                if path.is_dir() {
                    dirs.push(path);
                } else {
                    files.push(path);
                }
            }
        }
        let mut missing = std::collections::BTreeSet::new();
        for file in files {
            let Ok(text) = std::fs::read_to_string(&file) else {
                continue;
            };
            let tokens: Vec<&str> = text
                .split(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
                .filter(|t| !t.is_empty())
                .collect();
            for pair in tokens.windows(2) {
                let name = pair[1];
                let declared = DECLARATIONS.contains(&pair[0])
                    && name.len() > "Undra".len()
                    && name.starts_with("Undra")
                    && name[5..].starts_with(|c: char| c.is_ascii_uppercase());
                if declared && !RESERVED_ENTRIES.contains(&name) && name != "UndraPlaygroundCore" {
                    missing.insert(format!("{name} ({})", file.display()));
                }
            }
        }
        assert!(
            missing.is_empty(),
            "add these to RESERVED_ENTRIES (a namespace whose entry is one of them would generate \
             bindings that do not compile): {missing:?}"
        );
    }
}
