//! How a generated file says what it is (ADR-062): the sentence every generated source file starts
//! with, and the `.gitattributes` that lets a code host collapse a generated tree in review.
//!
//! Generated code is an artifact of the schema, and the schema is the API. The text here is the one
//! place both facts are spelled, so the three generators, the package manifests the CLI adds and the
//! golden tests all say the same thing.
//!
//! ```
//! use undra_bindgen::provenance;
//!
//! let sentence = provenance::sentence("demo-core", 0x1234_5678_9abc_def0);
//! assert_eq!(
//!     sentence,
//!     "Generated by undra-bindgen from the Undra schema of `demo-core` (schema hash 0x123456789abcdef0). Do not edit."
//! );
//! // The header of a Swift, Kotlin or TypeScript source file is that sentence as a line comment.
//! assert_eq!(provenance::line_comment("demo-core", 7), format!("// {}", provenance::sentence("demo-core", 7)));
//! ```

/// The sentence a generated file carries: the generator, the core, the schema hash and "do not
/// edit". A comment marker goes in front of it (see [`line_comment`]); a format with no comments
/// (`package.json`) holds it as the value of a `"//"` member.
///
/// A test reads the hash back from the committed bindings (`crates/undra-cli/tests/schema_docs.rs`),
/// so the shape `(schema hash 0x<16 hex digits>)` is relied upon.
#[must_use]
pub fn sentence(crate_name: &str, schema_hash: u64) -> String {
    format!(
        "Generated by undra-bindgen from the Undra schema of `{crate_name}` (schema hash 0x{schema_hash:016x}). Do not edit."
    )
}

/// The header of a Swift, Kotlin or TypeScript source file, and of `tsconfig.json`: [`sentence`] as
/// a `//` comment.
#[must_use]
pub fn line_comment(crate_name: &str, schema_hash: u64) -> String {
    format!("// {}", sentence(crate_name, schema_hash))
}

/// The `.gitattributes` the CLI writes at the root of each generated tree (`swift/`, `kotlin/`,
/// `ts/`; ADR-062).
///
/// `linguist-generated=true` is what GitHub reads to collapse a file in a pull request's diff and to
/// leave it out of the repository's language statistics. `diff` is deliberately **not** unset: the
/// diff stays one click (or one `git diff`) away for the reviewer who wants it. `*` matches every
/// file below the tree, so a hand-written file kept inside one is collapsed too; a nested
/// `.gitattributes` with `-linguist-generated` next to it restores it.
pub const GITATTRIBUTES: &str = "\
# Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
# GitHub collapses these files in a pull request and leaves them out of the language statistics.
# Review the schema (`undra schema diff`), not the bindings: `undra bindgen --check` proves they
# match it. A collapsed file opens to its full diff when you click it.
* linguist-generated=true
";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_sentence_names_the_generator_the_core_the_hash_and_do_not_edit() {
        let text = sentence("playground-core", 0x3c17_cd5f_59bb_6f68);
        assert!(text.starts_with("Generated by undra-bindgen"), "{text}");
        assert!(text.contains("`playground-core`"), "{text}");
        assert!(text.contains("(schema hash 0x3c17cd5f59bb6f68)"), "{text}");
        assert!(text.ends_with("Do not edit."), "{text}");
        assert!(!text.contains('\n'), "a header is one line");
    }

    #[test]
    fn a_small_hash_is_padded_to_sixteen_digits() {
        assert!(sentence("c", 0xab).contains("(schema hash 0x00000000000000ab)"));
    }

    #[test]
    fn gitattributes_collapses_but_never_hides_the_diff() {
        let rules: Vec<&str> = GITATTRIBUTES
            .lines()
            .filter(|l| !l.starts_with('#'))
            .collect();
        // One rule, and it neither unsets `diff` (`-diff`) nor marks the files binary.
        assert_eq!(rules, ["* linguist-generated=true"]);
        assert!(GITATTRIBUTES.ends_with('\n'));
    }
}
