// Generated by undra-bindgen from the Undra schema of `playground-core` (schema hash 0x3b1bd1062551c158). Do not edit.

import {
  type PortImpl,
  UndraCore,
  type UndraPort,
  UndraPortError,
  UndraReader,
  UndraWriter,
  codecs,
  encodeValue,
} from "@undra/runtime";
import { HttpError, HttpErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import {
  type HttpRequest,
  HttpRequestCodec,
  type HttpResponse,
  HttpResponseCodec,
  type NetKind,
  NetKindCodec,
} from "./types.js";

/** Sends the events of this port from the host to the core. A failure (a closed core) is logged and passed to `onError`; the methods do not throw. */
export class ConnectivityEvents {
  constructor(private readonly core: UndraCore = UndraCore.shared) {}

  changed(online: boolean, kind: NetKind): void {
    try {
      const w = new UndraWriter();
      w.writeBool(online);
      NetKindCodec.encode(w, kind);
      this.core.event(
        UndraIds.Ports.Connectivity.portId,
        UndraIds.Ports.Connectivity.changed,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "ConnectivityEvents.changed");
    }
  }
}

export interface Http extends UndraPort {
  /** @throws {HttpError} */
  request(req: HttpRequest): Promise<HttpResponse>;
}

/** Adapts an implementation of `Http` to `UndraCore.registerPort(UndraIds.Ports.Http.portId, ..)`. */
export function httpPortImpl(impl: Http): PortImpl {
  return {
    sync: false,
    methods: {
      [UndraIds.Ports.Http.request]: async (args) => {
        const r = new UndraReader(args);
        const req = HttpRequestCodec.decode(r);
        r.finish();
        try {
          return encodeValue(HttpResponseCodec, await impl.request(req));
        } catch (error) {
          if (error instanceof HttpError) {
            throw new UndraPortError(encodeValue(HttpErrorCodec, error));
          }
          throw error;
        }
      },
    },
  };
}

export interface Kv extends UndraPort {
  get(key: string): Promise<Uint8Array | null>;
  set(key: string, value: Uint8Array): Promise<void>;
}

/** Adapts an implementation of `Kv` to `UndraCore.registerPort(UndraIds.Ports.Kv.portId, ..)`. */
export function kvPortImpl(impl: Kv): PortImpl {
  return {
    sync: false,
    methods: {
      [UndraIds.Ports.Kv.get]: async (args) => {
        const r = new UndraReader(args);
        const key = r.readStr();
        r.finish();
        return encodeValue(optionBytes, await impl.get(key));
      },
      [UndraIds.Ports.Kv.set]: async (args) => {
        const r = new UndraReader(args);
        const key = r.readStr();
        const value = codecs.bytes.decode(r);
        r.finish();
        await impl.set(key, value);
        return new Uint8Array(0);
      },
    },
  };
}

export interface WallClock extends UndraPort {
  nowMs(): bigint;
  monotonicNs(): bigint;
}

/** Adapts an implementation of `WallClock` to `UndraCore.registerPort(UndraIds.Ports.WallClock.portId, ..)`. */
export function wallClockPortImpl(impl: WallClock): PortImpl {
  return {
    sync: true,
    methods: {
      [UndraIds.Ports.WallClock.nowMs]: () => {
        return encodeValue(codecs.i64, impl.nowMs());
      },
      [UndraIds.Ports.WallClock.monotonicNs]: () => {
        return encodeValue(codecs.u64, impl.monotonicNs());
      },
    },
  };
}

const optionBytes = codecs.option(codecs.bytes);
