// Generated by undra-bindgen from the Undra schema of `golden-polling` (schema hash 0xd1471391a5bc5da2). Do not edit.

package golden.polling

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0xd1471391a5bc5da2uL
    const val NAMESPACE: String = "golden_polling"

    object Objects {
        object HeadlinesQueryHandle {
            const val TYPE_ID: UInt = 0x1313b304u
            const val NEW: UInt = 0x1313b304u
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
            const val SET_POLL_INTERVAL: UInt = 0xe327e53bu
        }
        object StatusQueryHandle {
            const val TYPE_ID: UInt = 0x213dbe81u
            const val NEW: UInt = 0x213dbe81u
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
            const val SET_POLL_INTERVAL: UInt = 0xe327e53bu
        }
        object TickerQueryHandle {
            const val TYPE_ID: UInt = 0x38de4411u
            const val NEW: UInt = 0x38de4411u
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
            const val SET_POLL_INTERVAL: UInt = 0xe327e53bu
        }
    }

    object Functions {}

    object Ports {}

    object Queries {
        const val BUY: UInt = 0x7a61fc54u
        const val HEADLINES: UInt = 0x1313b304u
        const val STATUS: UInt = 0x213dbe81u
        const val TICKER: UInt = 0x38de4411u
    }
}
