// Generated by undra-bindgen from the Undra schema of `golden-polling` (schema hash 0xd1471391a5bc5da2). Do not edit.

package golden.polling

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraStore
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.Payloads.ChangeOp
import dev.undra.runtime.wire.Timestamp
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import kotlin.time.Duration
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Observes the `headlines` query (cache key `headlines`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
class HeadlinesQueryHandle internal constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _data: MutableStateFlow<List<String>?> = signal(null)
    /** The latest successful result, if any. */
    val data: StateFlow<List<String>?> = _data.asStateFlow()
    private val _status: MutableStateFlow<QueryStatus> = signal(QueryStatus.IDLE)
    /** Where the query is in its fetch lifecycle. */
    val status: StateFlow<QueryStatus> = _status.asStateFlow()
    private val _error: MutableStateFlow<MarketError?> = signal(null)
    /** The error of the latest failed fetch, cleared by the next success. */
    val error: StateFlow<MarketError?> = _error.asStateFlow()
    private val _fetching: MutableStateFlow<Boolean> = signal(false)
    /** Whether a fetch is in flight (also true while refetching stale data). */
    val fetching: StateFlow<Boolean> = _fetching.asStateFlow()
    private val _updatedAt: MutableStateFlow<Timestamp?> = signal(null)
    /** When `data` was last updated. */
    val updatedAt: StateFlow<Timestamp?> = _updatedAt.asStateFlow()

    /**
     * Fetches again now, even if the data is fresh.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun refetch() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.HeadlinesQueryHandle.REFETCH),
                UndraIds.Objects.HeadlinesQueryHandle.REFETCH,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "HeadlinesQueryHandle.refetch")
        }
    }

    /**
     * Marks the cached entry stale; it refetches while observed.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun invalidate() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.HeadlinesQueryHandle.INVALIDATE),
                UndraIds.Objects.HeadlinesQueryHandle.INVALIDATE,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "HeadlinesQueryHandle.invalidate")
        }
    }

    /**
     * Overrides how often the query polls while this handle observes it, counted from the end of a fetch.
     * The entry polls at the smallest interval among its observers; no interval clears this handle's override.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun setPollInterval(interval: Duration?) {
        try {
            val w = UndraWriter()
            codecOptionDuration.encode(w, interval)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.HeadlinesQueryHandle.SET_POLL_INTERVAL),
                UndraIds.Objects.HeadlinesQueryHandle.SET_POLL_INTERVAL,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "HeadlinesQueryHandle.setPollInterval")
        }
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        try {
            when (signalId) {
                0u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionVecString.decode(reader)
                        reader.finish()
                        _data.value = value
                    }
                }
                1u -> {
                    if (op == ChangeOp.FULL) {
                        val value = QueryStatus.decode(reader)
                        reader.finish()
                        _status.value = value
                    }
                }
                2u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionMarketError.decode(reader)
                        reader.finish()
                        _error.value = value
                    }
                }
                3u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Codecs.bool.decode(reader)
                        reader.finish()
                        _fetching.value = value
                    }
                }
                4u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionTimestamp.decode(reader)
                        reader.finish()
                        _updatedAt.value = value
                    }
                }
                else -> Unit
            }
        } catch (e: Exception) {
            core.report(e, "HeadlinesQueryHandle.apply(signal: $signalId)")
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        operator fun invoke(ctx: UndraCore = UndraGoldenPolling.core): HeadlinesQueryHandle = create(ctx)

        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraGoldenPolling.core): HeadlinesQueryHandle {
            val handle = ctx.constructObject(UndraIds.Objects.HeadlinesQueryHandle.TYPE_ID, UndraIds.Objects.HeadlinesQueryHandle.NEW, ByteArray(0))
            return ctx.adopt(handle, ::HeadlinesQueryHandle)
        }
    }
}

/**
 * Observes the `status` query (cache key `status`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
class StatusQueryHandle internal constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _data: MutableStateFlow<Boolean?> = signal(null)
    /** The latest successful result, if any. */
    val data: StateFlow<Boolean?> = _data.asStateFlow()
    private val _status: MutableStateFlow<QueryStatus> = signal(QueryStatus.IDLE)
    /** Where the query is in its fetch lifecycle. */
    val status: StateFlow<QueryStatus> = _status.asStateFlow()
    private val _error: MutableStateFlow<MarketError?> = signal(null)
    /** The error of the latest failed fetch, cleared by the next success. */
    val error: StateFlow<MarketError?> = _error.asStateFlow()
    private val _fetching: MutableStateFlow<Boolean> = signal(false)
    /** Whether a fetch is in flight (also true while refetching stale data). */
    val fetching: StateFlow<Boolean> = _fetching.asStateFlow()
    private val _updatedAt: MutableStateFlow<Timestamp?> = signal(null)
    /** When `data` was last updated. */
    val updatedAt: StateFlow<Timestamp?> = _updatedAt.asStateFlow()

    /**
     * Fetches again now, even if the data is fresh.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun refetch() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.StatusQueryHandle.REFETCH),
                UndraIds.Objects.StatusQueryHandle.REFETCH,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "StatusQueryHandle.refetch")
        }
    }

    /**
     * Marks the cached entry stale; it refetches while observed.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun invalidate() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.StatusQueryHandle.INVALIDATE),
                UndraIds.Objects.StatusQueryHandle.INVALIDATE,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "StatusQueryHandle.invalidate")
        }
    }

    /**
     * Overrides how often the query polls while this handle observes it, counted from the end of a fetch.
     * The entry polls at the smallest interval among its observers; no interval clears this handle's override.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun setPollInterval(interval: Duration?) {
        try {
            val w = UndraWriter()
            codecOptionDuration.encode(w, interval)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.StatusQueryHandle.SET_POLL_INTERVAL),
                UndraIds.Objects.StatusQueryHandle.SET_POLL_INTERVAL,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "StatusQueryHandle.setPollInterval")
        }
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        try {
            when (signalId) {
                0u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionBool.decode(reader)
                        reader.finish()
                        _data.value = value
                    }
                }
                1u -> {
                    if (op == ChangeOp.FULL) {
                        val value = QueryStatus.decode(reader)
                        reader.finish()
                        _status.value = value
                    }
                }
                2u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionMarketError.decode(reader)
                        reader.finish()
                        _error.value = value
                    }
                }
                3u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Codecs.bool.decode(reader)
                        reader.finish()
                        _fetching.value = value
                    }
                }
                4u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionTimestamp.decode(reader)
                        reader.finish()
                        _updatedAt.value = value
                    }
                }
                else -> Unit
            }
        } catch (e: Exception) {
            core.report(e, "StatusQueryHandle.apply(signal: $signalId)")
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        operator fun invoke(ctx: UndraCore = UndraGoldenPolling.core): StatusQueryHandle = create(ctx)

        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraGoldenPolling.core): StatusQueryHandle {
            val handle = ctx.constructObject(UndraIds.Objects.StatusQueryHandle.TYPE_ID, UndraIds.Objects.StatusQueryHandle.NEW, ByteArray(0))
            return ctx.adopt(handle, ::StatusQueryHandle)
        }
    }
}

/**
 * Observes the `ticker` query (cache key `ticker/{symbol}`).
 * Constructing it registers an observer and fetches when the data is stale or missing.
 */
class TickerQueryHandle internal constructor(core: UndraCore, handle: Long) : UndraStore(core, handle) {
    private val _data: MutableStateFlow<Quote?> = signal(null)
    /** The latest successful result, if any. */
    val data: StateFlow<Quote?> = _data.asStateFlow()
    private val _status: MutableStateFlow<QueryStatus> = signal(QueryStatus.IDLE)
    /** Where the query is in its fetch lifecycle. */
    val status: StateFlow<QueryStatus> = _status.asStateFlow()
    private val _error: MutableStateFlow<MarketError?> = signal(null)
    /** The error of the latest failed fetch, cleared by the next success. */
    val error: StateFlow<MarketError?> = _error.asStateFlow()
    private val _fetching: MutableStateFlow<Boolean> = signal(false)
    /** Whether a fetch is in flight (also true while refetching stale data). */
    val fetching: StateFlow<Boolean> = _fetching.asStateFlow()
    private val _updatedAt: MutableStateFlow<Timestamp?> = signal(null)
    /** When `data` was last updated. */
    val updatedAt: StateFlow<Timestamp?> = _updatedAt.asStateFlow()

    /**
     * Fetches again now, even if the data is fresh.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun refetch() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TickerQueryHandle.REFETCH),
                UndraIds.Objects.TickerQueryHandle.REFETCH,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "TickerQueryHandle.refetch")
        }
    }

    /**
     * Marks the cached entry stale; it refetches while observed.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun invalidate() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TickerQueryHandle.INVALIDATE),
                UndraIds.Objects.TickerQueryHandle.INVALIDATE,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "TickerQueryHandle.invalidate")
        }
    }

    /**
     * Overrides how often the query polls while this handle observes it, counted from the end of a fetch.
     * The entry polls at the smallest interval among its observers; no interval clears this handle's override.
     * A failure is logged and passed to `LoadOptions.onError`; the method does not throw.
     */
    fun setPollInterval(interval: Duration?) {
        try {
            val w = UndraWriter()
            codecOptionDuration.encode(w, interval)
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.TickerQueryHandle.SET_POLL_INTERVAL),
                UndraIds.Objects.TickerQueryHandle.SET_POLL_INTERVAL,
                w.toByteArray(),
            )
        } catch (e: Exception) {
            this.core.report(e, "TickerQueryHandle.setPollInterval")
        }
    }

    override fun apply(signalId: UInt, op: ChangeOp, reader: UndraReader) {
        try {
            when (signalId) {
                0u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionQuote.decode(reader)
                        reader.finish()
                        _data.value = value
                    }
                }
                1u -> {
                    if (op == ChangeOp.FULL) {
                        val value = QueryStatus.decode(reader)
                        reader.finish()
                        _status.value = value
                    }
                }
                2u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionMarketError.decode(reader)
                        reader.finish()
                        _error.value = value
                    }
                }
                3u -> {
                    if (op == ChangeOp.FULL) {
                        val value = Codecs.bool.decode(reader)
                        reader.finish()
                        _fetching.value = value
                    }
                }
                4u -> {
                    if (op == ChangeOp.FULL) {
                        val value = codecOptionTimestamp.decode(reader)
                        reader.finish()
                        _updatedAt.value = value
                    }
                }
                else -> Unit
            }
        } catch (e: Exception) {
            core.report(e, "TickerQueryHandle.apply(signal: $signalId)")
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(symbol: String, ctx: UndraCore = UndraGoldenPolling.core): TickerQueryHandle {
            val w = UndraWriter()
            w.writeStr(symbol)
            val handle = ctx.constructObject(UndraIds.Objects.TickerQueryHandle.TYPE_ID, UndraIds.Objects.TickerQueryHandle.NEW, w.toByteArray())
            return ctx.adopt(handle, ::TickerQueryHandle)
        }
    }
}

/**
 * Runs the `buy` mutation.
 * @throws MarketError
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 * @throws CancellationException if the calling coroutine is cancelled.
 */
suspend fun buy(symbol: String, ctx: UndraCore = UndraGoldenPolling.core): Quote {
    val w = UndraWriter()
    w.writeStr(symbol)
    try {
        val body = ctx.call(
            CallTarget.FreeFunction(UndraIds.Queries.BUY),
            UndraIds.Queries.BUY,
            w.toByteArray(),
        )
        return Quote.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e, MarketError)
    }
}

private val codecOptionDuration = Codecs.option(Codecs.duration)
private val codecVecString = Codecs.vec(Codecs.string)
private val codecOptionVecString = Codecs.option(codecVecString)
private val codecOptionMarketError = Codecs.option(MarketError)
private val codecOptionTimestamp = Codecs.option(Codecs.timestamp)
private val codecOptionBool = Codecs.option(Codecs.bool)
private val codecOptionQuote = Codecs.option(Quote)
