// Generated by undra-bindgen from the Undra schema of `golden-polling` (schema hash 0xd1471391a5bc5da2). Do not edit.

package golden.polling

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

data class Quote(
    val symbol: String,
    val price: Double,
) : UndraRecord {
    companion object : UndraCodec<Quote> {
        override fun encode(w: UndraWriter, v: Quote) {
            w.writeStr(v.symbol)
            w.writeF64(v.price)
        }

        override fun decode(r: UndraReader): Quote = Quote(
            symbol = r.readStr(),
            price = r.readF64(),
        )
    }
}

/** The fetch state of a query (SPEC section 9). */
enum class QueryStatus(val index: UShort) : UndraEnum {
    /** No fetch has started. */
    IDLE(0u),
    /** A fetch is in flight. */
    FETCHING(1u),
    /** The latest fetch succeeded. */
    SUCCESS(2u),
    /** The latest fetch failed. */
    ERROR(3u);

    companion object : UndraCodec<QueryStatus> {
        override fun encode(w: UndraWriter, v: QueryStatus) = w.writeU16(v.index)

        override fun decode(r: UndraReader): QueryStatus {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> IDLE
                1 -> FETCHING
                2 -> SUCCESS
                3 -> ERROR
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "QueryStatus")
            }
        }
    }
}
