// Generated by undra-bindgen from the Undra schema of `golden-object-graph` (schema hash 0x63ce15b6ad53100b). Do not edit.

package golden.object_graph

import dev.undra.runtime.UndraException
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

sealed class MailError(message: String) : UndraException(message) {
    data object NoThread : MailError("no such thread")

    companion object : UndraCodec<MailError> {
        override fun encode(w: UndraWriter, v: MailError) {
            when (v) {
                NoThread -> w.writeU16(0u)
            }
        }

        override fun decode(r: UndraReader): MailError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> NoThread
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "MailError")
            }
        }
    }
}
