// Generated by undra-bindgen from the Undra schema of `golden-object-graph` (schema hash 0x9d413883b026d02f). Do not edit.

package golden.object_graph

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0x9d413883b026d02fuL
    const val NAMESPACE: String = "golden_object_graph"

    object Objects {
        object Account {
            const val TYPE_ID: UInt = 0x59f8a2fcu
            const val NEW: UInt = 0xe01ae200u
            const val MAILBOX: UInt = 0x24623112u
            const val OPEN_THREAD: UInt = 0x87b7ff03u
            const val MOVE_TO: UInt = 0xde2a315du
            const val DRAFTS: UInt = 0xbf5232f2u
            const val MAILBOXES: UInt = 0x95c6b5d2u
            const val CHAT: UInt = 0x0c44f808u
            const val MERGE: UInt = 0x15297446u
            const val FIND_THREAD: UInt = 0xb8c641aeu
        }
        object Mailbox {
            const val TYPE_ID: UInt = 0xb211566bu
            const val NAME: UInt = 0x51436a9cu
        }
        object Thread {
            const val TYPE_ID: UInt = 0xea904991u
            const val ID: UInt = 0xe5a9b838u
        }
        object ChatStore {
            const val TYPE_ID: UInt = 0x98ddf884u
            const val NEW: UInt = 0x70c95548u
            const val SEND: UInt = 0xbcb1a2c4u
        }
    }

    object Functions {
        const val MAILBOX_OF: UInt = 0xebbc4349u
    }

    object Ports {}

    object Queries {}
}
