// Generated by undra-bindgen from the Undra schema of `golden-object-graph` (schema hash 0xb21e0bbe0d6ac9da). Do not edit.

package golden.object_graph

import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter

/** A message in a chat. */
data class Message(
    val id: UInt,
    val text: String,
) : UndraRecord {
    companion object : UndraCodec<Message> {
        override fun encode(w: UndraWriter, v: Message) {
            w.writeU32(v.id)
            w.writeStr(v.text)
        }

        override fun decode(r: UndraReader): Message = Message(id = r.readU32(), text = r.readStr())
    }
}
