// Generated by keel-bindgen from the Keel schema of `golden-ports` (schema hash 0xdbafb672e723bbc5). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash to pass to `KeelCore.load` as `expectedSchemaHash`.
 */
export const KeelIds = {
  schemaHash: 0xdbafb672e723bbc5n,
  Objects: {
  },
  Functions: {
  },
  Ports: {
    Clock: {
      portId: 0xcd99c48e,
      nowMs: 0xccc94d90,
      monotonicNs: 0x2cb2b4bf,
      log: 0xd553ab15,
    },
    Connectivity: {
      portId: 0x1feff6ff,
      changed: 0xb4f2a010,
      reset: 0x3cb795a3,
    },
    Http: {
      portId: 0x1ebeb908,
      request: 0x6b14df26,
    },
    Kv: {
      portId: 0x5389110d,
      get: 0xf050bb1a,
      set: 0x62427856,
      list: 0x32f1d03a,
      flush: 0x13b349c0,
    },
  },
  Queries: {
  },
} as const;
