// Generated by keel-bindgen from the Keel schema of `golden-ports` (schema hash 0xdbafb672e723bbc5). Do not edit.

import {
  KeelCore,
  type KeelPort,
  KeelPortError,
  KeelReader,
  KeelWriter,
  type PortImpl,
  codecs,
  encodeValue,
} from "@keel/runtime";
import { FsError, FsErrorCodec, HttpError, HttpErrorCodec } from "./errors.js";
import { KeelIds } from "./ids.js";
import {
  type HttpRequest,
  HttpRequestCodec,
  type HttpResponse,
  HttpResponseCodec,
  type NetKind,
  NetKindCodec,
} from "./types.js";

/** Wall-clock and monotonic time. */
export interface Clock extends KeelPort {
  /** Milliseconds since the epoch. */
  nowMs(): bigint;
  monotonicNs(): bigint;
  /** Logs a line. */
  log(level: number, target: string, message: string): void;
}

/** Adapts an implementation of `Clock` to `KeelCore.registerPort(KeelIds.Ports.Clock.portId, ..)`. */
export function clockPortImpl(impl: Clock): PortImpl {
  return {
    sync: true,
    methods: {
      [KeelIds.Ports.Clock.nowMs]: () => {
        return encodeValue(codecs.i64, impl.nowMs());
      },
      [KeelIds.Ports.Clock.monotonicNs]: () => {
        return encodeValue(codecs.u64, impl.monotonicNs());
      },
      [KeelIds.Ports.Clock.log]: (args) => {
        const r = new KeelReader(args);
        const level = r.readU8();
        const target = r.readStr();
        const message = r.readStr();
        r.finish();
        impl.log(level, target, message);
        return new Uint8Array(0);
      },
    },
  };
}

/**
 * Connectivity changes, sent by the platform.
 * Sends the events of this port from the host to the core.
 */
export class ConnectivityEvents {
  constructor(private readonly core: KeelCore = KeelCore.shared) {}

  /** The network changed. */
  changed(online: boolean, kind: NetKind): void {
    const w = new KeelWriter();
    w.writeBool(online);
    NetKindCodec.encode(w, kind);
    this.core.event(
      KeelIds.Ports.Connectivity.portId,
      KeelIds.Ports.Connectivity.changed,
      w.finish(),
    );
  }

  reset(): void {
    this.core.event(
      KeelIds.Ports.Connectivity.portId,
      KeelIds.Ports.Connectivity.reset,
      new Uint8Array(0),
    );
  }
}

/** Performs HTTP requests. */
export interface Http extends KeelPort {
  /**
   * Sends a request.
   * @throws {HttpError}
   */
  request(req: HttpRequest): Promise<HttpResponse>;
}

/** Adapts an implementation of `Http` to `KeelCore.registerPort(KeelIds.Ports.Http.portId, ..)`. */
export function httpPortImpl(impl: Http): PortImpl {
  return {
    sync: false,
    methods: {
      [KeelIds.Ports.Http.request]: async (args) => {
        const r = new KeelReader(args);
        const req = HttpRequestCodec.decode(r);
        r.finish();
        try {
          return encodeValue(HttpResponseCodec, await impl.request(req));
        } catch (error) {
          if (error instanceof HttpError) {
            throw new KeelPortError(encodeValue(HttpErrorCodec, error));
          }
          throw error;
        }
      },
    },
  };
}

/** A key-value store. */
export interface Kv extends KeelPort {
  get(key: string): Promise<Uint8Array | null>;
  set(key: string, value: Uint8Array): Promise<void>;
  list(prefix: string): Promise<string[]>;
  /**
   * A synchronous method on an async port.
   * @throws {FsError}
   */
  flush(): void;
}

/** Adapts an implementation of `Kv` to `KeelCore.registerPort(KeelIds.Ports.Kv.portId, ..)`. */
export function kvPortImpl(impl: Kv): PortImpl {
  return {
    sync: false,
    methods: {
      [KeelIds.Ports.Kv.get]: async (args) => {
        const r = new KeelReader(args);
        const key = r.readStr();
        r.finish();
        return encodeValue(optionBytes, await impl.get(key));
      },
      [KeelIds.Ports.Kv.set]: async (args) => {
        const r = new KeelReader(args);
        const key = r.readStr();
        const value = codecs.bytes.decode(r);
        r.finish();
        await impl.set(key, value);
        return new Uint8Array(0);
      },
      [KeelIds.Ports.Kv.list]: async (args) => {
        const r = new KeelReader(args);
        const prefix = r.readStr();
        r.finish();
        return encodeValue(vecString, await impl.list(prefix));
      },
      [KeelIds.Ports.Kv.flush]: async () => {
        try {
          impl.flush();
          return new Uint8Array(0);
        } catch (error) {
          if (error instanceof FsError) {
            throw new KeelPortError(encodeValue(FsErrorCodec, error));
          }
          throw error;
        }
      },
    },
  };
}

const optionBytes = codecs.option(codecs.bytes);
const vecString = codecs.vec(codecs.string);
