// Generated by keel-bindgen from the Keel schema of `golden-ports` (schema hash 0xde22690132b0e949). Do not edit.

import { type Codec, WireError, codecs } from "@keel/runtime";

export interface HttpRequest {
  url: string;
  headers: Map<string, string>;
  body: Uint8Array | null;
}

export const HttpRequestCodec: Codec<HttpRequest> = {
  encode(w, v) {
    w.writeStr(v.url);
    mapStringString.encode(w, v.headers);
    optionBytes.encode(w, v.body);
  },
  decode(r) {
    return {
      url: r.readStr(),
      headers: mapStringString.decode(r),
      body: optionBytes.decode(r),
    };
  },
};

export interface HttpResponse {
  status: number;
  body: Uint8Array;
}

export const HttpResponseCodec: Codec<HttpResponse> = {
  encode(w, v) {
    w.writeU16(v.status);
    w.writeBytes(v.body);
  },
  decode(r) {
    return {
      status: r.readU16(),
      body: codecs.bytes.decode(r),
    };
  },
};

export type NetKind = "wifi" | "cellular" | "none";

export const NetKindCodec: Codec<NetKind> = {
  encode(w, v) {
    switch (v) {
      case "wifi":
        w.writeU16(0);
        break;
      case "cellular":
        w.writeU16(1);
        break;
      case "none":
        w.writeU16(2);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return "wifi";
      case 1:
        return "cellular";
      case 2:
        return "none";
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "NetKind" });
    }
  },
};

const mapStringString = codecs.map(codecs.string, codecs.string);
const optionBytes = codecs.option(codecs.bytes);
