// Generated by undra-bindgen from the Undra schema of `golden-generics` (schema hash 0xa08c3e607ebcebbe). Do not edit.

import { type Codec, UndraError, WireError } from "@undra/runtime";

export type BrowseErrorKind = "offline";

export abstract class BrowseError extends UndraError {
  declare readonly kind: BrowseErrorKind;
}

export namespace BrowseError {
  export class Offline extends BrowseError {
    declare readonly kind: "offline";

    constructor() {
      super("offline", "offline");
    }
  }
}

export const BrowseErrorCodec: Codec<BrowseError> = {
  encode(w, v) {
    if (v instanceof BrowseError.Offline) {
      w.writeU16(0);
    } else {
      throw new TypeError(`unknown BrowseError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new BrowseError.Offline();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "BrowseError" });
    }
  },
};
