// Generated by undra-bindgen from the Undra schema of `golden-generics` (schema hash 0xa08c3e607ebcebbe). Do not edit.

import {
  CallTarget,
  ChangeOp,
  Signal,
  UndraCallError,
  UndraCore,
  UndraStore,
  UndraWriter,
  adopt,
  codecs,
  decodeValue,
} from "@undra/runtime";
import { UndraGoldenGenerics } from "./core.js";
import { BrowseErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import {
  type LoadableTodo,
  LoadableTodoCodec,
  type LoadableUser,
  LoadableUserCodec,
  type TodoPage,
  TodoPageCodec,
  type UserPage,
  UserPageCodec,
} from "./types.js";

/** Pages through todos and users. */
export class Browser extends UndraStore {
  readonly todos: Signal<TodoPage> = new Signal<TodoPage>({ items: [], next: null });
  readonly users: Signal<UserPage> = new Signal<UserPage>({ items: [], next: null });
  readonly selected: Signal<LoadableTodo> = new Signal<LoadableTodo>({ kind: "loading" });
  readonly owner: Signal<LoadableUser> = new Signal<LoadableUser>({ kind: "loading" });

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.todos, this.users, this.selected, this.owner];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraGoldenGenerics.core): Promise<Browser> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Browser.typeId,
        UndraIds.Objects.Browser.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = adopt(core, handle, Browser);
    await store._observeAll();
    return store;
  }

  /**
   * @throws {BrowseError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async loadTodos(cursor: string | null, signal?: AbortSignal): Promise<TodoPage> {
    const w = new UndraWriter();
    optionString.encode(w, cursor);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Browser.loadTodos,
        w.finish(),
        signal,
      );
      return decodeValue(TodoPageCodec, body);
    } catch (error) {
      throw UndraCallError.mapped(error, BrowseErrorCodec);
    }
  }

  /**
   * @throws {BrowseError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async loadUsers(cursor: string | null, signal?: AbortSignal): Promise<UserPage> {
    const w = new UndraWriter();
    optionString.encode(w, cursor);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Browser.loadUsers,
        w.finish(),
        signal,
      );
      return decodeValue(UserPageCodec, body);
    } catch (error) {
      throw UndraCallError.mapped(error, BrowseErrorCodec);
    }
  }

  /** A failure is logged and passed to `onError`; the returned promise never rejects. */
  async select(todo: LoadableTodo): Promise<void> {
    try {
      const w = new UndraWriter();
      LoadableTodoCodec.encode(w, todo);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Browser.select,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "Browser.select");
    }
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.todos._set(decodeValue(TodoPageCodec, value));
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.users._set(decodeValue(UserPageCodec, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.selected._set(decodeValue(LoadableTodoCodec, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.owner._set(decodeValue(LoadableUserCodec, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `Browser.apply(signal: ${signalId})`);
    }
  }
}

const optionString = codecs.option(codecs.string);
