// Generated by undra-bindgen from the Undra schema of `golden-generics` (schema hash 0xa08c3e607ebcebbe). Do not edit.

import { type Codec, WireError, codecs } from "@undra/runtime";

export interface Todo {
  id: number;
  title: string;
}

export const TodoCodec: Codec<Todo> = {
  encode(w, v) {
    w.writeU32(v.id);
    w.writeStr(v.title);
  },
  decode(r) {
    return {
      id: r.readU32(),
      title: r.readStr(),
    };
  },
};

/** A page of todos: `Page<Todo>`. */
export interface TodoPage {
  items: Todo[];
  next: string | null;
}

export const TodoPageCodec: Codec<TodoPage> = {
  encode(w, v) {
    vecTodo.encode(w, v.items);
    optionString.encode(w, v.next);
  },
  decode(r) {
    return {
      items: vecTodo.decode(r),
      next: optionString.decode(r),
    };
  },
};

export interface User {
  id: number;
  name: string;
}

export const UserCodec: Codec<User> = {
  encode(w, v) {
    w.writeU32(v.id);
    w.writeStr(v.name);
  },
  decode(r) {
    return {
      id: r.readU32(),
      name: r.readStr(),
    };
  },
};

/** A page of users: `Page<User>`. */
export interface UserPage {
  items: User[];
  next: string | null;
}

export const UserPageCodec: Codec<UserPage> = {
  encode(w, v) {
    vecUser.encode(w, v.items);
    optionString.encode(w, v.next);
  },
  decode(r) {
    return {
      items: vecUser.decode(r),
      next: optionString.decode(r),
    };
  },
};

/** A todo on its way: `Loadable<Todo>`. */
export type LoadableTodo =
  | { kind: "loading" }
  | { kind: "loaded"; value: Todo }
  | { kind: "failed"; value: string };

export const LoadableTodoCodec: Codec<LoadableTodo> = {
  encode(w, v) {
    switch (v.kind) {
      case "loading":
        w.writeU16(0);
        break;
      case "loaded":
        w.writeU16(1);
        TodoCodec.encode(w, v.value);
        break;
      case "failed":
        w.writeU16(2);
        w.writeStr(v.value);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return { kind: "loading" };
      case 1:
        return {
          kind: "loaded",
          value: TodoCodec.decode(r),
        };
      case 2:
        return {
          kind: "failed",
          value: r.readStr(),
        };
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "LoadableTodo" });
    }
  },
};

/** A user on its way: `Loadable<User>`. */
export type LoadableUser =
  | { kind: "loading" }
  | { kind: "loaded"; value: User }
  | { kind: "failed"; value: string };

export const LoadableUserCodec: Codec<LoadableUser> = {
  encode(w, v) {
    switch (v.kind) {
      case "loading":
        w.writeU16(0);
        break;
      case "loaded":
        w.writeU16(1);
        UserCodec.encode(w, v.value);
        break;
      case "failed":
        w.writeU16(2);
        w.writeStr(v.value);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return { kind: "loading" };
      case 1:
        return {
          kind: "loaded",
          value: UserCodec.decode(r),
        };
      case 2:
        return {
          kind: "failed",
          value: r.readStr(),
        };
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "LoadableUser" });
    }
  },
};

const vecTodo = codecs.vec(TodoCodec);
const optionString = codecs.option(codecs.string);
const vecUser = codecs.vec(UserCodec);
