// Generated by undra-bindgen from the Undra schema of `golden-decimal` (schema hash 0x166092f7b788cc34). Do not edit.

import { type Codec, UndraError, WireError } from "@undra/runtime";

export type PayErrorKind = "declined";

export abstract class PayError extends UndraError {
  declare readonly kind: PayErrorKind;
}

export namespace PayError {
  export class Declined extends PayError {
    declare readonly kind: "declined";

    constructor() {
      super("declined", "declined");
    }
  }
}

export const PayErrorCodec: Codec<PayError> = {
  encode(w, v) {
    if (v instanceof PayError.Declined) {
      w.writeU16(0);
    } else {
      throw new TypeError(`unknown PayError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new PayError.Declined();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "PayError" });
    }
  },
};
