// Generated by undra-bindgen from the Undra schema of `golden-decimal` (schema hash 0x166092f7b788cc34). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
export const UndraIds = {
  schemaHash: 0x166092f7b788cc34n,
  namespace: "golden_decimal",
  Objects: {
    Till: {
      typeId: 0xfae13cee,
      new: 0xe5cea35e,
      charge: 0x362c1b2c,
      refund: 0xc486bc32,
      totals: 0x612e5d8b,
    },
    PriceOfQueryHandle: {
      typeId: 0x0d61d8d0,
      new: 0x0d61d8d0,
      refetch: 0x21d1b9e2,
      invalidate: 0x44cec2fa,
      setPollInterval: 0xe327e53b,
    },
  },
  Functions: {
    quote: 0xe0ba36ab,
  },
  Ports: {
  },
  Queries: {
    priceOf: 0x0d61d8d0,
  },
} as const;
