// Generated by undra-bindgen from the Undra schema of `golden-decimal` (schema hash 0x166092f7b788cc34). Do not edit.

import {
  CallTarget,
  ChangeOp,
  type Codec,
  Decimal,
  Signal,
  UndraCallError,
  UndraCore,
  UndraStore,
  UndraWriter,
  adopt,
  codecs,
  decimalCodec,
  decodeValue,
} from "@undra/runtime";
import { UndraGoldenDecimal } from "./core.js";
import { PayErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import { type Invoice, InvoiceCodec, Price, PriceCodec } from "./types.js";

/** Takes payments. */
export class Till extends UndraStore {
  readonly balance: Signal<Decimal> = new Signal<Decimal>(Decimal.ZERO);
  readonly last: Signal<Price | null> = new Signal<Price | null>(null);
  readonly history: Signal<Decimal[]> = new Signal<Decimal[]>([]);
  readonly invoice: Signal<Invoice> = new Signal<Invoice>({ total: Decimal.ZERO, lines: [], discount: null, price: Price(Decimal.ZERO), bySku: new Map(), prices: new Map(), tax: Decimal.ZERO });

  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.balance, this.last, this.history, this.invoice];
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraGoldenDecimal.core): Promise<Till> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Till.typeId,
        UndraIds.Objects.Till.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    const store = adopt(core, handle, Till);
    await store._observeAll();
    return store;
  }

  /**
   * Takes `amount` and returns the balance.
   * @throws {PayError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async charge(amount: Decimal, signal?: AbortSignal): Promise<Decimal> {
    const w = new UndraWriter();
    decimalCodec.encode(w, amount);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Till.charge,
        w.finish(),
        signal,
      );
      return decodeValue(decimalCodec, body);
    } catch (error) {
      throw UndraCallError.mapped(error, PayErrorCodec);
    }
  }

  /** A failure is logged and passed to `onError`; the returned promise never rejects. */
  async refund(amount: Decimal | null): Promise<void> {
    try {
      const w = new UndraWriter();
      optionDecimal.encode(w, amount);
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Till.refund,
        w.finish(),
      );
    } catch (error) {
      this.core.report(error, "Till.refund");
    }
  }

  /** Iterating throws UndraCallError; leaving the loop early ends the stream quietly. */
  totals(): AsyncIterable<Decimal> {
    const source = this.core.stream(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.Till.totals,
      new Uint8Array(0),
    );
    return decodeStream(source, decimalCodec, (error) => UndraCallError.mappedStream(error));
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    try {
      switch (signalId) {
        case 0:
          if (op === ChangeOp.FullValue) {
            this.balance._set(decodeValue(decimalCodec, value));
          }
          break;
        case 1:
          if (op === ChangeOp.FullValue) {
            this.last._set(decodeValue(optionPrice, value));
          }
          break;
        case 2:
          if (op === ChangeOp.FullValue) {
            this.history._set(decodeValue(vecDecimal, value));
          }
          break;
        case 3:
          if (op === ChangeOp.FullValue) {
            this.invoice._set(decodeValue(InvoiceCodec, value));
          }
          break;
        default:
          break;
      }
    } catch (error) {
      this.core.report(error, `Till.apply(signal: ${signalId})`);
    }
  }
}

/** Decodes every item of a core stream; a failure of the stream or of an item goes through `mapError`. */
async function* decodeStream<T>(
  source: AsyncIterable<Uint8Array>,
  codec: Codec<T>,
  mapError: (error: unknown) => unknown,
): AsyncGenerator<T, void, undefined> {
  try {
    for await (const body of source) yield decodeValue(codec, body);
  } catch (error) {
    throw mapError(error);
  }
}

const optionDecimal = codecs.option(decimalCodec);
const optionPrice = codecs.option(PriceCodec);
const vecDecimal = codecs.vec(decimalCodec);
