// Generated by keel-bindgen from the Keel schema of `golden-queries` (schema hash 0x367c6bc54db0b31d). Do not edit.

import { type Codec, WireError, codecs } from "@keel/runtime";

export interface Page {
  items: Todo[];
  total: bigint;
}

export const PageCodec: Codec<Page> = {
  encode(w, v) {
    vecTodo.encode(w, v.items);
    w.writeU64(v.total);
  },
  decode(r) {
    return {
      items: vecTodo.decode(r),
      total: r.readU64(),
    };
  },
};

export interface Todo {
  id: string;
  title: string;
}

export const TodoCodec: Codec<Todo> = {
  encode(w, v) {
    w.writeUuid(v.id);
    w.writeStr(v.title);
  },
  decode(r) {
    return {
      id: r.readUuid(),
      title: r.readStr(),
    };
  },
};

/** The fetch state of a query (SPEC section 9). */
export type QueryStatus =
  /** No fetch has started. */
  | "idle"
  /** A fetch is in flight. */
  | "fetching"
  /** The latest fetch succeeded. */
  | "success"
  /** The latest fetch failed. */
  | "error";

export const QueryStatusCodec: Codec<QueryStatus> = {
  encode(w, v) {
    switch (v) {
      case "idle":
        w.writeU16(0);
        break;
      case "fetching":
        w.writeU16(1);
        break;
      case "success":
        w.writeU16(2);
        break;
      case "error":
        w.writeU16(3);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return "idle";
      case 1:
        return "fetching";
      case 2:
        return "success";
      case 3:
        return "error";
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "QueryStatus" });
    }
  },
};

const vecTodo = codecs.vec(TodoCodec);
