// Generated by keel-bindgen from the Keel schema of `golden-queries` (schema hash 0x367c6bc54db0b31d). Do not edit.

package golden.queries

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash to pass to `KeelCore.load` as `expectedSchemaHash`.
 */
object KeelIds {
    const val SCHEMA_HASH: ULong = 0x367c6bc54db0b31duL

    object Objects {
        object TodoByIdQueryHandle {
            const val TYPE_ID: UInt = 0x2bb5eff3u
            const val NEW: UInt = 0x2bb5eff3u
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
        }
        object TodoCountQueryHandle {
            const val TYPE_ID: UInt = 0xcb26daa7u
            const val NEW: UInt = 0xcb26daa7u
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
        }
        object TodosQueryHandle {
            const val TYPE_ID: UInt = 0x54209c7cu
            const val NEW: UInt = 0x54209c7cu
            const val REFETCH: UInt = 0x21d1b9e2u
            const val INVALIDATE: UInt = 0x44cec2fau
        }
    }

    object Functions {}

    object Ports {}

    object Queries {
        const val ADD_TODO: UInt = 0x4abb0ec8u
        const val CLEAR_TODOS: UInt = 0xd0e95d23u
        const val TODO_BY_ID: UInt = 0x2bb5eff3u
        const val TODO_COUNT: UInt = 0xcb26daa7u
        const val TODOS: UInt = 0x54209c7cu
    }
}
