// swift-tools-version: 6.0
// Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
import PackageDescription

let package = Package(
    name: "GoldenStores",
    platforms: [.iOS(.v17), .macOS(.v14)],
    products: [.library(name: "GoldenStores", targets: ["GoldenStores"])],
    dependencies: [.package(url: "https://github.com/shreypdev/undra", from: "<version>")],
    targets: [
        // Declares the core's entry point; the core itself is linked into the app.
        .target(name: "GoldenStoresCoreFFI", path: "Sources/GoldenStoresCoreFFI"),
        .target(
            name: "GoldenStores",
            dependencies: [
                "GoldenStoresCoreFFI",
                .product(name: "UndraRuntime", package: "undra"),
            ],
            path: "Sources/GoldenStores"
        ),
    ],
    swiftLanguageModes: [.v6]
)
