// Generated by undra-bindgen from the Undra schema of `golden-enums` (schema hash 0x2533f60443b3d23b). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.enums

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

/** Which todos the list shows. */
enum class Filter(val index: UShort) : UndraEnum {
    /** Everything. */
    ALL(0u),
    /** Not done yet. */
    ACTIVE(1u),
    /** Finished. */
    DONE(2u);

    companion object : UndraCodec<Filter> {
        override fun encode(w: UndraWriter, v: Filter) = w.writeU16(v.index)

        override fun decode(r: UndraReader): Filter {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> ALL
                1 -> ACTIVE
                2 -> DONE
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Filter")
            }
        }
    }
}

enum class NetKind(val index: UShort) : UndraEnum {
    WIFI(0u),
    CELLULAR(1u),
    NONE(2u),
    DEFAULT(3u);

    companion object : UndraCodec<NetKind> {
        override fun encode(w: UndraWriter, v: NetKind) = w.writeU16(v.index)

        override fun decode(r: UndraReader): NetKind {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> WIFI
                1 -> CELLULAR
                2 -> NONE
                3 -> DEFAULT
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "NetKind")
            }
        }
    }
}

/** A shape with data. */
sealed interface Shape : UndraEnum {
    /** A circle. */
    data class Circle(val radius: Double) : Shape
    data class Rect(val value0: Double, val value1: Double) : Shape
    data class Labelled(val label: String, val kind: Int, val inner: Filter?) : Shape
    data class Single(val value: String) : Shape
    data object Empty : Shape

    companion object : UndraCodec<Shape> {
        override fun encode(w: UndraWriter, v: Shape) {
            when (v) {
                is Circle -> {
                    w.writeU16(0u)
                    w.writeF64(v.radius)
                }
                is Rect -> {
                    w.writeU16(1u)
                    w.writeF64(v.value0)
                    w.writeF64(v.value1)
                }
                is Labelled -> {
                    w.writeU16(2u)
                    w.writeStr(v.label)
                    w.writeI32(v.kind)
                    codecOptionFilter.encode(w, v.inner)
                }
                is Single -> {
                    w.writeU16(3u)
                    w.writeStr(v.value)
                }
                Empty -> w.writeU16(4u)
            }
        }

        override fun decode(r: UndraReader): Shape {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Circle(radius = r.readF64())
                1 -> Rect(value0 = r.readF64(), value1 = r.readF64())
                2 -> Labelled(
                    label = r.readStr(),
                    kind = r.readI32(),
                    inner = codecOptionFilter.decode(r),
                )
                3 -> Single(value = r.readStr())
                4 -> Empty
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Shape")
            }
        }
    }
}

/** Variant indexes need not be dense. */
enum class Sparse(val index: UShort) : UndraEnum {
    FIRST(1u),
    SECOND(7u);

    companion object : UndraCodec<Sparse> {
        override fun encode(w: UndraWriter, v: Sparse) = w.writeU16(v.index)

        override fun decode(r: UndraReader): Sparse {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                1 -> FIRST
                7 -> SECOND
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Sparse")
            }
        }
    }
}

/** A JSON-like value: variant names shadow type names. */
sealed interface Value : UndraEnum {
    data class String(val value: kotlin.String) : Value
    data class Int(val value: Long) : Value
    data class Bool(val value: Boolean) : Value
    data class List(val value: kotlin.collections.List<Value>) : Value
    data class Shape(val value: golden.enums.Shape) : Value
    data class Filter(val value: golden.enums.Filter) : Value
    data object Null : Value

    companion object : UndraCodec<Value> {
        override fun encode(w: UndraWriter, v: Value) {
            when (v) {
                is String -> {
                    w.writeU16(0u)
                    w.writeStr(v.value)
                }
                is Int -> {
                    w.writeU16(1u)
                    w.writeI64(v.value)
                }
                is Bool -> {
                    w.writeU16(2u)
                    w.writeBool(v.value)
                }
                is List -> {
                    w.writeU16(3u)
                    codecVecValue.encode(w, v.value)
                }
                is Shape -> {
                    w.writeU16(4u)
                    golden.enums.Shape.encode(w, v.value)
                }
                is Filter -> {
                    w.writeU16(5u)
                    golden.enums.Filter.encode(w, v.value)
                }
                Null -> w.writeU16(6u)
            }
        }

        override fun decode(r: UndraReader): Value {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> String(value = r.readStr())
                1 -> Int(value = r.readI64())
                2 -> Bool(value = r.readBool())
                3 -> List(value = codecVecValue.decode(r))
                4 -> Shape(value = golden.enums.Shape.decode(r))
                5 -> Filter(value = golden.enums.Filter.decode(r))
                6 -> Null
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Value")
            }
        }
    }
}

private val codecOptionFilter = Codecs.option(Filter)
private val codecVecValue = Codecs.vec(Value)
