// Generated by keel-bindgen from the Keel schema of `golden-stores` (schema hash 0x96c553ec019df03c). Do not edit.

import {
  ALL_SIGNALS,
  CallTarget,
  ChangeOp,
  type Codec,
  type Duration,
  KeelCore,
  KeelReader,
  KeelStore,
  KeelWriter,
  PatchError,
  Signal,
  type Timestamp,
  applyPatch,
  codecs,
  decodePatch,
  decodeValue,
} from "@keel/runtime";
import { TodoError, TodoErrorCodec } from "./errors.js";
import { KeelIds } from "./ids.js";
import {
  type Counter,
  CounterCodec,
  type Filter,
  FilterCodec,
  type Todo,
  TodoCodec,
} from "./types.js";

/** A store with a single signal and a constructor argument. */
export class Clock extends KeelStore {
  readonly now: Signal<Timestamp> = new Signal<Timestamp>(0);

  private constructor(core: KeelCore, handle: bigint) {
    super(core, handle);
    this._signals = [this.now];
  }

  static async create(zone: string, core: KeelCore = KeelCore.shared): Promise<Clock> {
    const w = new KeelWriter();
    w.writeStr(zone);
    const handle = await core.construct(
      KeelIds.Objects.Clock.typeId,
      KeelIds.Objects.Clock.new,
      w.finish(),
    );
    const store = new Clock(core, handle);
    await core.observe(handle, ALL_SIGNALS, true);
    return store;
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    switch (signalId) {
      case 0:
        if (op === ChangeOp.FullValue) {
          this.now._set(decodeValue(codecs.timestamp, value));
        }
        break;
      default:
        break;
    }
  }
}

/** The todo list. */
export class Todos extends KeelStore {
  readonly todos: Signal<Todo[]> = new Signal<Todo[]>([]);
  readonly filter: Signal<Filter> = new Signal<Filter>("all");
  /** Computed by the core; read-only. */
  readonly visible: Signal<Todo[]> = new Signal<Todo[]>([]);
  /** Computed by the core; read-only. */
  readonly remaining: Signal<number> = new Signal<number>(0);
  readonly selected: Signal<Todo | null> = new Signal<Todo | null>(null);
  readonly title: Signal<string> = new Signal<string>("");
  readonly counter: Signal<Counter> = new Signal<Counter>({ label: "", n: 0 });
  readonly tags: Signal<Map<string, number>> = new Signal<Map<string, number>>(new Map());
  readonly lastError: Signal<TodoError | null> = new Signal<TodoError | null>(null);
  readonly elapsed: Signal<Duration> = new Signal<Duration>(0);
  readonly created: Signal<Timestamp> = new Signal<Timestamp>(0);
  readonly blob: Signal<Uint8Array> = new Signal<Uint8Array>(new Uint8Array(0));
  readonly total: Signal<bigint> = new Signal<bigint>(0n);
  readonly default: Signal<boolean> = new Signal<boolean>(false);
  readonly uuid: Signal<string> = new Signal<string>("00000000-0000-0000-0000-000000000000");

  private constructor(core: KeelCore, handle: bigint) {
    super(core, handle);
    this._signals = [
      this.todos,
      this.filter,
      this.visible,
      this.remaining,
      this.selected,
      this.title,
      this.counter,
      this.tags,
      this.lastError,
      this.elapsed,
      this.created,
      this.blob,
      this.total,
      this.default,
      this.uuid,
    ];
  }

  static async create(core: KeelCore = KeelCore.shared): Promise<Todos> {
    const handle = await core.construct(
      KeelIds.Objects.Todos.typeId,
      KeelIds.Objects.Todos.new,
      new Uint8Array(0),
    );
    const store = new Todos(core, handle);
    await core.observe(handle, ALL_SIGNALS, true);
    return store;
  }

  /** @throws {TodoError} */
  static async open(path: string, core: KeelCore = KeelCore.shared): Promise<Todos> {
    const w = new KeelWriter();
    w.writeStr(path);
    let handle: bigint;
    try {
      handle = await core.construct(
        KeelIds.Objects.Todos.typeId,
        KeelIds.Objects.Todos.open,
        w.finish(),
      );
    } catch (error) {
      throw TodoError.fromReply(error);
    }
    const store = new Todos(core, handle);
    await core.observe(handle, ALL_SIGNALS, true);
    return store;
  }

  /**
   * Adds a todo.
   * @throws {TodoError}
   */
  async add(title: string, signal?: AbortSignal): Promise<Todo> {
    const w = new KeelWriter();
    w.writeStr(title);
    let body: Uint8Array;
    try {
      body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        KeelIds.Objects.Todos.add,
        w.finish(),
        signal,
      );
    } catch (error) {
      throw TodoError.fromReply(error);
    }
    return decodeValue(TodoCodec, body);
  }

  changes(): AsyncIterable<Todo> {
    const source = this.core.stream(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      KeelIds.Objects.Todos.changes,
      new Uint8Array(0),
    );
    return decodeStream(source, TodoCodec);
  }

  async remainingAfter(id: string): Promise<number> {
    const w = new KeelWriter();
    w.writeUuid(id);
    const body = await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      KeelIds.Objects.Todos.remainingAfter,
      w.finish(),
    );
    return decodeValue(codecs.u32, body);
  }

  /** Shows only the todos matching `f`. */
  async setFilter(f: Filter): Promise<void> {
    const w = new KeelWriter();
    FilterCodec.encode(w, f);
    await this.core.call(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      KeelIds.Objects.Todos.setFilter,
      w.finish(),
    );
  }

  protected override _apply(signalId: number, op: ChangeOp, value: Uint8Array): void {
    switch (signalId) {
      case 0:
        if (op === ChangeOp.FullValue) {
          this.todos._set(decodeValue(vecTodo, value));
        } else if (op === ChangeOp.KeyedPatch) {
          const r = new KeelReader(value);
          const ops = decodePatch(r, TodoCodec);
          r.finish();
          try {
            this.todos._set(applyPatch(this.todos.peek(), ops));
          } catch (error) {
            if (!(error instanceof PatchError)) throw error;
            this._resync(0);
          }
        }
        break;
      case 1:
        if (op === ChangeOp.FullValue) {
          this.filter._set(decodeValue(FilterCodec, value));
        }
        break;
      case 2:
        if (op === ChangeOp.FullValue) {
          this.visible._set(decodeValue(vecTodo, value));
        } else if (op === ChangeOp.KeyedPatch) {
          const r = new KeelReader(value);
          const ops = decodePatch(r, TodoCodec);
          r.finish();
          try {
            this.visible._set(applyPatch(this.visible.peek(), ops));
          } catch (error) {
            if (!(error instanceof PatchError)) throw error;
            this._resync(2);
          }
        }
        break;
      case 3:
        if (op === ChangeOp.FullValue) {
          this.remaining._set(decodeValue(codecs.u32, value));
        }
        break;
      case 4:
        if (op === ChangeOp.FullValue) {
          this.selected._set(decodeValue(optionTodo, value));
        }
        break;
      case 5:
        if (op === ChangeOp.FullValue) {
          this.title._set(decodeValue(codecs.string, value));
        }
        break;
      case 6:
        if (op === ChangeOp.FullValue) {
          this.counter._set(decodeValue(CounterCodec, value));
        }
        break;
      case 7:
        if (op === ChangeOp.FullValue) {
          this.tags._set(decodeValue(mapStringU32, value));
        }
        break;
      case 8:
        if (op === ChangeOp.FullValue) {
          this.lastError._set(decodeValue(optionTodoError, value));
        }
        break;
      case 9:
        if (op === ChangeOp.FullValue) {
          this.elapsed._set(decodeValue(codecs.duration, value));
        }
        break;
      case 10:
        if (op === ChangeOp.FullValue) {
          this.created._set(decodeValue(codecs.timestamp, value));
        }
        break;
      case 11:
        if (op === ChangeOp.FullValue) {
          this.blob._set(decodeValue(codecs.bytes, value));
        }
        break;
      case 12:
        if (op === ChangeOp.FullValue) {
          this.total._set(decodeValue(codecs.u64, value));
        }
        break;
      case 13:
        if (op === ChangeOp.FullValue) {
          this.default._set(decodeValue(codecs.bool, value));
        }
        break;
      case 14:
        if (op === ChangeOp.FullValue) {
          this.uuid._set(decodeValue(codecs.uuid, value));
        }
        break;
      default:
        break;
    }
  }

  /** Re-observes a signal whose mirror diverged from the core, to receive a full value. */
  private _resync(signalId: number): void {
    void this.core.observe(this.handle, signalId, false);
    void this.core.observe(this.handle, signalId, true);
  }
}

/** Decodes every item of a core stream; a failure passes through `mapError`. */
async function* decodeStream<T>(
  source: AsyncIterable<Uint8Array>,
  codec: Codec<T>,
  mapError: (error: unknown) => unknown = (error) => error,
): AsyncGenerator<T, void, undefined> {
  try {
    for await (const body of source) yield decodeValue(codec, body);
  } catch (error) {
    throw mapError(error);
  }
}

const vecTodo = codecs.vec(TodoCodec);
const optionTodo = codecs.option(TodoCodec);
const mapStringU32 = codecs.map(codecs.string, codecs.u32);
const optionTodoError = codecs.option(TodoErrorCodec);
