// Generated by undra-bindgen from the Undra schema of `golden-objects` (schema hash 0x892e61432c31cead). Do not edit.

package golden.objects

import dev.undra.runtime.UndraException
import dev.undra.runtime.UndraReplyException
import dev.undra.runtime.wire.Payloads.ReplyStatus
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import dev.undra.runtime.wire.decodeAll

sealed class CalcError(message: String) : UndraException(message) {
    data object Overflow : CalcError("overflow")
    data object DivideByZero : CalcError("divide by zero")

    companion object : UndraCodec<CalcError> {
        override fun encode(w: UndraWriter, v: CalcError) {
            when (v) {
                Overflow -> w.writeU16(0u)
                DivideByZero -> w.writeU16(1u)
            }
        }

        override fun decode(r: UndraReader): CalcError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Overflow
                1 -> DivideByZero
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "CalcError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: UndraReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}
