// Generated by undra-bindgen from the Undra schema of `golden-objects` (schema hash 0x892e61432c31cead). Do not edit.

package golden.objects

import dev.undra.runtime.UndraCallError
import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraObject
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.decodeAll
import java.util.UUID
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map

/** Adds numbers. */
class Calculator private constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
    constructor(ctx: UndraCore = UndraCore.shared) : this(
        ctx,
        ctx.constructObject(UndraIds.Objects.Calculator.TYPE_ID, UndraIds.Objects.Calculator.NEW, ByteArray(0)),
    )

    /**
     * Adds two numbers.
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     */
    fun add(a: Int, b: Int): Int {
        val w = UndraWriter()
        w.writeI32(a)
        w.writeI32(b)
        try {
            val body = this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.ADD),
                UndraIds.Objects.Calculator.ADD,
                w.toByteArray(),
            )
            return Codecs.i32.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    /** A failure is logged and passed to `LoadOptions.onError`; the method does not throw. */
    fun reset() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.RESET),
                UndraIds.Objects.Calculator.RESET,
                ByteArray(0),
            )
        } catch (e: Exception) {
            this.core.report(e, "Calculator.reset")
        }
    }

    /**
     * Divides, failing on zero.
     * @throws CalcError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     */
    fun divide(a: Long, b: Long): Long {
        val w = UndraWriter()
        w.writeI64(a)
        w.writeI64(b)
        try {
            val body = this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.DIVIDE),
                UndraIds.Objects.Calculator.DIVIDE,
                w.toByteArray(),
            )
            return Codecs.i64.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, CalcError)
        }
    }

    /**
     * @throws CalcError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     */
    fun check() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.CHECK),
                UndraIds.Objects.Calculator.CHECK,
                ByteArray(0),
            )
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, CalcError)
        }
    }

    /**
     * Fetches a todo.
     * @throws CalcError
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun lookup(id: UUID): Todo {
        val w = UndraWriter()
        Codecs.uuid.encode(w, id)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.LOOKUP),
                UndraIds.Objects.Calculator.LOOKUP,
                w.toByteArray(),
            )
            return Todo.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e, CalcError)
        }
    }

    /**
     * An async method without an error type.
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun compute(input: Double?): Double {
        val w = UndraWriter()
        codecOptionF64.encode(w, input)
        try {
            val body = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.COMPUTE),
                UndraIds.Objects.Calculator.COMPUTE,
                w.toByteArray(),
            )
            return Codecs.f64.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    /**
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun warmUp() {
        try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.WARM_UP),
                UndraIds.Objects.Calculator.WARM_UP,
                ByteArray(0),
            )
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    /**
     * Counts up.
     * Collecting throws UndraCallError; cancelling the collector ends it quietly.
     */
    fun ticks(n: UInt): Flow<UInt> {
        val w = UndraWriter()
        w.writeU32(n)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.TICKS),
            UndraIds.Objects.Calculator.TICKS,
            w.toByteArray(),
        )
        return stream
            .map { bytes -> Codecs.u32.decodeAll(bytes) }
            .catch { error ->
                throw UndraCallError.mappedStream(error)
            }
    }

    /**
     * Streams todos, failing to open with a typed error.
     * Collecting throws CalcError or UndraCallError; cancelling the collector ends it quietly.
     */
    fun watch(mode: Mode): Flow<Todo> {
        val w = UndraWriter()
        Mode.encode(w, mode)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.WATCH),
            UndraIds.Objects.Calculator.WATCH,
            w.toByteArray(),
        )
        return stream
            .map { bytes -> Todo.decodeAll(bytes) }
            .catch { error ->
                throw UndraCallError.mappedStream(error, CalcError)
            }
    }

    /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
    fun stats(): Stats {
        try {
            val body = this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.STATS),
                UndraIds.Objects.Calculator.STATS,
                ByteArray(0),
            )
            return Stats.decodeAll(body)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    /**
     * A method named like a keyword.
     * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
     * @throws CancellationException if the calling coroutine is cancelled.
     */
    suspend fun delete(w: Int, body: Int, core: Int, default: Int, signal: Int): Int {
        val w_ = UndraWriter()
        w_.writeI32(w)
        w_.writeI32(body)
        w_.writeI32(core)
        w_.writeI32(default)
        w_.writeI32(signal)
        try {
            val body_ = this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.DELETE),
                UndraIds.Objects.Calculator.DELETE,
                w_.toByteArray(),
            )
            return Codecs.i32.decodeAll(body_)
        } catch (e: Exception) {
            throw UndraCallError.mapped(e)
        }
    }

    companion object {
        /** @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached. */
        fun create(ctx: UndraCore = UndraCore.shared): Calculator {
            val handle = ctx.constructObject(UndraIds.Objects.Calculator.TYPE_ID, UndraIds.Objects.Calculator.NEW, ByteArray(0))
            return Calculator(ctx, handle)
        }

        /**
         * @throws CalcError
         * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
         */
        fun withPrecision(digits: UByte, ctx: UndraCore = UndraCore.shared): Calculator {
            val w = UndraWriter()
            w.writeU8(digits)
            val handle = try {
                ctx.construct(UndraIds.Objects.Calculator.TYPE_ID, UndraIds.Objects.Calculator.WITH_PRECISION, w.toByteArray())
            } catch (e: Exception) {
                throw UndraCallError.mapped(e, CalcError)
            }
            return Calculator(ctx, handle)
        }

        /**
         * @throws CalcError
         * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
         * @throws CancellationException if the calling coroutine is cancelled.
         */
        suspend fun open(path: String, mode: Mode, ctx: UndraCore = UndraCore.shared): Calculator {
            val w = UndraWriter()
            w.writeStr(path)
            Mode.encode(w, mode)
            val handle = try {
                Codecs.handle.decodeAll(ctx.call(CallTarget.Constructor(UndraIds.Objects.Calculator.TYPE_ID, UndraIds.Objects.Calculator.OPEN), UndraIds.Objects.Calculator.OPEN, w.toByteArray()))
            } catch (e: Exception) {
                throw UndraCallError.mapped(e, CalcError)
            }
            if (handle == 0L) throw UndraCallError.Malformed("the core returned the null handle for a constructor")
            return Calculator(ctx, handle)
        }
    }
}

/**
 * Says hello.
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 */
fun greet(name: String, ctx: UndraCore = UndraCore.shared): String {
    val w = UndraWriter()
    w.writeStr(name)
    try {
        val body = ctx.callSync(
            CallTarget.FreeFunction(UndraIds.Functions.GREET),
            UndraIds.Functions.GREET,
            w.toByteArray(),
        )
        return Codecs.string.decodeAll(body)
    } catch (e: Exception) {
        throw UndraCallError.mapped(e)
    }
}

/** Collecting throws UndraCallError; cancelling the collector ends it quietly. */
fun numbers(upto: UInt, ctx: UndraCore = UndraCore.shared): Flow<UInt> {
    val w = UndraWriter()
    w.writeU32(upto)
    val stream = ctx.stream(
        CallTarget.FreeFunction(UndraIds.Functions.NUMBERS),
        UndraIds.Functions.NUMBERS,
        w.toByteArray(),
    )
    return stream
        .map { bytes -> Codecs.u32.decodeAll(bytes) }
        .catch { error ->
            throw UndraCallError.mappedStream(error)
        }
}

/**
 * @throws CalcError
 * @throws UndraCallError if the core panics, refuses or cancels the call, or cannot be reached.
 * @throws CancellationException if the calling coroutine is cancelled.
 */
suspend fun ping(ctx: UndraCore = UndraCore.shared) {
    try {
        ctx.call(
            CallTarget.FreeFunction(UndraIds.Functions.PING),
            UndraIds.Functions.PING,
            ByteArray(0),
        )
    } catch (e: Exception) {
        throw UndraCallError.mapped(e, CalcError)
    }
}

private val codecOptionF64 = Codecs.option(Codecs.f64)
