// Generated by undra-bindgen from the Undra schema of `golden-objects` (schema hash 0x892e61432c31cead). Do not edit.

package golden.objects

import dev.undra.runtime.UndraCore
import dev.undra.runtime.UndraObject
import dev.undra.runtime.UndraReplyException
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.Handle
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.Payloads.CallTarget
import dev.undra.runtime.wire.decodeAll
import java.util.UUID
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.catch
import kotlinx.coroutines.flow.map

/** Adds numbers. */
class Calculator private constructor(core: UndraCore, handle: Long) : UndraObject(core, handle) {
    constructor(ctx: UndraCore = UndraCore.shared) : this(
        ctx,
        ctx.construct(UndraIds.Objects.Calculator.TYPE_ID, UndraIds.Objects.Calculator.NEW, ByteArray(0)),
    )

    /** Adds two numbers. */
    fun add(a: Int, b: Int): Int {
        val w = UndraWriter()
        w.writeI32(a)
        w.writeI32(b)
        val body = this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.ADD),
            UndraIds.Objects.Calculator.ADD,
            w.toByteArray(),
        )
        return Codecs.i32.decodeAll(body)
    }

    fun reset() {
        this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.RESET),
            UndraIds.Objects.Calculator.RESET,
            ByteArray(0),
        )
    }

    /**
     * Divides, failing on zero.
     * @throws CalcError
     */
    fun divide(a: Long, b: Long): Long {
        val w = UndraWriter()
        w.writeI64(a)
        w.writeI64(b)
        val body = try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.DIVIDE),
                UndraIds.Objects.Calculator.DIVIDE,
                w.toByteArray(),
            )
        } catch (e: UndraReplyException) {
            throw CalcError.fromReply(e)
        }
        return Codecs.i64.decodeAll(body)
    }

    /** @throws CalcError */
    fun check() {
        try {
            this.core.callSync(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.CHECK),
                UndraIds.Objects.Calculator.CHECK,
                ByteArray(0),
            )
        } catch (e: UndraReplyException) {
            throw CalcError.fromReply(e)
        }
    }

    /**
     * Fetches a todo.
     * @throws CalcError
     */
    suspend fun lookup(id: UUID): Todo {
        val w = UndraWriter()
        Codecs.uuid.encode(w, id)
        val body = try {
            this.core.call(
                CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.LOOKUP),
                UndraIds.Objects.Calculator.LOOKUP,
                w.toByteArray(),
            )
        } catch (e: UndraReplyException) {
            throw CalcError.fromReply(e)
        }
        return Todo.decodeAll(body)
    }

    /** An async method without an error type. */
    suspend fun compute(input: Double?): Double {
        val w = UndraWriter()
        codecOptionF64.encode(w, input)
        val body = this.core.call(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.COMPUTE),
            UndraIds.Objects.Calculator.COMPUTE,
            w.toByteArray(),
        )
        return Codecs.f64.decodeAll(body)
    }

    suspend fun warmUp() {
        this.core.call(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.WARM_UP),
            UndraIds.Objects.Calculator.WARM_UP,
            ByteArray(0),
        )
    }

    /** Counts up. */
    fun ticks(n: UInt): Flow<UInt> {
        val w = UndraWriter()
        w.writeU32(n)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.TICKS),
            UndraIds.Objects.Calculator.TICKS,
            w.toByteArray(),
        )
        return stream.map { bytes -> Codecs.u32.decodeAll(bytes) }
    }

    /**
     * Streams todos, failing to open with a typed error.
     * @throws CalcError
     */
    fun watch(mode: Mode): Flow<Todo> {
        val w = UndraWriter()
        Mode.encode(w, mode)
        val stream = this.core.stream(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.WATCH),
            UndraIds.Objects.Calculator.WATCH,
            w.toByteArray(),
        )
        return stream
            .map { bytes -> Todo.decodeAll(bytes) }
            .catch { error ->
                throw if (error is UndraReplyException) CalcError.fromReply(error) else error
            }
    }

    fun stats(): Stats {
        val body = this.core.callSync(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.STATS),
            UndraIds.Objects.Calculator.STATS,
            ByteArray(0),
        )
        return Stats.decodeAll(body)
    }

    /** A method named like a keyword. */
    suspend fun delete(w: Int, body: Int, core: Int, default: Int, signal: Int): Int {
        val w_ = UndraWriter()
        w_.writeI32(w)
        w_.writeI32(body)
        w_.writeI32(core)
        w_.writeI32(default)
        w_.writeI32(signal)
        val body_ = this.core.call(
            CallTarget.ObjectMethod(Handle(this.handle), UndraIds.Objects.Calculator.DELETE),
            UndraIds.Objects.Calculator.DELETE,
            w_.toByteArray(),
        )
        return Codecs.i32.decodeAll(body_)
    }

    companion object {
        fun create(ctx: UndraCore = UndraCore.shared): Calculator {
            val handle = ctx.construct(UndraIds.Objects.Calculator.TYPE_ID, UndraIds.Objects.Calculator.NEW, ByteArray(0))
            return Calculator(ctx, handle)
        }

        /** @throws CalcError */
        fun withPrecision(digits: UByte, ctx: UndraCore = UndraCore.shared): Calculator {
            val w = UndraWriter()
            w.writeU8(digits)
            val handle = try {
                ctx.construct(UndraIds.Objects.Calculator.TYPE_ID, UndraIds.Objects.Calculator.WITH_PRECISION, w.toByteArray())
            } catch (e: UndraReplyException) {
                throw CalcError.fromReply(e)
            }
            return Calculator(ctx, handle)
        }

        /** @throws CalcError */
        suspend fun open(path: String, mode: Mode, ctx: UndraCore = UndraCore.shared): Calculator {
            val w = UndraWriter()
            w.writeStr(path)
            Mode.encode(w, mode)
            val handle = try {
                Codecs.handle.decodeAll(ctx.call(CallTarget.Constructor(UndraIds.Objects.Calculator.TYPE_ID, UndraIds.Objects.Calculator.OPEN), UndraIds.Objects.Calculator.OPEN, w.toByteArray()))
            } catch (e: UndraReplyException) {
                throw CalcError.fromReply(e)
            }
            return Calculator(ctx, handle)
        }
    }
}

/** Says hello. */
fun greet(name: String, ctx: UndraCore = UndraCore.shared): String {
    val w = UndraWriter()
    w.writeStr(name)
    val body = ctx.callSync(
        CallTarget.FreeFunction(UndraIds.Functions.GREET),
        UndraIds.Functions.GREET,
        w.toByteArray(),
    )
    return Codecs.string.decodeAll(body)
}

fun numbers(upto: UInt, ctx: UndraCore = UndraCore.shared): Flow<UInt> {
    val w = UndraWriter()
    w.writeU32(upto)
    val stream = ctx.stream(
        CallTarget.FreeFunction(UndraIds.Functions.NUMBERS),
        UndraIds.Functions.NUMBERS,
        w.toByteArray(),
    )
    return stream.map { bytes -> Codecs.u32.decodeAll(bytes) }
}

/** @throws CalcError */
suspend fun ping(ctx: UndraCore = UndraCore.shared) {
    try {
        ctx.call(
            CallTarget.FreeFunction(UndraIds.Functions.PING),
            UndraIds.Functions.PING,
            ByteArray(0),
        )
    } catch (e: UndraReplyException) {
        throw CalcError.fromReply(e)
    }
}

private val codecOptionF64 = Codecs.option(Codecs.f64)
