// Generated by undra-bindgen from the Undra schema of `golden-objects` (schema hash 0x892e61432c31cead). Do not edit.

package golden.objects

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import java.util.UUID

data class Stats(
    val count: UInt,
    val total: Long,
) : UndraRecord {
    companion object : UndraCodec<Stats> {
        override fun encode(w: UndraWriter, v: Stats) {
            w.writeU32(v.count)
            w.writeI64(v.total)
        }

        override fun decode(r: UndraReader): Stats = Stats(count = r.readU32(), total = r.readI64())
    }
}

data class Todo(
    val id: UUID,
    val title: String,
) : UndraRecord {
    companion object : UndraCodec<Todo> {
        override fun encode(w: UndraWriter, v: Todo) {
            Codecs.uuid.encode(w, v.id)
            w.writeStr(v.title)
        }

        override fun decode(r: UndraReader): Todo = Todo(
            id = Codecs.uuid.decode(r),
            title = r.readStr(),
        )
    }
}

enum class Mode(val index: UShort) : UndraEnum {
    FAST(0u),
    EXACT(1u);

    companion object : UndraCodec<Mode> {
        override fun encode(w: UndraWriter, v: Mode) = w.writeU16(v.index)

        override fun decode(r: UndraReader): Mode {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> FAST
                1 -> EXACT
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "Mode")
            }
        }
    }
}
