// Generated by undra-bindgen from the Undra schema of `golden-newtypes` (schema hash 0xcfde958ad92fbb7e). Do not edit.

import { type CallbackInterface } from "@undra/runtime";
import { UndraIds } from "./ids.js";
import { type TodoId, TodoIdCodec, type UserId, UserIdCodec } from "./types.js";

/** Hears about the board. */
export interface Listener {
  /** A todo changed hands. */
  assigned(todo: TodoId, owner: UserId): void;
}

/**
 * A `Listener` that holds `target` weakly (ADR-041): it forwards while `target` is alive; once `target` was
 * garbage-collected its methods do nothing.
 * Pass it instead of `target` when the core must not keep `target` alive.
 */
export function weakListener(target: Listener): Listener {
  const ref = new WeakRef(target);
  return {
    assigned: (todo, owner) => ref.deref()?.assigned(todo, owner),
  };
}

/**
 * How the core's calls reach a `Listener` the app passed in (ADR-041), for the runtime: the ids and the
 * decoding of each method. Generated calls lend through it; an app does not use it.
 */
export const ListenerCallback: CallbackInterface<Listener> = {
  name: "Listener",
  portId: UndraIds.Callbacks.Listener.portId,
  releaseInstance: UndraIds.Callbacks.Listener.releaseInstance,
  cancelCall: UndraIds.Callbacks.Listener.cancelCall,
  methods: {
    [UndraIds.Callbacks.Listener.assigned]: {
      name: "assigned",
      notify: (r) => {
        const todo = TodoIdCodec.decode(r);
        const owner = UserIdCodec.decode(r);
        return (impl) => impl.assigned(todo, owner);
      },
    },
  },
};
