// Generated by undra-bindgen from the Undra schema of `golden-newtypes` (schema hash 0xe3f1a6253d95e128). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
export const UndraIds = {
  schemaHash: 0xe3f1a6253d95e128n,
  namespace: "golden_newtypes",
  Objects: {
    Board: {
      typeId: 0xc18f13cb,
      new: 0x89587e3f,
      assign: 0xc04835d6,
      ownerOf: 0x2fdca5b2,
      distance: 0x34b971b8,
      changes: 0x828d0ef8,
      listen: 0x4aa53d38,
    },
  },
  Functions: {
    lookup: 0x4742a367,
    makeId: 0x2c503721,
  },
  Ports: {
    Directory: {
      portId: 0xd55746bb,
      find: 0xc1428f75,
    },
  },
  Queries: {
  },
  Callbacks: {
    Listener: {
      portId: 0xc0a9b660,
      assigned: 0xe4d64a85,
      releaseInstance: 0x193e1cd8,
      cancelCall: 0x41f8250d,
    },
  },
} as const;
