// node --test scripts/generated-weight.test.mjs
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";

import { classify, kindOf, markdown, measure } from "./generated-weight.mjs";

test("Swift: /// is documentation, // is a comment, a blank line is blank, the rest is code", () => {
  const text = [
    "// Generated by undra-bindgen. Do not edit.",
    "",
    "/// A todo.",
    "/// - Note: second line.",
    "public struct Todo {",
    "    // a plain comment",
    "    public var id: Int32 // trailing comment: the line is code",
    "}",
    "",
  ].join("\n");
  assert.deepEqual(classify(text, "Types.swift"), { code: 3, doc: 2, comment: 2, blank: 1 });
});

test("Kotlin and TypeScript: a /** .. */ block is documentation line by line, /* .. */ is a comment", () => {
  const text = [
    "// header",
    "/**",
    " * Adds `amount`.",
    " */",
    "fun add(amount: Int) {",
    "    /* not a doc */",
    "    /** one line */",
    "    run()",
    "}",
  ].join("\n");
  assert.deepEqual(classify(text, "Stores.kt"), { code: 3, doc: 4, comment: 2, blank: 0 });
  assert.deepEqual(classify(text, "stores.ts"), { code: 3, doc: 4, comment: 2, blank: 0 });
});

test("C: /* .. */ headers are comments, tsconfig.json has // comments, other JSON is all code", () => {
  const c = "/* Generated by undra.\n *\n * Do not edit.\n */\n#include \"a.h\"\n";
  assert.deepEqual(classify(c, "a.c"), { code: 1, doc: 0, comment: 4, blank: 0 });
  assert.deepEqual(classify("// header\n{\n}\n", "tsconfig.json"), { code: 2, doc: 0, comment: 1, blank: 0 });
  assert.deepEqual(classify('{\n  "//": "header"\n}\n', "package.json"), { code: 3, doc: 0, comment: 0, blank: 0 });
});

test("a file is counted under the kind of its stem; everything else is package files", () => {
  assert.equal(kindOf("swift/Sources/X/Generated/Stores.swift"), "Stores");
  assert.equal(kindOf("kotlin/src/main/kotlin/a/Ids.kt"), "Ids");
  assert.equal(kindOf("ts/src/index.ts"), "Index");
  assert.equal(kindOf("swift/Package.swift"), "package");
  assert.equal(kindOf("ts/package.json"), "package");
  assert.equal(kindOf("swift/Sources/XFFI/include/x.h"), "package");
});

test("a tree is measured per platform and kind, and the tree's .gitattributes is not bindings", () => {
  const root = mkdtempSync(join(tmpdir(), "weight-"));
  try {
    mkdirSync(join(root, "swift/Sources/X/Generated"), { recursive: true });
    mkdirSync(join(root, "kotlin"), { recursive: true });
    mkdirSync(join(root, "ts/src"), { recursive: true });
    writeFileSync(join(root, "swift/Sources/X/Generated/Types.swift"), "/// A.\nstruct A {}\n\n");
    writeFileSync(join(root, "swift/.gitattributes"), "* linguist-generated=true\n");
    writeFileSync(join(root, "kotlin/build.gradle.kts"), "// header\nplugins {}\n");
    writeFileSync(join(root, "ts/src/types.ts"), "export {};\n");
    const m = measure(root);
    assert.deepEqual(m.Swift.Types, { files: 1, lines: 3, code: 1, doc: 1, comment: 0, blank: 1 });
    assert.deepEqual(m.Swift.total, m.Swift.Types, "the .gitattributes file is not counted");
    assert.equal(m.Kotlin.package.lines, 2);
    assert.equal(m.TypeScript.total.lines, 1);
    const text = markdown(m);
    assert.match(text, /\*\*Swift\*\*/);
    assert.match(text, /\| Types \| 1 \| 3 \| 1 \| 1 \| 0 \| 1 \|/);
  } finally {
    rmSync(root, { recursive: true, force: true });
  }
});
