// Generated by undra-bindgen from the Undra schema of `golden-records` (schema hash 0x3e314305379cf9a4). Do not edit.

import { type Codec, type Duration, type Timestamp, WireError, codecs } from "@undra/runtime";

/** Nested containers and bytes. */
export interface Containers {
  lines: (string | null)[];
  scores: Map<string, number>;
  byId: Map<string, Todo[]>;
  blob: Uint8Array;
  maybeBlob: Uint8Array | null;
  matrix: number[][];
  counts: Map<number, bigint>;
}

export const ContainersCodec: Codec<Containers> = {
  encode(w, v) {
    vecOptionString.encode(w, v.lines);
    mapStringI32.encode(w, v.scores);
    mapUuidVecTodo.encode(w, v.byId);
    w.writeBytes(v.blob);
    optionBytes.encode(w, v.maybeBlob);
    vecVecF64.encode(w, v.matrix);
    mapU32u64.encode(w, v.counts);
  },
  decode(r) {
    return {
      lines: vecOptionString.decode(r),
      scores: mapStringI32.decode(r),
      byId: mapUuidVecTodo.decode(r),
      blob: codecs.bytes.decode(r),
      maybeBlob: optionBytes.decode(r),
      matrix: vecVecF64.decode(r),
      counts: mapU32u64.decode(r),
    };
  },
};

/** A record without fields. */
export interface Empty {}

export const EmptyCodec: Codec<Empty> = {
  encode(_w, _v) {
  },
  decode(_r) {
    return {};
  },
};

/** Field names that are reserved words in some target language. */
export interface Keywords {
  default: string;
  in: number;
  object: boolean;
  delete: boolean;
  new: boolean;
  className: string;
}

export const KeywordsCodec: Codec<Keywords> = {
  encode(w, v) {
    w.writeStr(v.default);
    w.writeI32(v.in);
    w.writeBool(v.object);
    w.writeBool(v.delete);
    w.writeBool(v.new);
    w.writeStr(v.className);
  },
  decode(r) {
    return {
      default: r.readStr(),
      in: r.readI32(),
      object: r.readBool(),
      delete: r.readBool(),
      new: r.readBool(),
      className: r.readStr(),
    };
  },
};

/** Every fixed-width number type. */
export interface Numbers {
  a: number;
  b: number;
  c: number;
  d: bigint;
  e: number;
  f: number;
  g: number;
  h: bigint;
  i: number;
  j: number;
  elapsed: Duration;
}

export const NumbersCodec: Codec<Numbers> = {
  encode(w, v) {
    w.writeI8(v.a);
    w.writeI16(v.b);
    w.writeI32(v.c);
    w.writeI64(v.d);
    w.writeU8(v.e);
    w.writeU16(v.f);
    w.writeU32(v.g);
    w.writeU64(v.h);
    w.writeF32(v.i);
    w.writeF64(v.j);
    codecs.duration.encode(w, v.elapsed);
  },
  decode(r) {
    return {
      a: r.readI8(),
      b: r.readI16(),
      c: r.readI32(),
      d: r.readI64(),
      e: r.readU8(),
      f: r.readU16(),
      g: r.readU32(),
      h: r.readU64(),
      i: r.readF32(),
      j: r.readF64(),
      elapsed: codecs.duration.decode(r),
    };
  },
};

/** A recursive record. */
export interface Page {
  items: Todo[];
  next: string | null;
  children: Page[];
}

export const PageCodec: Codec<Page> = {
  encode(w, v) {
    vecTodo.encode(w, v.items);
    optionString.encode(w, v.next);
    vecPage.encode(w, v.children);
  },
  decode(r) {
    return {
      items: vecTodo.decode(r),
      next: optionString.decode(r),
      children: vecPage.decode(r),
    };
  },
};

/**
 * A todo item.
 * Shown in the list and synced to the server.
 */
export interface Todo {
  /** Stable identifier. */
  id: string;
  title: string;
  done: boolean;
  tags: string[];
  due: Timestamp | null;
  priority: Priority;
}

export const TodoCodec: Codec<Todo> = {
  encode(w, v) {
    w.writeUuid(v.id);
    w.writeStr(v.title);
    w.writeBool(v.done);
    vecString.encode(w, v.tags);
    optionTimestamp.encode(w, v.due);
    PriorityCodec.encode(w, v.priority);
  },
  decode(r) {
    return {
      id: r.readUuid(),
      title: r.readStr(),
      done: r.readBool(),
      tags: vecString.decode(r),
      due: optionTimestamp.decode(r),
      priority: PriorityCodec.decode(r),
    };
  },
};

export type Priority = "low" | "normal" | "high";

export const PriorityCodec: Codec<Priority> = {
  encode(w, v) {
    switch (v) {
      case "low":
        w.writeU16(0);
        break;
      case "normal":
        w.writeU16(1);
        break;
      case "high":
        w.writeU16(2);
        break;
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return "low";
      case 1:
        return "normal";
      case 2:
        return "high";
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "Priority" });
    }
  },
};

const optionString = codecs.option(codecs.string);
const vecOptionString = codecs.vec(optionString);
const mapStringI32 = codecs.map(codecs.string, codecs.i32);
const vecTodo = codecs.vec(TodoCodec);
const mapUuidVecTodo = codecs.map(codecs.uuid, vecTodo);
const optionBytes = codecs.option(codecs.bytes);
const vecF64 = codecs.vec(codecs.f64);
const vecVecF64 = codecs.vec(vecF64);
const mapU32u64 = codecs.map(codecs.u32, codecs.u64);
const vecPage = codecs.vec(PageCodec);
const vecString = codecs.vec(codecs.string);
const optionTimestamp = codecs.option(codecs.timestamp);
