// Generated by undra-bindgen from the Undra schema of `golden-stdlib` (schema hash 0x6b4638c4a5e34313). Do not edit.

import {
  CallTarget,
  type Codec,
  FsErrorCodec,
  HttpErrorCodec,
  type HttpRequest,
  HttpRequestCodec,
  type HttpResponse,
  HttpResponseCodec,
  UndraCallError,
  UndraCore,
  UndraObject,
  UndraWriter,
  decodeValue,
} from "@undra/runtime";
import { UndraGoldenStdlib } from "./core.js";
import { SyncErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";
import { type Endpoint, EndpointCodec } from "./types.js";

/** Talks to the server. */
export class Syncer extends UndraObject {
  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(core: UndraCore = UndraGoldenStdlib.core): Promise<Syncer> {
    let handle: bigint;
    try {
      handle = await core.construct(
        UndraIds.Objects.Syncer.typeId,
        UndraIds.Objects.Syncer.new,
        new Uint8Array(0),
      );
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    return new Syncer(core, handle);
  }

  /**
   * Performs one request.
   * @throws {HttpError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async send(request: HttpRequest, signal?: AbortSignal): Promise<HttpResponse> {
    const w = new UndraWriter();
    HttpRequestCodec.encode(w, request);
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Syncer.send,
        w.finish(),
        signal,
      );
      return decodeValue(HttpResponseCodec, body);
    } catch (error) {
      throw UndraCallError.mapped(error, HttpErrorCodec);
    }
  }

  /**
   * Streams the responses of a request that repeats.
   * Iterating throws HttpError or UndraCallError; leaving the loop early ends the stream quietly.
   */
  follow(endpoint: Endpoint): AsyncIterable<HttpResponse> {
    const w = new UndraWriter();
    EndpointCodec.encode(w, endpoint);
    const source = this.core.stream(
      { target: CallTarget.ObjectMethod, handle: this.handle },
      UndraIds.Objects.Syncer.follow,
      w.finish(),
    );
    return decodeStream(
      source,
      HttpResponseCodec,
      (error) => UndraCallError.mappedStream(error, HttpErrorCodec),
    );
  }

  /**
   * Writes the last response to disk.
   * @throws {FsError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async save(path: string, signal?: AbortSignal): Promise<void> {
    const w = new UndraWriter();
    w.writeStr(path);
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Syncer.save,
        w.finish(),
        signal,
      );
    } catch (error) {
      throw UndraCallError.mapped(error, FsErrorCodec);
    }
  }

  /**
   * @throws {SyncError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async sync(signal?: AbortSignal): Promise<void> {
    try {
      await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Syncer.sync,
        new Uint8Array(0),
        signal,
      );
    } catch (error) {
      throw UndraCallError.mapped(error, SyncErrorCodec);
    }
  }
}

/** Decodes every item of a core stream; a failure of the stream or of an item goes through `mapError`. */
async function* decodeStream<T>(
  source: AsyncIterable<Uint8Array>,
  codec: Codec<T>,
  mapError: (error: unknown) => unknown,
): AsyncGenerator<T, void, undefined> {
  try {
    for await (const body of source) yield decodeValue(codec, body);
  } catch (error) {
    throw mapError(error);
  }
}
