// Generated by undra-bindgen from the Undra schema of `golden-infinite` (schema hash 0x1b2522922dd3b430). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
export const UndraIds = {
  schemaHash: 0x1b2522922dd3b430n,
  namespace: "golden_infinite",
  Objects: {
    FeedQueryHandle: {
      typeId: 0x015a66a3,
      new: 0x015a66a3,
      fetchNextPage: 0x84920501,
      refetch: 0x21d1b9e2,
      invalidate: 0x44cec2fa,
      setPollInterval: 0xe327e53b,
    },
    ProfileQueryHandle: {
      typeId: 0x9cc44f88,
      new: 0x9cc44f88,
      refetch: 0x21d1b9e2,
      invalidate: 0x44cec2fa,
      setPollInterval: 0xe327e53b,
    },
    SearchQueryHandle: {
      typeId: 0x1082eab7,
      new: 0x1082eab7,
      fetchNextPage: 0x84920501,
      refetch: 0x21d1b9e2,
      invalidate: 0x44cec2fa,
      setPollInterval: 0xe327e53b,
    },
  },
  Functions: {
  },
  Ports: {
  },
  Queries: {
    feed: 0x015a66a3,
    profile: 0x9cc44f88,
    search: 0x1082eab7,
  },
} as const;
