// Generated by keel-bindgen from the Keel schema of `golden-records` (schema hash 0x3e314305379cf9a4). Do not edit.

package golden.records

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash to pass to `KeelCore.load` as `expectedSchemaHash`.
 */
object KeelIds {
    const val SCHEMA_HASH: ULong = 0x3e314305379cf9a4uL

    object Objects {}

    object Functions {}

    object Ports {}

    object Queries {}
}
