//! The lint exclusions `undra bindgen` writes next to each generated tree (ADR-061).
//!
//! A repository that lints everything (ktlint, SwiftLint, ESLint, detekt) reports the generated bindings: they are the
//! output of a generator and have the generator's style, not the repository's. The fix is to tell each linter the tree
//! is generated, in the file each one reads, and to do it where the tree is, so it travels with it when an app copies
//! or publishes the tree on its own:
//!
//! | Tree | File | Read by |
//! |---|---|---|
//! | `kotlin/` | `.editorconfig` | ktlint and the IDE formatter, for every Kotlin file below it |
//! | `kotlin/**/*.kt` | `@file:Suppress("ALL", "ktlint")` (the Kotlin generator's header) | ktlint, detekt and the IDE, wherever the tree is |
//! | `swift/` | `.swiftlint.yml` | SwiftLint: the `excluded:` list to merge into the lint root's configuration |
//! | `ts/` | `.eslintrc.json` | ESLint 8 and earlier (`ignorePatterns`) |
//! | `ts/` | `eslint.config.undra.mjs` | ESLint 9's flat config: the entry to spread into `eslint.config.js` |
//!
//! Every file is part of the tree's manifest, so `undra bindgen --check` fails when one is missing or edited and a later
//! run removes it with the rest. The `.gitattributes` that collapses the trees in a review is another piece's
//! (ADR-062); nothing here conflicts with it.

use undra_bindgen::GeneratedFile;

use crate::config::Platform;

/// `kotlin/.editorconfig`.
pub const KOTLIN_EDITORCONFIG: &str = "\
# Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
#
# Keeps ktlint and the IDE's formatter out of the generated Kotlin: this module is the output of a generator, so its style
# is the generator's, not yours. Every generated file also starts with `@file:Suppress(\"ALL\", \"ktlint\")`, which
# ktlint (every version), detekt and the IDE read without any configuration.
#
# If your repository's own .editorconfig switches ktlint on for everything and you would rather say it once at the root:
#
#     [**/generated/**]
#     ktlint_standard = disabled
#     ktlint_experimental = disabled
#
# For the Gradle ktlint plugin (org.jlleitschuh.gradle.ktlint):
#
#     ktlint { filter { exclude { it.file.path.contains(\"/generated/\") } } }
#
# For detekt (detekt.yml):
#
#     build:
#       excludes: ['**/generated/**']

[*.{kt,kts}]
ktlint_standard = disabled
ktlint_experimental = disabled
ij_formatter_enabled = false
";

/// `swift/.swiftlint.yml`, for a tree written to a directory called `out_name`.
#[must_use]
pub fn swiftlint(out_name: &str) -> String {
    format!(
        "\
# Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
#
# Keeps SwiftLint out of the generated Swift package. SwiftLint reads `excluded:` from the configuration of the directory
# it runs in (a nested configuration's own `excluded:` is ignored), so put these lines in your repository's
# .swiftlint.yml, or merge this file into the run:
#
#     swiftlint --config .swiftlint.yml --config {out_name}/swift/.swiftlint.yml
#
# Paths are relative to the directory SwiftLint runs in; change the prefix if the bindings live somewhere else.
excluded:
  - \"**/{out_name}/swift\"
"
    )
}

/// `ts/.eslintrc.json`: ESLint 8 and earlier read it from the tree (patterns are relative to the file).
pub const ESLINTRC: &str = "\
// Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
//
// Keeps ESLint (8 and earlier, eslintrc configuration) out of the generated TypeScript. ESLint 9's flat configuration is
// read only from the directory ESLint runs in: spread `eslint.config.undra.mjs`, next to this file, into your
// eslint.config.js.
{
  \"root\": false,
  \"ignorePatterns\": [\"**/*\"]
}
";

/// `ts/eslint.config.undra.mjs`, for a tree written to a directory called `out_name`.
#[must_use]
pub fn eslint_flat(out_name: &str) -> String {
    format!(
        "\
// Generated by `undra bindgen`: do not edit, it is rewritten with the bindings.
//
// ESLint 9's flat configuration is read from the directory ESLint runs in, never from a subdirectory, so the generated
// TypeScript cannot exclude itself. Spread this into your eslint.config.js, before your own entries:
//
//     import undraGenerated from \"./{out_name}/ts/eslint.config.undra.mjs\";
//     export default [...undraGenerated, /* your configuration */];
//
// The pattern matches the tree wherever the config sits above it.
export default [{{ ignores: [\"**/{out_name}/ts/**\"] }}];
"
    )
}

/// The lint files of the trees `platforms` generates, for an output directory called `out_name`, paths relative to it.
#[must_use]
pub fn fragments(platforms: &[Platform], out_name: &str) -> Vec<GeneratedFile> {
    let mut files = Vec::new();
    let mut add = |path: &str, contents: String| {
        files.push(GeneratedFile {
            path: path.to_owned(),
            contents,
        });
    };
    if platforms.contains(&Platform::Ios) {
        add("swift/.swiftlint.yml", swiftlint(out_name));
    }
    if platforms.contains(&Platform::Android) {
        add("kotlin/.editorconfig", KOTLIN_EDITORCONFIG.to_owned());
    }
    if platforms.contains(&Platform::Web) {
        add("ts/.eslintrc.json", ESLINTRC.to_owned());
        add("ts/eslint.config.undra.mjs", eslint_flat(out_name));
    }
    files
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn each_tree_gets_the_file_its_linter_reads() {
        let paths = |platforms: &[Platform]| -> Vec<String> {
            fragments(platforms, "generated")
                .into_iter()
                .map(|f| f.path)
                .collect()
        };
        assert_eq!(paths(&[Platform::Android]), ["kotlin/.editorconfig"]);
        assert_eq!(paths(&[Platform::Ios]), ["swift/.swiftlint.yml"]);
        assert_eq!(
            paths(&[Platform::Web]),
            ["ts/.eslintrc.json", "ts/eslint.config.undra.mjs"]
        );
        assert_eq!(paths(&Platform::ALL).len(), 4);
        assert!(paths(&[]).is_empty());
    }

    #[test]
    fn the_editorconfig_disables_ktlint_for_kotlin_files_only() {
        let rules: Vec<&str> = KOTLIN_EDITORCONFIG
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .collect();
        assert_eq!(
            rules,
            [
                "[*.{kt,kts}]",
                "ktlint_standard = disabled",
                "ktlint_experimental = disabled",
                "ij_formatter_enabled = false",
            ],
            "the section is the one of the file's own tree, not `root = true`: a parent .editorconfig still applies to the rest"
        );
        assert!(
            !KOTLIN_EDITORCONFIG.contains("root = true"),
            "a nested file must not cut the search for the repository's own"
        );
    }

    #[test]
    fn the_flat_config_and_the_swiftlint_fragment_name_the_output_directory() {
        assert!(eslint_flat("bindings").contains("\"**/bindings/ts/**\""));
        assert!(eslint_flat("bindings").contains("./bindings/ts/eslint.config.undra.mjs"));
        let yml = swiftlint("bindings");
        assert!(
            yml.contains("excluded:\n  - \"**/bindings/swift\""),
            "{yml}"
        );
        assert!(
            yml.contains("--config bindings/swift/.swiftlint.yml"),
            "{yml}"
        );
    }

    #[test]
    fn the_eslintrc_is_valid_json_once_its_comments_are_gone() {
        let json: String = ESLINTRC
            .lines()
            .filter(|l| !l.trim_start().starts_with("//"))
            .collect::<Vec<_>>()
            .join("\n");
        let value: serde_json::Value = serde_json::from_str(&json).expect("JSON");
        assert_eq!(value["ignorePatterns"][0], "**/*");
        assert_eq!(value["root"], false);
        assert!(
            value
                .as_object()
                .unwrap()
                .keys()
                .all(|k| k == "root" || k == "ignorePatterns"),
            "ESLint rejects a configuration with a key it does not know: {value}"
        );
    }

    #[test]
    fn every_file_says_it_is_generated() {
        for file in fragments(&Platform::ALL, "generated") {
            assert!(
                file.contents
                    .contains("Generated by `undra bindgen`: do not edit"),
                "{} has no header",
                file.path
            );
        }
    }
}
