//! The dev runner: building it, starting it, stopping it.
//!
//! The runner (generated by [`crate::shim`]) is a separate process so that a core that panics,
//! deadlocks or is being rebuilt cannot take `undra dev` down with it, and so a restart is a
//! process restart: fresh statics, a fresh `inventory`, nothing half-initialised. It talks to
//! `undra dev` through two channels and nothing else:
//!
//! * **stdout**: one line, `UNDRA-DEV ready <ws-url> <schema-hash>`, once it listens;
//! * **stdin**: the runner runs until its stdin closes, so it cannot outlive the CLI, even when
//!   the CLI is killed.

use std::io::{BufRead, BufReader};
use std::path::Path;
use std::process::{Child, ChildStdin, Command, Stdio};
use std::sync::mpsc::Sender;
use std::thread;
use std::time::{Duration, Instant};

use crate::error::{CliError, Code, Result};
use crate::session::Session;
use crate::shim;

/// The name of the runner binary.
pub const BIN: &str = "undra-dev-runner";

/// The prefix of the runner's ready line.
const READY: &str = "UNDRA-DEV ready ";

/// What a running runner reports.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RunnerEvent {
    /// It listens.
    Ready {
        /// Which run (see [`Running::id`]).
        id: u64,
        /// The `ws://` URL.
        url: String,
        /// The schema hash, `0x...`.
        hash: String,
    },
    /// Any other line it printed on stdout.
    Line {
        /// Which run.
        id: u64,
        /// The line.
        text: String,
    },
    /// Its stdout closed: it exited.
    Closed {
        /// Which run.
        id: u64,
    },
}

/// Parses a runner stdout line.
#[must_use]
pub fn parse_line(id: u64, line: &str) -> RunnerEvent {
    match line
        .strip_prefix(READY)
        .map(|rest| rest.split_whitespace().collect::<Vec<_>>())
    {
        Some(parts) if parts.len() == 2 => RunnerEvent::Ready {
            id,
            url: parts[0].to_owned(),
            hash: parts[1].to_owned(),
        },
        _ => RunnerEvent::Line {
            id,
            text: line.to_owned(),
        },
    }
}

/// Generates the runner crate for the project and builds it; returns the executable.
///
/// # Errors
///
/// See [`Session::core`], [`shim::write_runner`] and [`crate::cargo::Cargo::build_executable`].
pub fn build(session: &Session<'_>) -> Result<std::path::PathBuf> {
    let core = session.core()?;
    let target_dir = session.target_dir()?;
    let manifest = shim::write_runner(&target_dir, &session.project.root, core)?;
    session
        .cargo()
        .build_executable(&manifest, &target_dir, BIN)
}

/// A started runner.
pub struct Running {
    /// The run's number, to tell its events from an earlier run's.
    pub id: u64,
    child: Child,
    stdin: Option<ChildStdin>,
}

/// Starts the runner on `addr` and forwards what it prints as [`RunnerEvent`]s.
///
/// # Errors
///
/// `C0013` when it cannot be started.
pub fn spawn(
    exe: &Path,
    addr: &str,
    log_level: u8,
    id: u64,
    events: Sender<RunnerEvent>,
) -> Result<Running> {
    let mut child = Command::new(exe)
        .arg(addr)
        .arg("--log-level")
        .arg(log_level.to_string())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .spawn()
        .map_err(|e| {
            CliError::new(
                Code::Dev,
                format!("cannot start the dev runner {}: {e}", exe.display()),
                "`undra dev` serves the core from a small program it builds for this project",
                "run `undra dev` again; if the file is missing, `cargo clean` and retry",
            )
        })?;
    let stdout = child.stdout.take().expect("stdout is piped");
    let stdin = child.stdin.take();
    thread::Builder::new()
        .name("undra-dev-runner-stdout".to_owned())
        .spawn(move || {
            for line in BufReader::new(stdout)
                .lines()
                .map_while(std::result::Result::ok)
            {
                if events.send(parse_line(id, &line)).is_err() {
                    return;
                }
            }
            let _ = events.send(RunnerEvent::Closed { id });
        })
        .map_err(|e| {
            CliError::new(
                Code::Dev,
                format!("cannot start a thread to read the dev runner: {e}"),
                "the operating system refused a new thread",
                "close some programs and try again",
            )
        })?;
    Ok(Running { id, child, stdin })
}

impl Running {
    /// Asks the runner to stop by closing its stdin, waits a few seconds, then kills it.
    pub fn stop(mut self) {
        drop(self.stdin.take());
        let deadline = Instant::now() + Duration::from_secs(5);
        while Instant::now() < deadline {
            if matches!(self.child.try_wait(), Ok(Some(_))) {
                return;
            }
            thread::sleep(Duration::from_millis(25));
        }
        let _ = self.child.kill();
        let _ = self.child.wait();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ready_lines_are_parsed() {
        assert_eq!(
            parse_line(3, "UNDRA-DEV ready ws://127.0.0.1:7443 0x00000000deadbeef"),
            RunnerEvent::Ready {
                id: 3,
                url: "ws://127.0.0.1:7443".into(),
                hash: "0x00000000deadbeef".into()
            }
        );
    }

    #[test]
    fn anything_else_is_a_plain_line() {
        for text in [
            "hello",
            "UNDRA-DEV ready",
            "UNDRA-DEV ready only-one",
            "UNDRA-DEV ready a b c",
        ] {
            assert_eq!(
                parse_line(1, text),
                RunnerEvent::Line {
                    id: 1,
                    text: text.into()
                },
                "{text}"
            );
        }
    }
}
