//! Generated by `undra`: the app core and the Undra C ABI in one library.

// The core's one C export, `@@NAMESPACE@@_undra_api()` (its `UndraApi` table, docs/SPEC.md 6) and, with
// the `jni` feature, `JNI_OnLoad` registering the natives on `@@JNI_CLASS_DOTTED@@` (ADR-044). The version is the
// app core crate's: what a panic report names the core as (ADR-046).
undra_ffi::export_core!(@@NAMESPACE@@, jni_class = "@@JNI_CLASS@@", version = "@@CORE_VERSION@@");

// Links the core, whose `#[undra::api]` items register themselves with the runtime at load time.
extern crate app_core;
