//! Generated by `undra`: the app core and the Undra C ABI in one library.
#![allow(unused_imports)]

// The `undra_*` C ABI (`undra_init`, `undra_call`, `undra_schema_json`, ...) and, with the `jni`
// feature, the JNI entry points.
pub use undra_ffi::*;

// Links the core, whose `#[undra::api]` items register themselves with the runtime at load time.
extern crate app_core;
