// Generated by undra-bindgen from the Undra schema of `golden-newtypes` (schema hash 0xe3f1a6253d95e128). Do not edit.

package golden.newtypes

import dev.undra.runtime.UndraException
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException

sealed class BoardError(message: String) : UndraException(message) {
    data class NotFound(val value: TodoId) : BoardError("todo ${value} not found")
    data class Taken(val owner: UserId) : BoardError("taken by ${owner}")

    companion object : UndraCodec<BoardError> {
        override fun encode(w: UndraWriter, v: BoardError) {
            when (v) {
                is NotFound -> {
                    w.writeU16(0u)
                    TodoId.encode(w, v.value)
                }
                is Taken -> {
                    w.writeU16(1u)
                    UserId.encode(w, v.owner)
                }
            }
        }

        override fun decode(r: UndraReader): BoardError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> NotFound(value = TodoId.decode(r))
                1 -> Taken(owner = UserId.decode(r))
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "BoardError")
            }
        }
    }
}
