// Generated by undra-bindgen from the Undra schema of `golden-newtypes` (schema hash 0xcfde958ad92fbb7e). Do not edit.

package golden.newtypes

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
object UndraIds {
    const val SCHEMA_HASH: ULong = 0xcfde958ad92fbb7euL
    const val NAMESPACE: String = "golden_newtypes"

    object Objects {
        object Board {
            const val TYPE_ID: UInt = 0xc18f13cbu
            const val NEW: UInt = 0x89587e3fu
            const val ASSIGN: UInt = 0xc04835d6u
            const val OWNER_OF: UInt = 0x2fdca5b2u
            const val DISTANCE: UInt = 0x34b971b8u
            const val CHANGES: UInt = 0x828d0ef8u
            const val LISTEN: UInt = 0x4aa53d38u
        }
    }

    object Functions {
        const val LOOKUP: UInt = 0x4742a367u
        const val MAKE_ID: UInt = 0x2c503721u
    }

    object Ports {
        object Directory {
            const val PORT_ID: UInt = 0xd55746bbu
            const val FIND: UInt = 0xc1428f75u
        }
    }

    object Callbacks {
        object Listener {
            const val PORT_ID: UInt = 0xc0a9b660u
            const val ASSIGNED: UInt = 0xe4d64a85u
            const val RELEASE_INSTANCE: UInt = 0x193e1cd8u
            const val CANCEL_CALL: UInt = 0x41f8250du
        }
    }

    object Queries {}
}
