// Generated by undra-bindgen from the Undra schema of `golden-callbacks` (schema hash 0xdcef0138feda9c54). Do not edit.

import { type Codec, UndraError, WireError } from "@undra/runtime";

export type AuthErrorKind = "expired";

export abstract class AuthError extends UndraError {
  declare readonly kind: AuthErrorKind;
}

export namespace AuthError {
  export class Expired extends AuthError {
    declare readonly kind: "expired";

    constructor() {
      super("expired", "the token expired");
    }
  }
}

export const AuthErrorCodec: Codec<AuthError> = {
  encode(w, v) {
    if (v instanceof AuthError.Expired) {
      w.writeU16(0);
    } else {
      throw new TypeError(`unknown AuthError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new AuthError.Expired();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "AuthError" });
    }
  },
};

export type PromptErrorKind = "declined" | "unavailable";

export abstract class PromptError extends UndraError {
  declare readonly kind: PromptErrorKind;
}

export namespace PromptError {
  export class Declined extends PromptError {
    declare readonly kind: "declined";

    constructor() {
      super("declined", "the user declined");
    }
  }

  export class Unavailable extends PromptError {
    declare readonly kind: "unavailable";

    constructor(readonly value: string) {
      super("unavailable", `${value}`);
    }
  }
}

export const PromptErrorCodec: Codec<PromptError> = {
  encode(w, v) {
    if (v instanceof PromptError.Declined) {
      w.writeU16(0);
    } else if (v instanceof PromptError.Unavailable) {
      w.writeU16(1);
      w.writeStr(v.value);
    } else {
      throw new TypeError(`unknown PromptError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new PromptError.Declined();
      case 1:
        return new PromptError.Unavailable(r.readStr());
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "PromptError" });
    }
  },
};

export type UploadErrorKind = "failed";

export abstract class UploadError extends UndraError {
  declare readonly kind: UploadErrorKind;
}

export namespace UploadError {
  export class Failed extends UploadError {
    declare readonly kind: "failed";

    constructor() {
      super("failed", "the upload failed");
    }
  }
}

export const UploadErrorCodec: Codec<UploadError> = {
  encode(w, v) {
    if (v instanceof UploadError.Failed) {
      w.writeU16(0);
    } else {
      throw new TypeError(`unknown UploadError variant: ${v.kind}`);
    }
  },
  decode(r) {
    const at = r.position;
    const tag = r.readU16();
    switch (tag) {
      case 0:
        return new UploadError.Failed();
      default:
        throw new WireError({ code: "invalid_tag", tag, at, ty: "UploadError" });
    }
  },
};
