// Generated by undra-bindgen from the Undra schema of `golden-callbacks` (schema hash 0xdcef0138feda9c54). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash and the namespace of the core these bindings belong to.
 */
export const UndraIds = {
  schemaHash: 0xdcef0138feda9c54n,
  namespace: "golden_callbacks",
  Objects: {
    Uploader: {
      typeId: 0x247ebc8b,
      new: 0x0b61967f,
      upload: 0x815b2b02,
      watch: 0x44514bf6,
      setProvider: 0xe07bf10b,
      notify: 0x22c36eba,
      follow: 0x4e5d3d42,
      followChecked: 0x489acde0,
    },
    Watch: {
      typeId: 0xec266ec8,
      id: 0x2075bd1f,
    },
  },
  Functions: {
    tail: 0x757a75cf,
    withListener: 0xf5ac9882,
  },
  Ports: {
  },
  Queries: {
  },
  Callbacks: {
    TokenProvider: {
      portId: 0x92be3d64,
      token: 0x606cf2d0,
      refreshed: 0xedd513d7,
      releaseInstance: 0xb1249b22,
      cancelCall: 0xca10907f,
    },
    UploadListener: {
      portId: 0x77a5fa4d,
      progress: 0xd38d6519,
      finished: 0x9849e9d8,
      confirmReplace: 0xe4077c65,
      releaseInstance: 0x1e812a11,
      cancelCall: 0x5f0899fe,
    },
  },
} as const;
