// Generated by undra-bindgen from the Undra schema of `golden-callbacks` (schema hash 0xdcef0138feda9c54). Do not edit.

import {
  CallTarget,
  type Codec,
  UndraCallError,
  UndraCore,
  UndraObject,
  UndraWriter,
  adopt,
  adoptObject,
  codecs,
  decodeValue,
  lending,
  lendingStream,
  requireOwn,
} from "@undra/runtime";
import {
  type TokenProvider,
  TokenProviderCallback,
  type UploadListener,
  UploadListenerCallback,
} from "./callbacks.js";
import { UndraGoldenCallbacks } from "./core.js";
import { UploadErrorCodec } from "./errors.js";
import { UndraIds } from "./ids.js";

/** Uploads files. */
export class Uploader extends UndraObject {
  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  static async create(
    listener: UploadListener | null,
    core: UndraCore = UndraGoldenCallbacks.core,
  ): Promise<Uploader> {
    let handle: bigint;
    try {
      handle = await lending(core, (lend) => {
        const w = new UndraWriter();
        optionalHandle.encode(w, listener === null ? null : lend(listener, UploadListenerCallback));
        return core.construct(
          UndraIds.Objects.Uploader.typeId,
          UndraIds.Objects.Uploader.new,
          w.finish(),
        );
      });
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
    return adopt(core, handle, Uploader);
  }

  /**
   * Uploads `file`, reporting to `listener`.
   * @throws {UploadError}
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   * @throws The `signal`'s reason (an `AbortError` by default) if it aborts the call.
   */
  async upload(file: string, listener: UploadListener, signal?: AbortSignal): Promise<number> {
    try {
      const body = await lending(this.core, (lend) => {
        const w = new UndraWriter();
        w.writeStr(file);
        w.writeU64(lend(listener, UploadListenerCallback));
        return this.core.call(
          { target: CallTarget.ObjectMethod, handle: this.handle },
          UndraIds.Objects.Uploader.upload,
          w.finish(),
          signal,
        );
      }, signal);
      return decodeValue(codecs.u32, body);
    } catch (error) {
      throw UndraCallError.mapped(error, UploadErrorCodec);
    }
  }

  /**
   * Keeps `listener` until the returned watch is closed.
   * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
   */
  async watch(listener: UploadListener): Promise<Watch> {
    try {
      const body = await lending(this.core, (lend) => {
        const w = new UndraWriter();
        w.writeU64(lend(listener, UploadListenerCallback));
        return this.core.call(
          { target: CallTarget.ObjectMethod, handle: this.handle },
          UndraIds.Objects.Uploader.watch,
          w.finish(),
        );
      });
      return await adoptObject(this.core, body, Watch);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }

  /**
   * Uses `provider` for the tokens.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async setProvider(provider: TokenProvider): Promise<void> {
    try {
      await lending(this.core, (lend) => {
        const w = new UndraWriter();
        w.writeU64(lend(provider, TokenProviderCallback));
        return this.core.call(
          { target: CallTarget.ObjectMethod, handle: this.handle },
          UndraIds.Objects.Uploader.setProvider,
          w.finish(),
        );
      });
    } catch (error) {
      this.core.report(error, "Uploader.setProvider");
    }
  }

  /**
   * Tells the optional `listener` the upload is over.
   * A failure is logged and passed to `onError`; the returned promise never rejects.
   */
  async notify(listener: UploadListener | null): Promise<void> {
    try {
      await lending(this.core, (lend) => {
        const w = new UndraWriter();
        optionalHandle.encode(w, listener === null ? null : lend(listener, UploadListenerCallback));
        return this.core.call(
          { target: CallTarget.ObjectMethod, handle: this.handle },
          UndraIds.Objects.Uploader.notify,
          w.finish(),
        );
      });
    } catch (error) {
      this.core.report(error, "Uploader.notify");
    }
  }

  /**
   * Follows the progress of `watch`, telling `listener`.
   * Iterating throws UndraCallError; leaving the loop early ends the stream quietly.
   */
  follow(watch: Watch, listener: UploadListener): AsyncIterable<number> {
    const source = lendingStream(this.core, (lend) => {
      const w = new UndraWriter();
      w.writeU64(requireOwn(this.core, watch));
      w.writeU64(lend(listener, UploadListenerCallback));
      return this.core.stream(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Uploader.follow,
        w.finish(),
      );
    });
    return decodeStream(source, codecs.u32, (error) => UndraCallError.mappedStream(error));
  }

  /**
   * Follows the uploads, telling `listener`; a stream that can fail to open.
   * Iterating throws UploadError or UndraCallError; leaving the loop early ends the stream quietly.
   */
  followChecked(listener: UploadListener | null): AsyncIterable<number> {
    const source = lendingStream(this.core, (lend) => {
      const w = new UndraWriter();
      optionalHandle.encode(w, listener === null ? null : lend(listener, UploadListenerCallback));
      return this.core.stream(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Uploader.followChecked,
        w.finish(),
      );
    });
    return decodeStream(
      source,
      codecs.u32,
      (error) => UndraCallError.mappedStream(error, UploadErrorCodec),
    );
  }
}

/** A subscription. */
export class Watch extends UndraObject {
  private constructor(core: UndraCore, handle: bigint) {
    super(core, handle);
  }

  /** @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached. */
  async id(): Promise<number> {
    try {
      const body = await this.core.call(
        { target: CallTarget.ObjectMethod, handle: this.handle },
        UndraIds.Objects.Watch.id,
        new Uint8Array(0),
      );
      return decodeValue(codecs.u32, body);
    } catch (error) {
      throw UndraCallError.mapped(error);
    }
  }
}

/**
 * Tells `listener` about every upload as it happens.
 * Iterating throws UndraCallError; leaving the loop early ends the stream quietly.
 */
export function tail(
  listener: UploadListener,
  core: UndraCore = UndraGoldenCallbacks.core,
): AsyncIterable<number> {
  const source = lendingStream(core, (lend) => {
    const w = new UndraWriter();
    w.writeU64(lend(listener, UploadListenerCallback));
    return core.stream({ target: CallTarget.FreeFunction }, UndraIds.Functions.tail, w.finish());
  });
  return decodeStream(source, codecs.u32, (error) => UndraCallError.mappedStream(error));
}

/**
 * Calls `listener` once and returns how many arguments it had.
 * @throws {UndraCallError} If the core panics, refuses or cancels the call, or cannot be reached.
 */
export async function withListener(
  listener: UploadListener,
  core: UndraCore = UndraGoldenCallbacks.core,
): Promise<number> {
  try {
    const body = await lending(core, (lend) => {
      const w = new UndraWriter();
      w.writeU64(lend(listener, UploadListenerCallback));
      return core.call(
        { target: CallTarget.FreeFunction },
        UndraIds.Functions.withListener,
        w.finish(),
      );
    });
    return decodeValue(codecs.u32, body);
  } catch (error) {
    throw UndraCallError.mapped(error);
  }
}

/** Decodes every item of a core stream; a failure of the stream or of an item goes through `mapError`. */
async function* decodeStream<T>(
  source: AsyncIterable<Uint8Array>,
  codec: Codec<T>,
  mapError: (error: unknown) => unknown,
): AsyncGenerator<T, void, undefined> {
  try {
    for await (const body of source) yield decodeValue(codec, body);
  } catch (error) {
    throw mapError(error);
  }
}

const optionalHandle = codecs.option(codecs.u64);
