// Generated by keel-bindgen from the Keel schema of `golden-records` (schema hash 0x0fd9f3ca8e2a558a). Do not edit.

/**
 * Stable wire identifiers (SPEC section 1.1), for logs and debugging, plus the schema
 * hash to pass to `KeelCore.load` as `expectedSchemaHash`.
 */
export const KeelIds = {
  schemaHash: 0x0fd9f3ca8e2a558an,
  Objects: {
  },
  Functions: {
  },
  Ports: {
  },
  Queries: {
  },
} as const;
