// Generated by undra-bindgen from the Undra schema of `golden-errors` (schema hash 0x8005bee6ac51e549). Do not edit.

import { type Codec, codecs } from "@undra/runtime";
import { type Boxed, BoxedCodec, type HttpError, HttpErrorCodec } from "./errors.js";

export interface Payload {
  text: string;
  failure: HttpError | null;
  history: Boxed[];
}

export const PayloadCodec: Codec<Payload> = {
  encode(w, v) {
    w.writeStr(v.text);
    codecs.option(HttpErrorCodec).encode(w, v.failure);
    codecs.vec(BoxedCodec).encode(w, v.history);
  },
  decode(r) {
    return {
      text: r.readStr(),
      failure: codecs.option(HttpErrorCodec).decode(r),
      history: codecs.vec(BoxedCodec).decode(r),
    };
  },
};
