// Generated by undra-bindgen from the Undra schema of `golden-queries` (schema hash 0xbfc1afa630b0b63d). Do not edit.
@file:Suppress("ALL", "ktlint")

package golden.queries

import dev.undra.runtime.CoreEntry
import dev.undra.runtime.LoadOptions
import dev.undra.runtime.NativeApi
import dev.undra.runtime.NativeCallbacks
import dev.undra.runtime.NativeLibrary
import dev.undra.runtime.UndraCore

/**
 * The JNI natives of the core `golden_queries`: `libgolden_queries.so`, whose `JNI_OnLoad` registers
 * them on this class (ADR-044). Loading the library is what makes them callable; while it
 * cannot be loaded, [isAvailable] is `false` and [unavailableReason] says why.
 */
internal object UndraCoreNative : NativeApi {
    override val namespace: String = "golden_queries"

    private val loadFailure: Throwable? = NativeLibrary.load(namespace)

    override val isAvailable: Boolean get() = loadFailure == null
    override val unavailableReason: Throwable? get() = loadFailure

    override external fun abiVersion(): Int
    override external fun schemaHash(): Long
    override external fun schemaJson(): ByteArray
    override external fun init(cfg: ByteArray, cb: NativeCallbacks): Int
    override external fun call(payload: ByteArray): Int
    override external fun callSync(payload: ByteArray): ByteArray
    override external fun cancel(callId: Int)
    override external fun streamCredit(callId: Int, credit: Int)
    override external fun observe(handle: Long, signalId: Int, on: Boolean)
    override external fun release(handle: Long)
    override external fun portReply(payload: ByteArray)
    override external fun event(portId: Int, methodId: Int, payload: ByteArray)
    override external fun timerFired(timerId: Int)
    override external fun snapshot(): ByteArray
    override external fun restore(snapshot: ByteArray): Int
    override external fun statsJson(): String
    override external fun shutdown()
}

/**
 * The core these bindings belong to, `golden_queries` (`[core] namespace` in undra.toml): [load]
 * starts it, and [core] is the core every generated class and function of this package uses
 * unless it is given another one (`ctx`).
 *
 * ```kotlin
 * val core = UndraGoldenQueries.load() // in this process
 * val dev = UndraGoldenQueries.load(LoadOptions(Mode.REMOTE, remoteUrl = "ws://10.0.2.2:7878")) // `undra dev`
 * ```
 */
object UndraGoldenQueries {
    /** The core's namespace: its library is `libgolden_queries.so`. */
    const val NAMESPACE: String = "golden_queries"

    private val entry = CoreEntry(NAMESPACE, UndraIds.SCHEMA_HASH) { UndraCoreNative }

    /**
     * Loads the core (in this process unless [options] say otherwise) and makes it [core].
     *
     * @throws UndraSchemaMismatchException if the core was built from another schema.
     * @throws UndraException if it cannot start, or this core is already loaded.
     */
    fun load(options: LoadOptions = LoadOptions()): UndraCore = entry.load(options)

    /**
     * The loaded core, or, while none is loaded (or after it was closed), a closed placeholder
     * whose calls fail with `UndraCallError.Unavailable`.
     */
    val core: UndraCore get() = entry.core
}
