// Generated by undra-bindgen from the Undra schema of `golden-queries` (schema hash 0xbfc1afa630b0b63d). Do not edit.

package golden.queries

import dev.undra.runtime.UndraException
import dev.undra.runtime.UndraReplyException
import dev.undra.runtime.wire.Payloads.ReplyStatus
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import dev.undra.runtime.wire.decodeAll

sealed class TodoError(message: String) : UndraException(message) {
    data object Offline : TodoError("offline")

    companion object : UndraCodec<TodoError> {
        override fun encode(w: UndraWriter, v: TodoError) {
            when (v) {
                Offline -> w.writeU16(0u)
            }
        }

        override fun decode(r: UndraReader): TodoError {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> Offline
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "TodoError")
            }
        }

        /** The typed error a failed call carries; any other failure is returned unchanged. */
        fun fromReply(error: UndraReplyException): Throwable {
            return if (error.status == ReplyStatus.ERROR) decodeAll(error.body) else error
        }
    }
}
