// Generated by undra-bindgen from the Undra schema of `golden-queries` (schema hash 0xbfc1afa630b0b63d). Do not edit.

package golden.queries

import dev.undra.runtime.UndraEnum
import dev.undra.runtime.UndraRecord
import dev.undra.runtime.wire.Codecs
import dev.undra.runtime.wire.UndraCodec
import dev.undra.runtime.wire.UndraReader
import dev.undra.runtime.wire.UndraWriter
import dev.undra.runtime.wire.WireException
import java.util.UUID

data class Page(
    val items: List<Todo>,
    val total: ULong,
) : UndraRecord {
    companion object : UndraCodec<Page> {
        override fun encode(w: UndraWriter, v: Page) {
            codecVecTodo.encode(w, v.items)
            w.writeU64(v.total)
        }

        override fun decode(r: UndraReader): Page = Page(
            items = codecVecTodo.decode(r),
            total = r.readU64(),
        )
    }
}

data class Todo(
    val id: UUID,
    val title: String,
) : UndraRecord {
    companion object : UndraCodec<Todo> {
        override fun encode(w: UndraWriter, v: Todo) {
            Codecs.uuid.encode(w, v.id)
            w.writeStr(v.title)
        }

        override fun decode(r: UndraReader): Todo = Todo(
            id = Codecs.uuid.decode(r),
            title = r.readStr(),
        )
    }
}

/** The fetch state of a query (SPEC section 9). */
enum class QueryStatus(val index: UShort) : UndraEnum {
    /** No fetch has started. */
    IDLE(0u),
    /** A fetch is in flight. */
    FETCHING(1u),
    /** The latest fetch succeeded. */
    SUCCESS(2u),
    /** The latest fetch failed. */
    ERROR(3u);

    companion object : UndraCodec<QueryStatus> {
        override fun encode(w: UndraWriter, v: QueryStatus) = w.writeU16(v.index)

        override fun decode(r: UndraReader): QueryStatus {
            val at = r.position
            return when (val tag = r.readU16().toInt()) {
                0 -> IDLE
                1 -> FETCHING
                2 -> SUCCESS
                3 -> ERROR
                else -> throw WireException.InvalidTag(tag.toUInt(), at, "QueryStatus")
            }
        }
    }
}

private val codecVecTodo = Codecs.vec(Todo)
